import React,{useState} from 'react';
import {LockKeyhole,Check,Heart,Leaf,X} from 'lucide-react';
import ProfileNail from '../ProfileNail';
import {DAILY,NAILS,UNDERTONES,lifestyle,practicalSuggestions,colorSuggestions} from './model';
import './lifestyle.css';
export function LifestyleSummary({profile,onOpen}){const p=lifestyle(profile.lifestyle);return <section className="nmBento lifeSummary"><small className="nmEyebrow"><LockKeyhole size={13}/> RIEN QUE POUR MOI</small><h2>À mon rythme</h2><p>Mon quotidien, mes envies et les détails qui comptent pour mes ongles.</p><div className="lifeTags">{DAILY.filter(([id])=>p.daily.includes(id)).slice(0,3).map(([id,label])=><span key={id}>{label}</span>)}</div><button className="outline" onClick={onOpen}>{p.daily.length?'Retrouver mes repères':'Personnaliser mes repères'}</button></section>;}
function Options({legend,options,values,onToggle,single=false}){return <fieldset className="lifeOptions"><legend>{legend}</legend><div>{options.map(([id,label])=><button type="button" key={id} aria-pressed={values.includes(id)} onClick={()=>onToggle(id)}>{values.includes(id)&&<Check size={15}/>}<span>{label}</span></button>)}</div></fieldset>;}
export default function LifestyleProfile({profile,onChange,onCreate}){const p=lifestyle(profile.lifestyle),[ingredient,setIngredient]=useState(''),[notice,setNotice]=useState('');
 const save=patch=>{const next=lifestyle({...p,...patch});if(onChange({...profile,lifestyle:next}))setNotice('Tes repères sont enregistrés.');};
 const toggle=(key,id)=>save({[key]:p[key].includes(id)?p[key].filter(x=>x!==id):[...p[key],id]});
 const suggestions=practicalSuggestions(p),colors=colorSuggestions(p);
 return <div className="lifePage"><section className="lifeIntro"><Heart/><small className="nmEyebrow">MES ONGLES, MA VIE</small><h2>Des idées à mon rythme.</h2><p>Quelques repères facultatifs pour personnaliser tes envies. Tu peux tout modifier ou effacer. En mode découverte, ils restent sur cet appareil. Avec un compte, ils sont synchronisés dans ton profil privé.</p><span className="lifePrivate"><LockKeyhole size={14}/> Toujours privés, même sur ton profil public</span></section>
 <section className="lifeCard"><h2>Mon quotidien</h2><Options legend="Ce qui compte pour moi" options={DAILY} values={p.daily} onToggle={id=>toggle('daily',id)}/></section>
 <section className="lifeCard"><h2>Mes ongles aujourd’hui</h2><p>Ce que tu observes toi-même, sans diagnostic.</p><Options legend="Mes observations" options={NAILS} values={p.nails} onToggle={id=>{let nails=p.nails.includes(id)?p.nails.filter(x=>x!==id):[...p.nails,id];if(id==='normal'&&nails.includes(id))nails=['normal'];else if(id!=='normal')nails=nails.filter(x=>x!=='normal');save({nails});}}/>{p.nails.includes('other')&&<label>Mon observation personnelle<input maxLength={120} value={p.nailNote} onChange={e=>save({nailNote:e.target.value})}/></label>}{p.nails.some(x=>['sensitive','after_removal','brittle','splitting'].includes(x))&&<div className="lifeGentle"><Leaf size={22}/><div><b>À ton rythme</b><p>Tu peux garder une inspiration pour plus tard ou choisir une pause personnelle. Ces observations ne déterminent ni produit adapté ni durée de soin.</p></div></div>}</section>
 <section className="lifeCard"><h2>Des formes à explorer</h2><p>Tes activités suggèrent des pistes, jamais une forme imposée.</p>{suggestions.length?<div className="lifeRecommendations">{suggestions.map(s=><article key={s.shape}><ProfileNail variant={{Ronde:'round',Ovale:'oval',Carrée:'square',Amande:'almond'}[s.shape]}/><h3>{s.shape}</h3><b>{s.length}</b><p>{s.reason}</p><button type="button" className="outline" onClick={()=>{if(onChange({...profile,shape:s.shape,length:s.length}))setNotice(`${s.shape} · ${s.length} ajouté à tes préférences.`);}}>Choisir {s.shape}</button></article>)}</div>:<p>Choisis quelques activités pour découvrir des suggestions.</p>}<button className="outline" onClick={onCreate}>Voir des idées avec mes préférences</button></section>
 <section className="lifeCard"><h2>Mes envies de couleur</h2><Options legend="Mon sous-ton, si je souhaite l’utiliser" options={UNDERTONES} values={[p.undertone]} onToggle={id=>save({undertone:id})}/>{colors.length>0&&<><p>Quelques pistes à essayer : {colors.join(', ')}.</p><p>Toutes les couleurs restent possibles. Aucun produit n’est masqué.</p></>}</section>
 <section className="lifeCard"><h2>Mes ingrédients à surveiller</h2><p>Choisis les noms à repérer dans une vraie liste INCI. Une mention n’est pas un diagnostic d’allergie.</p><Options legend="Ajouter un repère" options={['HEMA','Di-HEMA'].map(x=>[x,x])} values={p.watch} onToggle={id=>toggle('watch',id)}/><form onSubmit={e=>{e.preventDefault();if(ingredient.trim()&&p.watch.length<30){save({watch:[...p.watch,ingredient.trim()]});setIngredient('');}}}><label>Autre nom INCI<input value={ingredient} maxLength={120} onChange={e=>setIngredient(e.target.value)} placeholder="Nom exact de l’ingrédient"/></label><button className="outline" disabled={!ingredient.trim()||p.watch.length>=30}>Ajouter à ma liste</button></form><div className="lifeTags">{p.watch.map(x=><button key={x} aria-label={'Retirer '+x} onClick={()=>save({watch:p.watch.filter(v=>v!==x)})}>{x}<X size={14}/></button>)}</div><p>HEMA et Di-HEMA sont recherchés séparément. L’absence de correspondance ne signifie pas qu’un produit est sans risque.</p></section>
 <p className="lifeStatus" role="status">{notice}</p><button className="outline" onClick={()=>{if(window.confirm('Effacer ces repères privés ? Tes préférences de pose et tes univers restent conservés.'))save({daily:[],nails:[],nailNote:'',undertone:'off',watch:[]});}}>Effacer mes repères privés</button></div>;
}
