import React,{useEffect,useState} from 'react';
import Sheet from '../Sheet';
import PublicProfile from '../identity/PublicProfile';
export default function Discovery({client}) {
 const [open,setOpen]=useState(false),[mode,setMode]=useState('discover'),[query,setQuery]=useState(''),[rows,setRows]=useState([]),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[handle,setHandle]=useState(null);
 async function call(action,data){const r=await client.rpc('nm_discover',{p_action:action,p_data:data});if(r.error)throw r.error;return r.data;}
 async function load(page=0){setBusy(true);try{setRows(await call(mode,{query,offset:page}));setOffset(page);setError('');}catch{setError('Chargement impossible. Réessaie.');}finally{setBusy(false);}}
 useEffect(()=>{if(open)load();},[open,mode]);
 async function favorite(row){try{await call(row.saved?'remove':'add',{id:row.id,kind:row.kind});await load(offset);}catch{setError('Ce contenu n’est plus disponible ou la sauvegarde a échoué.');}}
 return <section className="card"><h2>Découvrir et sauvegarder</h2><p>Les inspirations et poses que leurs propriétaires ont rendues publiques.</p><button className="identitySearchButton" onClick={()=>setOpen(true)}>Découverte · Mes favoris sociaux</button>{open&&<Sheet title="Découvrir NailMoods" onClose={()=>setOpen(false)} className="socialSheet"><div className="socialTabs"><button onClick={()=>setMode('discover')} aria-pressed={mode==='discover'}>Découverte</button><button onClick={()=>setMode('favorites')} aria-pressed={mode==='favorites'}>Mes favoris</button></div><form onSubmit={e=>{e.preventDefault();load();}}><label>Mood, titre ou @identifiant<input value={query} maxLength={80} onChange={e=>setQuery(e.target.value)}/></label><button disabled={busy}>Rechercher</button></form>{error&&<p role="alert">{error}</p>}{busy?<p>Chargement…</p>:!rows.length?<p>Aucun contenu public disponible pour cette recherche.</p>:rows.map(r=><article className="socialPerson" key={r.kind+r.id}><b>{r.title||'Inspiration'}</b><span>@{r.handle} · {r.mood}</span><div><button onClick={()=>setHandle(r.handle)}>Voir le profil et le contenu</button><button onClick={()=>favorite(r)}>{r.saved?'Retirer des favoris':'Sauvegarder'}</button></div></article>)}<div className="socialTabs"><button disabled={busy||offset===0} onClick={()=>load(Math.max(0,offset-20))}>Précédent</button><button disabled={busy||rows.length<20} onClick={()=>load(offset+20)}>Suivant</button></div></Sheet>}{handle&&<PublicProfile client={client} handle={handle} onClose={()=>setHandle(null)}/>}</section>;
}
