import React,{useEffect,useMemo,useRef,useState} from 'react';
import {useSocial} from './SocialContext';
import {useStorage} from '../StorageContext';
import {Button} from '../design/UI';
import Sheet from '../Sheet';
import NailPreview from '../NailPreview';
import ProNailEditor from '../workspaces/ProNailEditor';
import {poseRepository} from '../poseCycle/repository';
import {projectFromIdea} from '../poseCycle/model';
import {proposalIdea} from './proposal';
import {receivedShareIdea} from './receivedShare';
import {poLoopService,briefDesign,applyBriefDesign,replySnapshot} from './poLoop.js';
import './po-loop.css';
export default function PoLoop({client,id,snapshot}){
 const social=useSocial(),storage=useStorage(),[state,setState]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[drawing,setDrawing]=useState(false),[idea,setIdea]=useState(null),[project,setProject]=useState(null),[canSave,setCanSave]=useState(false),[opened,setOpened]=useState(null);
 const principal={userId:social?.userId||storage.userId,workspaceId:storage.workspaceId};const service=useMemo(()=>poLoopService(client),[client]);
 const repo=useMemo(()=>principal.userId&&principal.workspaceId?poseRepository(client,principal):null,[client,principal.userId,principal.workspaceId]);const attempt=useRef(null);
 async function refresh(){const s=await service.run('state',id);setState(s);return s;}
 useEffect(()=>{let active=true;setState(null);setError('');setEditing(false);setIdea(null);setProject(null);service.run('state',id).then(s=>{if(active)setState(s);}).catch(()=>{if(active)setError('Les actions de cet échange sont indisponibles. Actualise pour vérifier ton accès.');});return()=>{active=false;};},[service,id,principal.userId]);
 async function run(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(String(e?.message||'').includes('reply_too_large')?'Le dessin est trop détaillé pour ce partage. Réduis le nombre de traits avant de réessayer.':'L’action n’a pas abouti. Vérifie votre connexion et réessaie ; rien n’a été publié.');}finally{setBusy(false);}}
 async function adapt(){await service.run('state',id);if(!repo)throw Error('Compte requis');const list=await repo.list('projects');const draft=list.find(p=>p.legacy_key==='po-adaptation:'+id);setProject(draft||null);setIdea(draft?.details.composition||receivedShareIdea(snapshot,id));setEditing(true);setCanSave(false);}
 async function saveDraft(){if(!repo||!idea)throw Error('Projet indisponible');let row=project;if(row)row=await repo.save('projects',{...row,title:idea.title,details:{...row.details,composition:idea}});else{const p=projectFromIdea(idea,principal);p.legacy_key='po-adaptation:'+id;row=await repo.importLegacy(p);if(JSON.stringify(row.details.composition)!==JSON.stringify(idea))row=await repo.save('projects',{...row,title:idea.title,details:{...row.details,composition:idea}});}setProject(row);return row;}
 async function saveResponse(){const r=await client.rpc('nm_proposal_for_save',{p_id:id});if(r.error)throw r.error;const next=proposalIdea(r.data,id),p=projectFromIdea(next,principal);p.legacy_key='po-response:'+id;const saved=await repo.importLegacy(p);setOpened(saved.id);setNotice('Cette proposition est dans tes projets privés. Tu peux la planifier ou créer une variante.');}
 async function send(){await saveDraft();const snapshot=replySnapshot(idea),key=JSON.stringify([id,snapshot,canSave]);if(attempt.current?.key!==key)attempt.current={key,id:crypto.randomUUID()};const result=await service.run('reply',id,{...snapshot,can_save:canSave,client_id:attempt.current.id});await refresh();social?.refresh?.();setEditing(false);setNotice('Ta proposition a été envoyée dans votre conversation privée.');location.hash='partage/'+result.id;}
 return <section className="nmPoLoop"><h3>{snapshot.proposal?'Ta proposition, à ton rythme':'Votre brief NailMoods'}</h3>{error&&!editing&&<p role="alert">{error}<button onClick={()=>run(refresh)} disabled={busy}>Réessayer</button></p>}{notice&&!editing&&<p role="status">{notice}</p>}{state?.canAdapt&&<><p>Reprends les cinq ongles dans ton Atelier. Ton adaptation restera privée jusqu’à ton envoi.</p><Button disabled={busy} onClick={()=>run(adapt)}>Adapter dans l’Atelier</Button></>}{state?.isRecipient&&snapshot.proposal&&<div className="nmPoActions"><Button variant="secondary" disabled={busy} aria-pressed={state.liked} onClick={()=>run(async()=>{const s=await service.run('like',id,{liked:!state.liked});setState(v=>({...v,liked:s.liked}));setNotice(s.liked?'Ton « J’adore » est visible par ta PO.':'Réaction retirée.');})}>{state.liked?'♥ Tu adores':'♡ J’adore'}</Button>{snapshot.can_save&&repo&&<Button disabled={busy} onClick={()=>run(saveResponse)}>Ajouter à ma prochaine pose</Button>}</div>}{opened&&<Button variant="secondary" onClick={()=>{location.hash='creer/pose/'+opened;}}>Ouvrir mon projet / créer une variante</Button>}{state&&!state.isRecipient&&snapshot.proposal&&<p>{state.liked?'♥ Ta cliente adore cette proposition.':'Ta proposition attend le retour de ta cliente.'}</p>}{state?.parentId&&<a href={'#partage/'+state.parentId}>Revoir le brief d’origine</a>}{state?.replies?.length>0&&<div className="nmPoReplies"><h4>Vos propositions</h4>{state.replies.map(r=><a key={r.id} href={'#partage/'+r.id}><b>{r.title}</b><span>{new Date(r.createdAt).toLocaleDateString('fr-FR')}{r.liked?' · ♥ J’adore':''}</span></a>)}</div>}
 {editing&&idea&&<Sheet title="Mon interprétation du brief" eyebrow="ATELIER · ÉCHANGE PRIVÉ" className="proEditorSheet" onClose={()=>!busy&&setEditing(false)}><div className="nmPoEditor">{drawing?<ProNailEditor design={briefDesign(idea)} onDraft={()=>{}} onSave={d=>{setIdea(applyBriefDesign(idea,d));setDrawing(false);}} onClose={()=>setDrawing(false)} collectionColors={[]} colorRoles={idea.palette.map(p=>({color:p.color,role:p.name}))}/>:<><label>Nom de ma proposition<input maxLength={120} value={idea.title} onChange={e=>setIdea(v=>({...v,title:e.target.value}))}/></label><NailPreview idea={idea}/><Button variant="secondary" onClick={()=>setDrawing(true)}>Dessiner / adapter les cinq ongles</Button><label className="nmPoCheck"><input type="checkbox" checked={canSave} onChange={e=>setCanSave(e.target.checked)}/><span>Autoriser ma cliente à enregistrer cette composition dans ses projets et à en créer des variantes.</span></label><p>Les photos et les notes du brief ne sont pas renvoyées. Vérifie cet aperçu avant de confirmer.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="nmPoActions"><Button variant="secondary" disabled={busy||!idea.title.trim()} onClick={()=>run(async()=>{await saveDraft();setNotice('Brouillon privé enregistré.');})}>Garder mon brouillon</Button><Button disabled={busy||!idea.title.trim()} onClick={()=>run(send)}>Confirmer et envoyer ma proposition</Button></div></>}</div></Sheet>}
 </section>;
}
