import {useStorage} from '../StorageContext';
import {readInspirations,saveProject,INSPIRATIONS_KEY} from '../inspirations';
import {proposalIdea} from './proposal';
import React,{useState} from 'react';
import ContentImage from './ContentImage';
import NailPreview from '../NailPreview';
import Sheet from '../Sheet';
import {poShareService} from './poShareService';
export function ShareDetails({client,snapshot:s,id}){const storage=useStorage(),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);async function save(){setSaving(true);try{const{data,error}=await client.rpc('nm_proposal_for_save',{p_id:id});if(error)throw error;const next=saveProject(readInspirations(storage),proposalIdea(data,id));storage.setItem(INSPIRATIONS_KEY,JSON.stringify(next));window.dispatchEvent(new Event('nm-library-updated'));setNotice('Composition enregistrée dans Mes projets.');}catch{setNotice('La proposition ne peut pas être enregistrée. Vérifie les droits de partage.');}finally{setSaving(false);}}return <div className="poShareSummary"><h3>{s.title}</h3>{s.preview?.nails?.length===5&&<NailPreview idea={s.preview} compact/>}<div>{(s.colors||[]).map((c,i)=><i key={i} style={{background:c}}/>)}</div><p>{[s.mood,s.level,...(s.techniques||[])].filter(Boolean).join(' · ')}</p><p><b>{s.proposal?'Produits proposés :':'Produits cliente :'}</b> {(s.products||[]).map(p=>[p.brand,p.name,p.reference].filter(Boolean).join(' ')).join(' · ')||'À préciser'}</p><p><b>Produits manquants :</b> {(s.missing||[]).join(' · ')||'À vérifier'}</p><p><b>Matériel :</b> {[...(s.equipment||[]).map(p=>p.name),...(s.requirements||[])].join(' · ')||'À préciser'}</p>{s.include_notes&&s.notes&&<p className="shareNotes"><b>Notes jointes volontairement :</b> {s.notes}</p>}{id&&s.include_images&&<div className="photoThumbs">{(s.images||[]).map((_,i)=><ContentImage key={i} client={client} kind="share" id={id} index={i} title={'Référence partagée '+(i+1)}/>)}</div>}{id&&s.proposal&&s.can_save&&<><button disabled={saving} onClick={save}>Enregistrer la composition dans Mes projets</button><small>Les photos et notes jointes restent dans cet échange privé.</small></>}{notice&&<p role="status">{notice}</p>}</div>;}
export default function ShareCard({client,snapshot,id}){const [detail,setDetail]=useState(null),[error,setError]=useState('');return <><div className="poShareSummary"><b>{snapshot.title}</b><div>{(snapshot.colors||[]).map((c,i)=><i key={i} style={{background:c}}/>)}</div><small>{snapshot.mood} · {snapshot.level}</small><button onClick={async()=>{setError('');try{setDetail(await poShareService(client).detail(id));}catch{setError('Cette fiche n’est plus accessible.');}}}>Ouvrir la fiche partagée</button>{error&&<p role="status">{error}</p>}</div>{detail&&<Sheet title="Fiche partagée" onClose={()=>setDetail(null)}><ShareDetails client={client} id={id} snapshot={detail}/><button onClick={async()=>{try{await navigator.clipboard.writeText(new URL('#partage/'+id,window.location.href).href);setError('Lien copié, réservé aux participants.');}catch{setError('Copie indisponible.');}}}>Copier le lien privé</button></Sheet>}</>;}
