import React,{useEffect,useState,useRef} from 'react';
import Sheet from '../Sheet';
import PublicProfile from '../identity/PublicProfile';
import './social-beta.css';
export async function socialCall(client,action,data={}) { const r=await client.rpc('nm_social',{p_action:action,p_data:data});if(r.error)throw r.error;return r.data; }
export function ConnectionAction({client,handle}) {
 const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 return <div><button className="detailSecondary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await socialCall(client,'request',{handle});setNotice(r.status==='accepted'?'Déjà connecté·es — retrouve cette personne dans Mes connexions.':r.outgoing?'Demande envoyée.':'Cette personne t’a déjà invitée : accepte depuis Mes connexions.');}catch{setNotice('Invitation impossible. Vérifie que ce profil est visible et différent du tien.');}finally{setBusy(false);}}}>Se connecter / Inviter</button>{notice&&<p role="status">{notice}</p>}</div>;
}
export function Conversation({client,peer,onClose}) {
 const alive=useRef(true);
 const [messages,setMessages]=useState([]),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[older,setOlder]=useState(true);
 async function load(before){try{const r=await socialCall(client,'history',{user_id:peer.user_id,...(before?{before}:{})});if(!alive.current)return;setMessages(old=>before?[...old,...r.messages]:r.messages);setOlder(r.messages.length===40);await socialCall(client,'read',{user_id:peer.user_id});}catch{setError('Conversation indisponible. Une connexion acceptée est nécessaire.');}}
 useEffect(()=>{let active=true;alive.current=true;load();const timer=setInterval(()=>{if(active&&document.visibilityState==='visible')load();},20000);return()=>{active=false;alive.current=false;clearInterval(timer);};},[peer.user_id]);
 async function send(e){e.preventDefault();setBusy(true);setError('');try{await socialCall(client,'send',{user_id:peer.user_id,body,client_id:crypto.randomUUID()});setBody('');await load();}catch{setError('Message non envoyé. Réessaie dans un instant.');}finally{setBusy(false);}}
 return <Sheet title={peer.display_name||'Conversation'} eyebrow={'@'+peer.handle} onClose={onClose} className="socialSheet"><p>Échange privé · messages texte uniquement</p>{error&&<p role="alert">{error}</p>}<button onClick={()=>load()}>Actualiser</button>{older&&messages.length>0&&<button onClick={()=>load(messages.at(-1).created_at)}>Messages précédents</button>}<div className="socialMessages">{[...messages].reverse().map(m=><article key={m.id} className={m.mine?'mine':''}><p>{m.body}</p>{m.share&&<div className="poShareSummary"><b>{m.share.title}</b><div>{(m.share.colors||[]).map(c=><i key={c} style={{background:c}}/>)}</div><small>{(m.share.techniques||[]).join(" · ")} · {m.share.level}</small><p>{m.share.mood}</p><p>Matériel : {(m.share.requirements||[]).join(" · ")||"À vérifier avec la cliente"}</p></div>}<time>{new Date(m.created_at).toLocaleString('fr-FR')}</time></article>)}</div><form onSubmit={send}><label>Ton message<textarea value={body} maxLength={2000} onChange={e=>setBody(e.target.value)} required/></label><button disabled={busy||!body.trim()}>{busy?'Envoi…':'Envoyer'}</button></form></Sheet>;
}
export default function SocialHub({client}) {
 const [open,setOpen]=useState(false),[rows,setRows]=useState([]),[tab,setTab]=useState('accepted'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[peer,setPeer]=useState(null),[profile,setProfile]=useState(null);
 async function load(){setBusy(true);try{setRows(await socialCall(client,'list'));setError('');}catch{setError('Les connexions sont momentanément indisponibles.');}finally{setBusy(false);}}
 useEffect(()=>{load();const timer=setInterval(()=>{if(document.visibilityState==='visible')load();},60000);return()=>clearInterval(timer);},[]);
 async function act(action,id){setBusy(true);try{await socialCall(client,action,{id});await load();}catch{setError('Action non effectuée. Actualise puis réessaie.');}finally{setBusy(false);}}
 const filtered=rows.filter(r=>tab==='accepted'?r.status==='accepted':r.status==='pending'&&r.outgoing===(tab==='sent'));
 return <section className="card"><small>SOCIAL BÊTA</small><h2>Mes connexions</h2><p>Retrouve tes contacts, tes invitations et tes messages.</p><button className="identitySearchButton" onClick={()=>setOpen(true)}>Connexions et messagerie {rows.some(r=>r.status==='pending'&&!r.outgoing||Number(r.unread)>0)&&"· Nouveau"}</button>{open&&<Sheet title="Mes connexions" onClose={()=>setOpen(false)} className="socialSheet"><div className="socialTabs">{[['accepted','Connexions'],['received','Reçues'],['sent','Envoyées']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div><button disabled={busy} onClick={load}>Actualiser</button>{busy&&<p role="status">Chargement…</p>}{error&&<p role="alert">{error}</p>}{!busy&&!filtered.length&&<p>Aucune {tab==='accepted'?'connexion':'demande'} pour le moment. Recherche un @NailMoodsID depuis ton profil pour inviter une personne.</p>}{filtered.map(r=><article className="socialPerson" key={r.id}><b>{r.display_name}</b><span>@{r.handle} · {r.account_tier==='pro'?'Pro':'Particulier'}</span><small>{r.status==='accepted'?'Connecté·es':r.outgoing?'Demande envoyée':'Demande reçue'}{Number(r.unread)>0?` · ${r.unread} non lu(s)`:''}</small><div><button onClick={()=>setProfile(r.pro_handle||r.handle)}>Voir le profil</button>{r.status==='accepted'?<><button onClick={()=>setPeer(r)}>Envoyer un message</button><button disabled={busy} onClick={()=>{if(window.confirm('Retirer cette connexion ? Les nouveaux échanges seront bloqués.'))act('remove',r.id);}}>Retirer</button></>:r.outgoing?<button disabled={busy} onClick={()=>act('remove',r.id)}>Annuler</button>:<><button disabled={busy} onClick={()=>act('accept',r.id)}>Accepter</button><button disabled={busy} onClick={()=>act('decline',r.id)}>Refuser</button></>}</div></article>)}</Sheet>}{peer&&<Conversation client={client} peer={peer} onClose={()=>{setPeer(null);load();}}/>}{profile&&<PublicProfile client={client} handle={profile} onClose={()=>setProfile(null)}/>}</section>;
}
