import React,{useEffect,useRef,useState} from 'react';
import {ArrowUp,Square,Trash2,Sparkles,TrendingUp,ImagePlus,Palette,Brush,Camera,Check,ChevronRight,ShieldCheck,Power} from 'lucide-react';
import Sheet from '../Sheet';
import NailPreview from '../NailPreview';
import AtelierArt from '../design/AtelierArt';
import {useSocial} from '../social/SocialContext';
import {useStorage} from '../StorageContext';
import {compositionImage,drawingReference} from '../aiPlus/compositionImage';
import {CONCEPT_COLORS,SHAPES,LENGTHS} from '../../supabase/functions/nailmoods-ai/contract.mjs';
import {assistantEnabled,localPlan,ideaFromPlan,productContext,tutorialFor,minimalComposition,withResultMedia,AI_MESSAGES} from './model';
import {assistantCall,awaitAssistantJob} from './service';
import './assistant.css';
// The AI entry belongs only to the creation source grid; access stays server-gated.
export function AssistantEntry({onOpen}){const social=useSocial();const [visible,setVisible]=useState(false);useEffect(()=>{let active=true;setVisible(false);if(assistantEnabled(import.meta.env)&&social?.client)assistantCall(social.client,{action:'access'}).then(a=>{if(active)setVisible(a.uiAccess===true);}).catch(()=>{});return()=>{active=false;};},[social?.client,social?.userId]);if(!assistantEnabled(import.meta.env)||!visible)return null;return <button type="button" className="sourceCard sourceCard--ai" onClick={onOpen}><AtelierArt source="ai"/><b>NailMoods AI</b><small>Ton idée, en dessin puis en rendu IA</small></button>;}

export function AssistantRenderEntry({onOpen}){const social=useSocial(),[visible,setVisible]=useState(false);useEffect(()=>{let active=true;setVisible(false);if(assistantEnabled(import.meta.env)&&social?.client)assistantCall(social.client,{action:'access'}).then(a=>{if(active)setVisible(a.uiAccess===true&&a.allowed===true&&a.operations?.realistic?.enabled===true);}).catch(()=>{});return()=>{active=false;};},[social?.client,social?.userId]);return visible&&onOpen?<button type="button" className="nmIdeaRenderEntry" onClick={onOpen}><Camera size={16}/>Rendu IA</button>:null;}

export default function Assistant({items,profile,initialIdea,initialRender,onClose,onSave,onOpen,onTutorial,onShare}){
 const social=useSocial(),storage=useStorage(),[prompt,setPrompt]=useState(''),[mode,setMode]=useState('conversation'),[only,setOnly]=useState(false),[consent,setConsent]=useState(false),[messages,setMessages]=useState([]),[idea,setIdea]=useState(initialIdea||null),[image,setImage]=useState(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[access,setAccess]=useState(null),[threads,setThreads]=useState([]),[thread,setThread]=useState(()=>crypto.randomUUID()),[tutorial,setTutorial]=useState(false),[attachment,setAttachment]=useState(null),[deleteAsk,setDeleteAsk]=useState(false),[metrics,setMetrics]=useState(null),[notice,setNotice]=useState(''),[switching,setSwitching]=useState(false),[trends,setTrends]=useState(null),[settings,setSettings]=useState(false),[shape,setShape]=useState(initialIdea?.shape||profile.shape||'Amande'),[length,setLength]=useState(initialIdea?.length||profile.length||'Courte'),[level,setLevel]=useState(initialIdea?.rank??0),[designCount,setDesignCount]=useState(initialIdea?.secondHand?10:5),[renderChoice,setRenderChoice]=useState(initialRender||null),[renderedImage,setRenderedImage]=useState(null),[drawingImage,setDrawingImage]=useState(null),[visualKind,setVisualKind]=useState(null),[quality,setQuality]=useState({});
 const resultPanel=useRef(null),controller=useRef(null),preview=useRef(null),mounted=useRef(true),request=useRef(null),drawingJob=useRef(null);
 useEffect(()=>{mounted.current=true;if(social?.client){assistantCall(social.client,{action:'access'}).then(a=>{if(mounted.current){setAccess(a);if(!a.allowed)setMode('local');}}).catch(()=>{});assistantCall(social.client,{action:'history'}).then(h=>{if(mounted.current)setThreads(h.threads);}).catch(()=>{});}return()=>{mounted.current=false;controller.current?.abort();};},[social?.client,social?.userId]);
 useEffect(()=>{let active=true;if(initialIdea?.ai?.media&&social?.client)for(const media of Object.values(initialIdea.ai.media)){if(media.jobId)assistantCall(social.client,{action:'status',jobId:media.jobId}).then(r=>{if(active&&r.status==='succeeded'&&r.result?.imageUrl)apply({...r.result,jobId:media.jobId},initialIdea);}).catch(()=>{});}return()=>{active=false;};},[initialIdea?.id,social?.client]);
 useEffect(()=>{if(idea||image||trends){const el=resultPanel.current,scroll=el?.closest('.nmAIScroll');if(el&&scroll)scroll.scrollTop=el.offsetTop-scroll.offsetTop;}},[idea,image,trends]);
 const message=e=>AI_MESSAGES[e.message]||'La demande n’a pas abouti. Tes produits et tes droits sont conservés.';
 function apply(result,current=idea){if(result.kind==='plan'){
   const next=ideaFromPlan(result.plan,{products:result.products,items,profile,current,collectionOnly:only,master:result.master});if(next){setShape(next.shape);setLength(next.length);setLevel(next.rank);setDesignCount(next.secondHand?10:5);setIdea(next);setImage(null);setRenderedImage(null);setDrawingImage(null);drawingJob.current=null;setVisualKind(null);setQuality({});setTrends(null);}
   setMessages(m=>[...m,{role:'assistant',text:result.plan.message,action:result.plan.action}]);if(result.plan.action==='tutorial')setTutorial(true);return next;
  }else{if(result.kind==='trends'){setTrends(result);setIdea(null);setImage(null);setRenderedImage(null);setDrawingImage(null);drawingJob.current=null;setVisualKind(null);}setMessages(m=>[...m,{role:'assistant',text:result.message,sources:result.sources}]);if(result.imageUrl){const saved=withResultMedia(current,result);if(saved)setIdea(saved);setQuality(q=>({...q,[result.kind]:result.quality||null}));setImage(result.imageUrl);const kind=result.kind==='illustration'?'illustration':'realistic';setVisualKind(kind);if(kind==='illustration'){setDrawingImage(result.imageUrl);drawingJob.current=result.jobId||result.imagePath?.split('/').at(-1)?.replace(/\.png$/,'')||null;}else setRenderedImage(result.imageUrl);setMode('conversation');setRenderChoice(null);}}}
 async function run(e,operation=mode,inputText=prompt){e?.preventDefault();if(busy||!inputText.trim())return;setError('');setProgress('');setBusy(true);const text=inputText.trim();setMessages(m=>[...m,{role:'user',text}]);setPrompt('');
  try{if(operation==='local'){const p=localPlan(text,{items,profile:{shape,length},collectionOnly:only,current:idea});p.level=level;apply({kind:'plan',plan:p,products:[...productContext(items),...(only?[]:CONCEPT_COLORS)]});}
   else{
    if(!consent)throw Error('consent_required');
    if(navigator.onLine===false)throw Error('offline');
    const sourceDrawing=drawingImage;
    const referenceJobId=operation==='realistic'?drawingJob.current:null;const referenceImage=referenceJobId?undefined:['realistic','illustration'].includes(operation)?(operation==='realistic'&&sourceDrawing?await drawingReference(sourceDrawing):await compositionImage(preview.current)):operation==='vision'?attachment:undefined;
    controller.current=new AbortController();const body={requestId:crypto.randomUUID(),threadId:thread,workspaceId:storage.workspaceId,operation,prompt:text,collectionOnly:only,shape:['realistic','illustration'].includes(operation)?idea.shape:shape,length:['realistic','illustration'].includes(operation)?idea.length:length,level:['realistic','illustration'].includes(operation)?idea.rank:level,designCount:['realistic','illustration'].includes(operation)?(idea.secondHand?10:5):designCount,consent:true,...(referenceImage?{referenceImage}:{}),...(referenceJobId?{referenceJobId}:{}),...(idea?{composition:minimalComposition(idea)}:{})};request.current=body;
    const response=await awaitAssistantJob(social.client,body,controller.current.signal,s=>{if(mounted.current)setProgress(s==='queued'?'En attente…':operation==='realistic'?'Création du rendu IA…':'Création en cours…');});if(!mounted.current)return;
    if(response.status==='succeeded'&&response.result){const next=apply({...response.result,jobId:response.jobId});if(next&&['conversation','vision'].includes(operation)&&['compose','edit'].includes(response.result.plan?.action)&&access?.operations?.illustration?.enabled){await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));if(!mounted.current)return;if(controller.current.signal.aborted)throw new DOMException('Aborted','AbortError');setProgress('Création du dessin IA…');const visualBody={...body,requestId:crypto.randomUUID(),operation:'illustration',prompt:'Dessine fidèlement cette création et tous ses motifs, sans ajouter de thème.',shape:next.shape,length:next.length,level:next.rank,designCount:next.secondHand?10:5,composition:minimalComposition(next),referenceImage:await compositionImage(preview.current)};const drawing=await awaitAssistantJob(social.client,visualBody,controller.current.signal,()=>{if(mounted.current)setProgress('Création du dessin IA…');});if(!mounted.current)return;if(drawing.status==='succeeded'&&drawing.result)apply({...drawing.result,jobId:drawing.jobId},next);else setError('Le dessin IA n’a pas abouti. Le schéma technique reste disponible ; tu peux relancer le dessin.');}}else {setError(response.error?message(Error(response.error)):'Demande en cours ou interrompue : consulte l’historique avant de relancer.');if(response.status==='failed')setPrompt(text);}
    const h=await assistantCall(social.client,{action:'history'});if(mounted.current)setThreads(h.threads);
   }
  }catch(e){if(mounted.current){setError(e.name==='AbortError'?'L’attente est interrompue. Le serveur peut encore terminer ; retrouve la demande dans l’historique.':e.message==='offline'?'Tu es hors ligne. La composition locale reste disponible.':e.message==='consent_required'?'Confirme les données à transmettre avant de lancer.':message(e));setPrompt(text);}}
  finally{if(mounted.current)setBusy(false);}
 }
 async function load(id){setBusy(true);setError('');try{const h=await assistantCall(social.client,{action:'history',threadId:id});setThread(id);setConsent(false);setRenderChoice(null);setMessages([]);setImage(null);setRenderedImage(null);setDrawingImage(null);drawingJob.current=null;setVisualKind(null);setQuality({});setTrends(null);let current=initialIdea||null;for(const m of h.messages){if(m.role==='user')setMessages(v=>[...v,{role:'user',text:m.content.text}]);else{if(m.content.kind==='plan'){try{const next=ideaFromPlan(m.content.plan,{products:m.content.products,items,profile,current,collectionOnly:false,master:m.content.master});if(next){current=next;setIdea(next);setImage(null);setRenderedImage(null);setDrawingImage(null);drawingJob.current=null;setVisualKind(null);setQuality({});setTrends(null);setMode('conversation');}}catch{setError('Une ancienne composition nécessite d’être rouverte depuis Mes poses.');}setMessages(v=>[...v,{role:'assistant',text:m.content.plan.message,action:m.content.plan.action}]);}else{if(m.content.kind==='trends'){setTrends(m.content);setIdea(null);setMode('trends');}setMessages(v=>[...v,{role:'assistant',text:m.content.message,sources:m.content.sources}]);if(m.content.imageUrl){current=withResultMedia(current,m.content);if(current)setIdea(current);setQuality(q=>({...q,[m.content.kind]:m.content.quality||null}));setImage(m.content.imageUrl);const kind=m.content.kind==='illustration'?'illustration':'realistic';setVisualKind(kind);if(kind==='illustration'){setDrawingImage(m.content.imageUrl);drawingJob.current=m.content.imagePath?.split('/').at(-1)?.replace(/\.png$/,'')||null;}else setRenderedImage(m.content.imageUrl);}}}}}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{await assistantCall(social.client,{action:'delete',threadId:thread});setThreads(ts=>ts.filter(t=>t.id!==thread));setMessages([]);setIdea(null);setImage(null);setRenderedImage(null);setDrawingImage(null);drawingJob.current=null;setVisualKind(null);setConsent(false);setRenderChoice(null);setThread(crypto.randomUUID());setDeleteAsk(false);}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function photo(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>5000000)throw Error();const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,768/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const value=canvas.toDataURL('image/png');if(value.length>1400000)throw Error();setAttachment(value);}catch{setError('Choisis une image de moins de 5 Mo, ou recadre-la avant de réessayer.');}}
 function chooseMode(value){setMode(value);setError('');setNotice('');}
 function preparePreview(value){if(!idea||busy)return;const cached=value==='illustration'?drawingImage:renderedImage;if(cached){setImage(cached);setVisualKind(value);return;}if(!consent){setRenderChoice(value);return;}run(null,value,(value==='illustration'?'Dessine fidèlement cette pose,':'Crée un rendu réaliste de cette pose,')+' en conservant sa forme, sa longueur et les designs de chacun des '+(idea.secondHand?'dix':'cinq')+' doigts.');}

 const modeText={conversation:['Ton envie','Une French rose, un détail doré, des fleurs…','Générer le dessin'],local:['Ton envie','Décris les couleurs et les motifs que tu aimes…','Composer ma pose'],trends:['Ce que tu veux explorer','Les tendances nail art de cet automne…','Trouver mon inspiration'],vision:['Ce qui te plaît dans cette photo','Ses couleurs, ses motifs, son ambiance…','M’inspirer de ma photo'],illustration:['Ton dessin','Les détails à conserver dans ton dessin…','Créer le dessin'],realistic:['Ton rendu','Les détails à conserver dans ton rendu…','Créer le rendu réaliste']}[mode];
 const suggestions=mode==='trends'?['Des idées pour cet automne','Les French du moment','Des tendances faciles à réaliser']:mode==='vision'?['Reprendre les couleurs','Adapter les motifs à mes vernis','Créer une variante plus simple']:['Une French léopard dorée','Des fleurs avec mes vernis','Une pose facile à réaliser'];
 const hasVisual=mode==='trends'?!!trends?.cards?.length:!!idea||!!image;
 function selectTrend(card){const next=ideaFromPlan(card.plan,{products:trends.products,items,profile,collectionOnly:only});if(next){setShape(next.shape);setLength(next.length);setLevel(next.rank);setDesignCount(next.secondHand?10:5);setIdea(next);setImage(null);setRenderedImage(null);setDrawingImage(null);drawingJob.current=null;setVisualKind(null);setQuality({});setTrends(null);chooseMode('conversation');setPrompt('');}}
 const creditCost=Number(access?.operations?.[mode]?.credits||0)+(['conversation','vision'].includes(mode)?Number(access?.operations?.illustration?.enabled?access?.operations?.illustration?.credits||0:0):0);
 const canSubmit=!busy&&prompt.trim()&&(mode==='local'||(access?.allowed&&consent))&&(mode!=='vision'||attachment)&&(!['illustration','realistic'].includes(mode)||idea);
 return <Sheet title="NailMoods AI" eyebrow="UNE ENVIE, TA PROCHAINE POSE" className="nmAISheet" scrollBody onClose={onClose}>
 <div className="nmAIQuickTools"><button className="nmAIQuiet" aria-expanded={settings} onClick={()=>setSettings(v=>!v)}>Options et essai privé</button>{hasVisual&&<button className="nmAIQuiet" disabled={busy} onClick={()=>{setIdea(null);setImage(null);setTrends(null);setRenderedImage(null);setDrawingImage(null);drawingJob.current=null;setVisualKind(null);setPrompt('');setConsent(false);setRenderChoice(null);setThread(crypto.randomUUID());setMessages([]);chooseMode(access?.allowed?'conversation':'local');}}>Nouvelle recherche</button>}</div>
 <div className={'nmAIWorkspace'+(hasVisual?' nmAIHasVisual':'')}><div className="nmAIConversation">
  {!hasVisual&&<div className="nmAIIntro"><AtelierArt source="ai"/><div><p>Imagine ta prochaine pose.</p></div></div>}
  {!hasVisual&&<details className="nmAIOtherIntents"><summary>Photo et tendances</summary><div className="nmAIIntentTabs" role="group" aria-label="Que souhaites-tu créer ?">
   {[['conversation','Créer une pose',Sparkles],['trends','Les tendances',TrendingUp],['vision','Avec une photo',ImagePlus]].map(([value,label,Icon])=><button type="button" key={value} aria-pressed={value==='conversation'?['conversation','local','illustration','realistic'].includes(mode):mode===value} disabled={busy||(!access?.allowed&&value!=='conversation')||value!=='conversation'&&!access?.operations?.[value]?.enabled} onClick={()=>chooseMode(value==='conversation'&&!access?.allowed?'local':value)}><Icon size={18}/><span>{label}</span></button>)}
  </div></details>}
  {mode==='local'&&<p className="nmAINotice nmAILocalNote">Tu composes avec les outils NailMoods, sans envoi à l’IA. Enregistre ta pose pour la conserver.</p>}
  {['illustration','realistic'].includes(mode)&&<div className="nmAISelectedOutput"><Brush size={18}/><span>{mode==='illustration'?'Un dessin de ta composition':'Un aperçu réaliste de ta composition'}</span><button type="button" disabled={busy} onClick={()=>chooseMode('conversation')}>Revenir à ma pose</button></div>}
  {mode==='vision'&&<div className="nmAIPhotoBox">{attachment?<><img className="nmAIReference" src={attachment} alt="Ta photo d’inspiration"/><span>Ta photo est prête</span></>:<><AtelierArt source="photos"/><p>Choisis une photo qui t’inspire.</p></>}<label className="nmAIPhotoPick"><ImagePlus size={18}/>{attachment?'Changer de photo':'Ajouter ma photo'}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={photo} disabled={busy}/></label><small>JPG, PNG ou WebP · 5 Mo maximum</small></div>}
  {!(initialRender&&idea)&&<details className="nmAIRefine" open={!hasVisual}><summary hidden={!hasVisual}>{mode==='trends'?'Affiner ma recherche':['illustration','realistic'].includes(mode)?'Créer ce visuel':'Affiner ma pose'}</summary><form className="nmAIComposer" onSubmit={run}>
   {['conversation','local','vision'].includes(mode)&&<><div className="nmAIShapeRow"><label>Forme<select aria-label="Forme des ongles" value={shape} disabled={busy} onChange={e=>setShape(e.target.value)}>{SHAPES.map(s=><option key={s}>{s}</option>)}</select></label><label>Longueur<select aria-label="Longueur des ongles" value={length} disabled={busy} onChange={e=>setLength(e.target.value)}>{LENGTHS.map(s=><option key={s}>{s}</option>)}</select></label></div><fieldset className="nmAIChoices"><legend>Ta composition</legend>{[[5,'5 designs · les deux mains'],[10,'10 doigts différents']].map(([n,label])=><button type="button" key={n} aria-pressed={designCount===n} disabled={busy||mode==='local'&&n===10} onClick={()=>setDesignCount(n)}>{label}</button>)}</fieldset></>}
   <label className="nmAIPromptLabel" htmlFor="nm-ai-prompt">{modeText[0]}</label><textarea id="nm-ai-prompt" value={prompt} maxLength={3000} rows={3} onChange={e=>setPrompt(e.target.value)} placeholder={modeText[1]} disabled={busy}/>
   {['conversation','local','vision'].includes(mode)&&<fieldset className="nmAIChoices nmAILevels"><legend>Niveau nail art</legend>{['Facile','Moyen','Difficile'].map((label,n)=><button type="button" key={label} aria-pressed={level===n} disabled={busy} onClick={()=>setLevel(n)}>{label}</button>)}</fieldset>}
   <label className="nmAICheck"><input type="checkbox" checked={only} disabled={busy} onChange={e=>setOnly(e.target.checked)}/><span>Utiliser uniquement mes vernis</span></label>
   {mode!=='local'&&<div className="nmAIConsent"><label className="nmAICheck"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/><span>J’autorise l’IA pour cette création et ses rendus.</span></label><details><summary>Quelles données sont envoyées ?</summary><p>Ton texte, les références utiles de tes vernis, les derniers échanges et, si tu en utilises une, ta photo sont transmis à OpenAI. Pour voir le rendu IA, le dessin de cette création est aussi transmis. Cette autorisation vaut uniquement pour cette création et ses rendus, jusqu’à la fermeture de cet écran ou au début d’une nouvelle création. Tes échanges restent privés dans NailMoods et tu peux les supprimer. Aucun achat automatique.</p></details></div>}
   <button className="nmAIPrimary" disabled={!canSubmit}>{busy?(progress||'Préparation…'):modeText[2]}<ArrowUp size={18}/></button>
   {busy&&<button className="nmAIQuiet" type="button" onClick={()=>controller.current?.abort()}><Square size={14}/>Arrêter l’attente</button>}
   {access?.admin&&mode!=='local'&&<p className="nmAITrial"><ShieldCheck size={14}/>Ton essai privé est {access.enabled?'actif':'en pause'}{creditCost>0?' · '+creditCost+' jeton'+(creditCost>1?'s':'')+' pour cette demande':''}.</p>}
  </form></details>}
  {error&&<p role="alert" className="formError nmAIAlert">{error}</p>}{notice&&<p role="status" className="nmAIStatus"><Check size={16}/>{notice}</p>}
  {!!messages.length&&<details className="nmAIExchange"><summary>Lire les échanges et les sources</summary><div className="nmAIMessages" role="log" aria-live="polite">{messages.map((m,i)=><article key={i} className={'nmAIMessage '+m.role}><small>{m.role==='user'?'Toi':'NailMoods'}</small><p>{String(m.text||'').replace(/\[([^\]]+)\]\(https?:\/\/[^)]+\)/g,'$1').replace(/\*\*/g,'')}</p>{m.sources?.map(source=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer">{source.title} · consulté le {new Date(source.accessedAt).toLocaleDateString('fr-FR')}{source.publishedAt?' · publié le '+source.publishedAt:''}</a>)}{m.action==='share'&&idea&&onShare&&<button className="nmAISecondary" onClick={()=>onShare(idea)}>Choisir ma PO et confirmer</button>}</article>)}</div></details>}
 </div>
 {hasVisual&&<aside className="nmAIPreview" ref={resultPanel}><span className="nmAIEyebrow">TON ATELIER</span><h3>{mode==='trends'?'Tes inspirations':'Ta pose'}</h3>
 {mode==='trends'?<><p className="nmAINotice">{trends.message}</p><div className="nmAITrendGrid">{trends.cards.map((card,i)=>{let pose;try{pose=ideaFromPlan(card.plan,{products:trends.products,items,profile});}catch{return null;}return <article className="nmAITrendCard" key={i}><NailPreview idea={pose}/><h4>{card.plan.title}</h4><p>{card.summary}</p><small>Suggestion illustrée · inspirée des sources</small><button className="nmAISecondary" disabled={busy} onClick={()=>selectTrend(card)}>Choisir cette pose<ChevronRight size={15}/></button><a href={card.source.url} target="_blank" rel="noopener noreferrer">Source : {card.source.title}</a></article>;})}</div></>:idea?<>{image&&<figure className="nmAIHeroImage"><img src={image} alt="Visuel de ta pose généré par l’IA"/><figcaption>{visualKind==='illustration'?'Dessin généré par l’IA':'Rendu réaliste généré par l’IA'}</figcaption></figure>}<div ref={preview} className={image?'nmAIReferencePreview':''}><NailPreview idea={idea}/></div>{!image&&<small className="nmAINotice">Schéma technique · motifs simplifiés</small>}<p className="nmAIPoseTitle">{idea.title}</p><p className="nmAINotice">{idea.shape} · {idea.length} · {['Facile','Moyen','Difficile'][idea.rank]} · {idea.secondHand?'10 doigts différents':'5 designs répétés'}</p><div className="nmAIActions"><button className="nmAIPrimary" onClick={()=>onOpen(idea)}><Palette size={17}/>Personnaliser ma pose</button><button className="nmAISecondary" onClick={()=>{if(onSave(idea)!==false)setNotice('Ta pose est enregistrée dans tes projets.');}}><Check size={17}/>Enregistrer</button><button className="nmAISecondary" aria-expanded={tutorial} onClick={()=>setTutorial(v=>!v)}>Voir les étapes<ChevronRight size={17}/></button></div>
 <div className="nmAIOutputActions" role="group" aria-label="Vues de la pose"><button disabled={busy||!image} aria-pressed={!image} onClick={()=>{setImage(null);setVisualKind(null);}}><Brush size={18}/><b>Voir le schéma</b></button><button disabled={busy||!access?.allowed||visualKind==='illustration'} aria-pressed={visualKind==='illustration'} onClick={()=>preparePreview('illustration')}><Brush size={18}/><b>{drawingImage?'Voir le dessin':'Générer le dessin IA'}</b></button><button disabled={busy||!access?.allowed||!access?.operations?.realistic?.enabled||!drawingImage&&!renderedImage&&!initialIdea||visualKind==='realistic'} aria-pressed={visualKind==='realistic'} onClick={()=>preparePreview('realistic')}><Camera size={18}/><b>Voir le rendu réaliste</b></button></div>
 {busy&&<p role="status" className="nmAINotice">{progress||'Création en cours…'}</p>}
 {image&&quality[visualKind]&&<details className="nmAIQuality"><summary>{quality[visualKind].status==='nonconforming'?'Écarts détectés · visuel non validé':'Validation artistique à faire'}</summary><p>{quality[visualKind].summary}</p>{quality[visualKind].fingers?.filter(f=>f.missing?.length||f.moved?.length||f.uncertain).map(f=><p key={f.id}>{f.id} : {[...(f.missing||[]),...(f.moved||[]),...(f.uncertain?['À vérifier visuellement']:[])].join(', ')}</p>)}<small>Contrôle automatique préliminaire. La validation finale est humaine.</small></details>}

 {renderChoice&&<div className="nmAIRenderConsent"><label className="nmAICheck"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>J’autorise l’IA pour cette création et ses rendus.</span></label><small>Le dessin de cette pose sera transmis à OpenAI. Sa forme, sa longueur, ses couleurs et ses motifs sont conservés.</small><button className="nmAIPrimary" disabled={busy||!consent||!access?.allowed||!access?.operations?.[renderChoice]?.enabled} onClick={()=>preparePreview(renderChoice)}>{renderChoice==='realistic'?'Créer le rendu IA':'Créer le dessin IA'}</button></div>}


 {tutorial&&<div className="nmAITutorial"><h4>Ta pose, étape par étape</h4><p className="nmAINotice">Guide NailMoods : complète-le avec les notices de tes produits.</p><ol>{tutorialFor(idea).map(step=><li key={step.id}><b>{step.title}</b><p>{step.body}</p></li>)}</ol><button className="nmAISecondary" onClick={()=>onTutorial(idea)}>Ouvrir ma pose guidée<ChevronRight size={17}/></button></div>}</>:image?<figure className="nmAIHeroImage"><img src={image} alt="Manucure générée par l’IA"/><figcaption>Image générée par l’IA</figcaption></figure>:<><AtelierArt source="manual"/><p>Décris ton envie : ta composition sur cinq ongles apparaîtra ici.</p><span className="nmAINotice">Tu pourras l’ajuster, l’enregistrer et suivre ses étapes.</span></>}
 </aside>}</div>
 {settings&&<div className="nmAIFooter">
 <details className="nmAIDisclosure"><summary>Mes conversations<small>{threads.length?threads.length+' enregistrée'+(threads.length>1?'s':''):'Privées et supprimables'}</small></summary><div className="nmAIDisclosureBody"><button className="nmAISecondary" disabled={busy} onClick={()=>{setThread(crypto.randomUUID());setConsent(false);setRenderChoice(null);setMessages([]);setImage(null);setRenderedImage(null);setDrawingImage(null);drawingJob.current=null;setVisualKind(null);setQuality({});setTrends(null);setIdea(null);setTutorial(false);setError('');setNotice('');chooseMode(access?.allowed?'conversation':'local');}}>Nouvelle conversation</button>{threads.map(t=><button className="nmAIHistoryRow" key={t.id} disabled={busy} onClick={()=>load(t.id)}>{t.title}<ChevronRight size={15}/></button>)}{!threads.length&&<p className="nmAINotice">Tes conversations IA apparaîtront ici après ta première demande.</p>}{threads.some(t=>t.id===thread)&&<button className="nmAIQuiet" onClick={()=>setDeleteAsk(true)}><Trash2 size={14}/>Supprimer cette conversation</button>}{deleteAsk&&<div className="nmAIConfirmation"><p>Supprimer les échanges et aperçus de cette conversation ? Tes poses enregistrées sont conservées.</p><button className="nmAISecondary" disabled={busy} onClick={remove}>Confirmer la suppression</button><button className="nmAIQuiet" onClick={()=>setDeleteAsk(false)}>Conserver</button></div>}</div></details>
 <details className="nmAIDisclosure"><summary>Mes préférences<small>Créer avec ou sans IA</small></summary><div className="nmAIDisclosureBody"><button className="nmAISecondary" disabled={busy} aria-pressed={mode==='local'} onClick={()=>chooseMode(mode==='local'&&access?.allowed?'conversation':'local')}>{mode==='local'&&access?.allowed?'Retrouver l’assistante IA':'Composer sans IA'}</button><p className="nmAINotice">Sans IA, NailMoods utilise ses règles de création. Les échanges restent sur cet écran ; enregistre ta pose pour la conserver.</p></div></details>
 {access?.admin&&<details className="nmAIDisclosure nmAIAdmin"><summary>Mon essai privé<small>Arrêt et consommation</small></summary><div className="nmAIDisclosureBody"><p>Ton plafond d’essai : <b>{access.dailyBudget} $ par jour</b> et <b>{access.monthlyBudget} $ par mois</b>.</p><button className="nmAISecondary nmAIPower" disabled={switching} onClick={async()=>{setSwitching(true);try{const next=await assistantCall(social.client,{action:'switch',enabled:!access.enabled});setAccess(next);if(!busy)chooseMode(next.enabled?'conversation':'local');setNotice(next.enabled?'Ton essai IA est réactivé.':'Ton essai IA est en pause. Les demandes déjà envoyées peuvent se terminer.');}catch{setError('Le changement n’a pas été confirmé.');}finally{setSwitching(false);}}}><Power size={17}/>{access.enabled?'Mettre l’IA en pause':'Réactiver mon essai IA'}</button><p className="nmAINotice">La pause empêche les nouvelles demandes. Celles déjà envoyées peuvent se terminer.</p><div className="nmAIAdminTools"><button className="nmAIQuiet" onClick={async()=>{try{const d=await assistantCall(social.client,{action:'diagnostics'});setNotice(d.authenticated?'La connexion IA fonctionne. Ce contrôle n’a lancé aucune création.':'La connexion IA doit être vérifiée.');}catch{setError('La vérification n’est pas disponible.');}}}>Vérifier la connexion</button><button className="nmAIQuiet" onClick={async()=>{try{const [bilan,health]=await Promise.all([assistantCall(social.client,{action:'metrics'}),assistantCall(social.client,{action:'health'})]);setMetrics({...bilan,health});}catch{setError('La consommation n’a pas pu être chargée.');}}}>Voir ma consommation</button></div>{metrics&&<div className="nmAIBudget"><p>{metrics.health?.queued??0} demandes en attente · {metrics.health?.running??0} en cours</p><table><thead><tr><th>Création</th><th>Demandes</th><th>Coût estimé</th></tr></thead><tbody>{metrics.byOperation.map((r,i)=><tr key={i}><td>{{conversation:'Pose',trends:'Tendances',vision:'Photo',illustration:'Dessin',realistic:'Rendu'}[r.operation]||r.operation}</td><td>{r.requests}</td><td>{r.estimated_usd==null?'À vérifier':Number(r.estimated_usd).toFixed(3)+' $'}</td></tr>)}</tbody></table><p className="nmAINotice">Estimation de l’usage IA, à rapprocher de la facture.</p></div>}</div></details>}
 </div>}</Sheet>;
}
