import React,{useEffect,useRef,useState} from 'react';
import {ArrowUp,Search,Square,Trash2} from 'lucide-react';
import Sheet from '../Sheet';
import NailPreview from '../NailPreview';
import AtelierArt from '../design/AtelierArt';
import {useSocial} from '../social/SocialContext';
import {useStorage} from '../StorageContext';
import {compositionImage} from '../aiPlus/compositionImage';
import {CONCEPT_COLORS} from '../../supabase/functions/nailmoods-ai/contract.mjs';
import {assistantEnabled,localPlan,ideaFromPlan,productContext,tutorialFor,minimalComposition,AI_MESSAGES} from './model';
import {assistantCall,awaitAssistantJob} from './service';
import './assistant.css';
export function AssistantEntry({onOpen,context='home'}){const social=useSocial();const [visible,setVisible]=useState(false);useEffect(()=>{let active=true;setVisible(false);if(assistantEnabled(import.meta.env)&&social?.client)assistantCall(social.client,{action:'access'}).then(a=>{if(active)setVisible(a.uiAccess===true);}).catch(()=>{});return()=>{active=false;};},[social?.client,social?.userId]);if(!assistantEnabled(import.meta.env)||!visible)return null;return <button className="nmAIEntry" onClick={onOpen}><Search size={19}/><span><b>{context==='collection'?'Une idée avec mes vernis':context==='journal'?'Une variante de ma pose':'Quelle est ton envie nail art ?'}</b><small>NailMoods AI · essai privé</small></span><ArrowUp size={18}/></button>;}
export default function Assistant({items,profile,initialIdea,onClose,onSave,onOpen,onTutorial,onShare}){
 const social=useSocial(),storage=useStorage(),[prompt,setPrompt]=useState(''),[mode,setMode]=useState('local'),[only,setOnly]=useState(false),[consent,setConsent]=useState(false),[messages,setMessages]=useState([]),[idea,setIdea]=useState(initialIdea||null),[image,setImage]=useState(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[access,setAccess]=useState(null),[threads,setThreads]=useState([]),[thread,setThread]=useState(()=>crypto.randomUUID()),[tutorial,setTutorial]=useState(false),[attachment,setAttachment]=useState(null),[deleteAsk,setDeleteAsk]=useState(false),[metrics,setMetrics]=useState(null);
 const controller=useRef(null),preview=useRef(null),mounted=useRef(true),request=useRef(null);
 useEffect(()=>{mounted.current=true;if(social?.client){assistantCall(social.client,{action:'access'}).then(a=>{if(mounted.current){setAccess(a);if(a.allowed)setMode('conversation');}}).catch(()=>{});assistantCall(social.client,{action:'history'}).then(h=>{if(mounted.current)setThreads(h.threads);}).catch(()=>{});}return()=>{mounted.current=false;controller.current?.abort();};},[social?.client,social?.userId]);
 const message=e=>AI_MESSAGES[e.message]||'La demande n’a pas abouti. Tes produits et tes droits sont conservés.';
 function apply(result,current=idea){if(result.kind==='plan'){
   const next=ideaFromPlan(result.plan,{products:result.products,items,profile,current,collectionOnly:only});if(next)setIdea(next);
   setMessages(m=>[...m,{role:'assistant',text:result.plan.message,action:result.plan.action}]);if(result.plan.action==='tutorial')setTutorial(true);
  }else{setMessages(m=>[...m,{role:'assistant',text:result.message,sources:result.sources}]);if(result.imageUrl)setImage(result.imageUrl);}}
 async function run(e){e.preventDefault();if(busy||!prompt.trim())return;setError('');setProgress('');setBusy(true);const text=prompt.trim();setMessages(m=>[...m,{role:'user',text}]);setPrompt('');
  try{if(mode==='local'){const p=localPlan(text,{items,profile,collectionOnly:only,current:idea});apply({kind:'plan',plan:p,products:[...productContext(items),...(only?[]:CONCEPT_COLORS)]});}
   else{
    if(!consent)throw Error('consent_required');
    if(navigator.onLine===false)throw Error('offline');
    const referenceImage=['realistic','illustration'].includes(mode)?await compositionImage(preview.current):mode==='vision'?attachment:undefined;
    controller.current=new AbortController();const body={requestId:crypto.randomUUID(),threadId:thread,workspaceId:storage.workspaceId,operation:mode,prompt:text,collectionOnly:only,shape:profile.shape||'Amande',length:profile.length||'Courte',mood:profile.visualMood||'soft-glam',consent:true,...(referenceImage?{referenceImage}:{}),...(idea?{composition:minimalComposition(idea)}:{})};request.current=body;
    const response=await awaitAssistantJob(social.client,body,controller.current.signal,s=>{if(mounted.current)setProgress(s==='queued'?'En attente…':'Création en cours…');});if(!mounted.current)return;
    if(response.status==='succeeded'&&response.result)apply(response.result);else setError(response.error?message(Error(response.error)):'Demande en cours ou interrompue : consulte l’historique avant de relancer.');
    const h=await assistantCall(social.client,{action:'history'});if(mounted.current)setThreads(h.threads);
   }
  }catch(e){if(mounted.current){setError(e.name==='AbortError'?'L’attente est interrompue. Le serveur peut encore terminer ; retrouve la demande dans l’historique.':e.message==='offline'?'Tu es hors ligne. La composition locale reste disponible.':e.message==='consent_required'?'Confirme les données à transmettre avant de lancer.':message(e));setPrompt(text);}}
  finally{if(mounted.current)setBusy(false);}
 }
 async function load(id){setBusy(true);setError('');try{const h=await assistantCall(social.client,{action:'history',threadId:id});setThread(id);setMessages([]);setImage(null);let current=initialIdea||null;for(const m of h.messages){if(m.role==='user')setMessages(v=>[...v,{role:'user',text:m.content.text}]);else{if(m.content.kind==='plan'){try{const next=ideaFromPlan(m.content.plan,{products:m.content.products,items,profile,current,collectionOnly:false});if(next){current=next;setIdea(next);}}catch{setError('Une ancienne composition nécessite d’être rouverte depuis Mes poses.');}setMessages(v=>[...v,{role:'assistant',text:m.content.plan.message,action:m.content.plan.action}]);}else{setMessages(v=>[...v,{role:'assistant',text:m.content.message,sources:m.content.sources}]);if(m.content.imageUrl)setImage(m.content.imageUrl);}}}}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{await assistantCall(social.client,{action:'delete',threadId:thread});setThreads(ts=>ts.filter(t=>t.id!==thread));setMessages([]);setImage(null);setThread(crypto.randomUUID());setDeleteAsk(false);}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function photo(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>5000000)throw Error();const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,768/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const value=canvas.toDataURL('image/png');if(value.length>1400000)throw Error();setAttachment(value);}catch{setError('Choisis une image de moins de 5 Mo, ou recadre-la avant de réessayer.');}}
 return <Sheet title="NailMoods AI" eyebrow="DE L’ENVIE À LA CRÉATION" className="nmAISheet" onClose={onClose}><div className="nmAIWorkspace"><div className="nmAIConversation">
 <div className="nmAIIntro"><AtelierArt source="inspire"/><p>Imagine une pose, explore tes couleurs ou fais évoluer un seul ongle.</p></div>
 <label>Mode<select value={mode} disabled={busy} onChange={e=>setMode(e.target.value)}><option value="local">Composition locale · sans appel IA</option>{[['conversation','Assistante IA'],['trends','Tendances sourcées'],['vision','Analyser une image'],['illustration','Illustration distante'],['realistic','Rendu réaliste']].map(([v,l])=><option key={v} value={v} disabled={!access?.allowed||!access?.operations?.[v]?.enabled}>{l}{!access?.allowed?' · non activé':''}</option>)}</select></label>
 <p className="nmAINotice">Version de test : la composition locale utilise les règles NailMoods, sans intelligence artificielle distante. Enregistre ton projet pour le conserver ; les échanges locaux ne sont pas conservés à la fermeture.</p>
 <label className="nmAICheck"><input type="checkbox" checked={only} onChange={e=>setOnly(e.target.checked)}/>Uniquement mes vernis</label>
 {mode!=='local'&&<><p className="nmAINotice">Cette demande transmet le texte, les références utiles, les derniers échanges et l’image choisie à OpenAI. L’historique est privé et supprimable. Aucun achat automatique.</p><label className="nmAICheck"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>J’accepte cet envoi pour ma demande.</label><p>Solde : {Object.values(access?.balance||{}).reduce((a,b)=>a+Number(b),0)} jeton(s). {access?.operations?.[mode]?.credits??0} jeton(s) réservés · restitués si la création échoue.</p></>}
 {mode==='vision'&&<label>Image à analyser<input type="file" accept="image/png,image/jpeg,image/webp" onChange={photo}/>{attachment&&<img className="nmAIReference" src={attachment} alt="Image sélectionnée, prête à être analysée"/>}</label>}
 <div className="nmAIMessages" role="log" aria-live="polite">{messages.map((m,i)=><article key={i} className={'nmAIMessage '+m.role}><small>{m.role==='user'?'Toi':'NailMoods'}</small><p>{m.text}</p>{m.sources?.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.title} · consulté le {new Date(s.accessedAt).toLocaleDateString('fr-FR')}{s.publishedAt?' · publié le '+s.publishedAt:''}</a>)}{m.action==='share'&&idea&&onShare&&<button onClick={()=>onShare(idea)}>Choisir ma PO et confirmer</button>}</article>)}</div>
 {!messages.length&&<div className="nmAISuggestions">{['Une French léopard avec des détails dorés','Des fleurs avec mes vernis','Une pose simple pour débutante'].map(t=><button key={t} onClick={()=>setPrompt(t)}>{t}</button>)}</div>}
 <form className="nmAIComposer" onSubmit={run}><label htmlFor="nm-ai-prompt">Ton envie<textarea id="nm-ai-prompt" value={prompt} maxLength={3000} rows={3} onChange={e=>setPrompt(e.target.value)} placeholder="Décris ta pose… La dictée de ton clavier fonctionne aussi."/></label><button className="detailPrimary" disabled={busy||!prompt.trim()||mode!=='local'&&!consent}>{busy?(progress||'Préparation…'):'Explorer mon idée'}<ArrowUp size={18}/></button>{busy&&<button type="button" onClick={()=>controller.current?.abort()}><Square size={14}/>Arrêter l’attente</button>}</form>
 {error&&<p role="alert" className="formError">{error}</p>}
 <details className="nmDisclosure"><summary>Mes conversations privées</summary><button disabled={busy} onClick={()=>{setThread(crypto.randomUUID());setMessages([]);setImage(null);setIdea(null);setTutorial(false);setError('');}}>Nouvelle conversation</button>{threads.map(t=><button key={t.id} disabled={busy} onClick={()=>load(t.id)}>{t.title}</button>)}{threads.some(t=>t.id===thread)&&<button onClick={()=>setDeleteAsk(true)}><Trash2 size={14}/>Supprimer cette conversation</button>}{deleteAsk&&<div><p>Supprimer ses échanges et rendus privés ? Les projets déjà enregistrés sont conservés.</p><button disabled={busy} onClick={remove}>Confirmer la suppression</button><button onClick={()=>setDeleteAsk(false)}>Conserver</button></div>}</details>
 {access?.admin&&<details className="nmDisclosure"><summary>Pilotage · accès administratrice</summary><p>Budget serveur : {access.dailyBudget} $ / jour et {access.monthlyBudget} $ / mois. Les requêtes déjà envoyées peuvent se terminer après l’arrêt.</p><button disabled={busy} onClick={async()=>{try{setAccess(await assistantCall(social.client,{action:'switch',enabled:!access.enabled}));}catch{setError('Le changement n’a pas été confirmé.');}}}>{access.enabled?'Désactiver immédiatement l’IA':'Réactiver mon essai privé'}</button><button onClick={async()=>{try{const d=await assistantCall(social.client,{action:'diagnostics'});setError(d.authenticated?'Clé serveur présente et acceptée par OpenAI. Aucun appel de génération effectué.':d.keyPresent?'La clé existe mais son accès OpenAI reste à vérifier.':'La clé OpenAI manque côté serveur.');}catch{setError('Diagnostic indisponible.');}}}>Vérifier la connexion OpenAI</button><button onClick={async()=>{try{const [bilan,health]=await Promise.all([assistantCall(social.client,{action:'metrics'}),assistantCall(social.client,{action:'health'})]);setMetrics({...bilan,health});}catch{setError('Ce tableau est réservé à l’administratrice.');}}}>Actualiser le bilan</button>{metrics&&<div><p>{metrics.activeUsers} utilisatrices actives sur 30 jours · service {metrics.enabled?'activé':'arrêté'}</p><p>{metrics.health?.queued??0} demandes en attente · {metrics.health?.running??0} en traitement · {metrics.health?.last24h?.failed??0} échecs sur 24 h</p><p>Coûts estimés à partir de l’usage. Facture et revenus publicitaires non rapprochés.</p><table><thead><tr><th>Opération</th><th>Demandes</th><th>Estimation USD</th></tr></thead><tbody>{metrics.byOperation.map((r,i)=><tr key={i}><td>{r.operation} · {r.tier} · {r.status}</td><td>{r.requests}</td><td>{r.estimated_usd??'inconnue'}</td></tr>)}</tbody></table></div>}</details>}
 </div><aside className="nmAIPreview"><h3>Ma composition</h3>{idea?<><div ref={preview}><NailPreview idea={idea}/></div><p>{idea.title}</p><p className="nmAINotice">Couleurs d’aperçu ; vérifie les références et le matériel avant réalisation.</p><div className="nmAIActions"><button onClick={()=>onOpen(idea)}>Personnaliser</button><button onClick={()=>{if(onSave(idea)!==false)setMessages(m=>[...m,{role:'assistant',text:'Composition enregistrée dans tes projets.'}]);}}>Enregistrer le projet</button><button onClick={()=>setTutorial(v=>!v)}>Tutoriel inclus</button></div>{image&&<figure><img src={image} alt="Aperçu synthétique IA de la composition"/><figcaption>Rendu IA à valider · la correspondance des motifs et couleurs n’est pas garantie.</figcaption></figure>}{tutorial&&<div><p>Guide de la bibliothèque NailMoods. Pour les effets avancés, compléter avec les notices des produits.</p><ol>{tutorialFor(idea).map(s=><li key={s.id}><b>{s.title}</b><p>{s.body}</p></li>)}</ol><button onClick={()=>onTutorial(idea)}>Ouvrir ma pose guidée</button></div>}</>:<p>Ton aperçu sur cinq ongles apparaîtra ici.</p>}</aside></div></Sheet>;
}
