import React,{useEffect,useRef,useState} from 'react';
import {ArrowUp,Search,Square,Trash2,Sparkles,TrendingUp,ImagePlus,Palette,Brush,Camera,Check,ChevronRight,ShieldCheck,Power} from 'lucide-react';
import Sheet from '../Sheet';
import NailPreview from '../NailPreview';
import AtelierArt from '../design/AtelierArt';
import {useSocial} from '../social/SocialContext';
import {useStorage} from '../StorageContext';
import {compositionImage} from '../aiPlus/compositionImage';
import {CONCEPT_COLORS} from '../../supabase/functions/nailmoods-ai/contract.mjs';
import {assistantEnabled,localPlan,ideaFromPlan,productContext,tutorialFor,minimalComposition,AI_MESSAGES} from './model';
import {assistantCall,awaitAssistantJob} from './service';
import './assistant.css';
export function AssistantEntry({onOpen,context='home'}){const social=useSocial();const [visible,setVisible]=useState(false);useEffect(()=>{let active=true;setVisible(false);if(assistantEnabled(import.meta.env)&&social?.client)assistantCall(social.client,{action:'access'}).then(a=>{if(active)setVisible(a.uiAccess===true);}).catch(()=>{});return()=>{active=false;};},[social?.client,social?.userId]);if(!assistantEnabled(import.meta.env)||!visible)return null;return <button className="nmAIEntry" onClick={onOpen}><Search size={19}/><span><b>{context==='collection'?'Une idée avec mes vernis':context==='journal'?'Une variante de ma pose':'Quelle est ton envie nail art ?'}</b><small>NailMoods AI · essai privé</small></span><ArrowUp size={18}/></button>;}
export default function Assistant({items,profile,initialIdea,onClose,onSave,onOpen,onTutorial,onShare}){
 const social=useSocial(),storage=useStorage(),[prompt,setPrompt]=useState(''),[mode,setMode]=useState('conversation'),[only,setOnly]=useState(false),[consent,setConsent]=useState(false),[messages,setMessages]=useState([]),[idea,setIdea]=useState(initialIdea||null),[image,setImage]=useState(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[access,setAccess]=useState(null),[threads,setThreads]=useState([]),[thread,setThread]=useState(()=>crypto.randomUUID()),[tutorial,setTutorial]=useState(false),[attachment,setAttachment]=useState(null),[deleteAsk,setDeleteAsk]=useState(false),[metrics,setMetrics]=useState(null),[notice,setNotice]=useState(''),[switching,setSwitching]=useState(false);
 const controller=useRef(null),preview=useRef(null),mounted=useRef(true),request=useRef(null);
 useEffect(()=>{mounted.current=true;if(social?.client){assistantCall(social.client,{action:'access'}).then(a=>{if(mounted.current){setAccess(a);if(!a.allowed)setMode('local');}}).catch(()=>{});assistantCall(social.client,{action:'history'}).then(h=>{if(mounted.current)setThreads(h.threads);}).catch(()=>{});}return()=>{mounted.current=false;controller.current?.abort();};},[social?.client,social?.userId]);
 const message=e=>AI_MESSAGES[e.message]||'La demande n’a pas abouti. Tes produits et tes droits sont conservés.';
 function apply(result,current=idea){if(result.kind==='plan'){
   const next=ideaFromPlan(result.plan,{products:result.products,items,profile,current,collectionOnly:only});if(next)setIdea(next);
   setMessages(m=>[...m,{role:'assistant',text:result.plan.message,action:result.plan.action}]);if(result.plan.action==='tutorial')setTutorial(true);
  }else{setMessages(m=>[...m,{role:'assistant',text:result.message,sources:result.sources}]);if(result.imageUrl)setImage(result.imageUrl);}}
 async function run(e){e.preventDefault();if(busy||!prompt.trim())return;setError('');setProgress('');setBusy(true);const text=prompt.trim();setMessages(m=>[...m,{role:'user',text}]);setPrompt('');
  try{if(mode==='local'){const p=localPlan(text,{items,profile,collectionOnly:only,current:idea});apply({kind:'plan',plan:p,products:[...productContext(items),...(only?[]:CONCEPT_COLORS)]});}
   else{
    if(!consent)throw Error('consent_required');
    if(navigator.onLine===false)throw Error('offline');
    const referenceImage=['realistic','illustration'].includes(mode)?await compositionImage(preview.current):mode==='vision'?attachment:undefined;
    controller.current=new AbortController();const body={requestId:crypto.randomUUID(),threadId:thread,workspaceId:storage.workspaceId,operation:mode,prompt:text,collectionOnly:only,shape:profile.shape||'Amande',length:profile.length||'Courte',mood:profile.visualMood||'soft-glam',consent:true,...(referenceImage?{referenceImage}:{}),...(idea?{composition:minimalComposition(idea)}:{})};request.current=body;
    const response=await awaitAssistantJob(social.client,body,controller.current.signal,s=>{if(mounted.current)setProgress(s==='queued'?'En attente…':'Création en cours…');});if(!mounted.current)return;
    if(response.status==='succeeded'&&response.result)apply(response.result);else setError(response.error?message(Error(response.error)):'Demande en cours ou interrompue : consulte l’historique avant de relancer.');
    const h=await assistantCall(social.client,{action:'history'});if(mounted.current)setThreads(h.threads);
   }
  }catch(e){if(mounted.current){setError(e.name==='AbortError'?'L’attente est interrompue. Le serveur peut encore terminer ; retrouve la demande dans l’historique.':e.message==='offline'?'Tu es hors ligne. La composition locale reste disponible.':e.message==='consent_required'?'Confirme les données à transmettre avant de lancer.':message(e));setPrompt(text);}}
  finally{if(mounted.current)setBusy(false);}
 }
 async function load(id){setBusy(true);setError('');try{const h=await assistantCall(social.client,{action:'history',threadId:id});setThread(id);setMessages([]);setImage(null);let current=initialIdea||null;for(const m of h.messages){if(m.role==='user')setMessages(v=>[...v,{role:'user',text:m.content.text}]);else{if(m.content.kind==='plan'){try{const next=ideaFromPlan(m.content.plan,{products:m.content.products,items,profile,current,collectionOnly:false});if(next){current=next;setIdea(next);}}catch{setError('Une ancienne composition nécessite d’être rouverte depuis Mes poses.');}setMessages(v=>[...v,{role:'assistant',text:m.content.plan.message,action:m.content.plan.action}]);}else{setMessages(v=>[...v,{role:'assistant',text:m.content.message,sources:m.content.sources}]);if(m.content.imageUrl)setImage(m.content.imageUrl);}}}}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{await assistantCall(social.client,{action:'delete',threadId:thread});setThreads(ts=>ts.filter(t=>t.id!==thread));setMessages([]);setImage(null);setThread(crypto.randomUUID());setDeleteAsk(false);}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function photo(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>5000000)throw Error();const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,768/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const value=canvas.toDataURL('image/png');if(value.length>1400000)throw Error();setAttachment(value);}catch{setError('Choisis une image de moins de 5 Mo, ou recadre-la avant de réessayer.');}}
 function chooseMode(value){setMode(value);setConsent(false);setError('');setNotice('');}
 function preparePreview(value){chooseMode(value);setPrompt(value==='realistic'?'Crée un rendu réaliste de cette composition, en conservant ses cinq ongles, ses couleurs et ses motifs.':'Illustre cette composition en conservant ses cinq ongles, ses couleurs et ses motifs.');requestAnimationFrame(()=>document.getElementById('nm-ai-prompt')?.focus());}
 const modeText={conversation:['Ton envie','Une French rose, un détail doré, des fleurs…','Créer ma pose'],local:['Ton envie','Décris les couleurs et les motifs que tu aimes…','Composer ma pose'],trends:['Ce que tu veux explorer','Les tendances nail art de cet automne…','Trouver mon inspiration'],vision:['Ce qui te plaît dans cette photo','Ses couleurs, ses motifs, son ambiance…','M’inspirer de ma photo'],illustration:['Ton dessin','Les détails à conserver dans ton dessin…','Créer le dessin'],realistic:['Ton rendu','Les détails à conserver dans ton rendu…','Créer le rendu réaliste']}[mode];
 const suggestions=mode==='trends'?['Des idées pour cet automne','Les French du moment','Des tendances faciles à réaliser']:mode==='vision'?['Reprendre les couleurs','Adapter les motifs à mes vernis','Créer une variante plus simple']:['Une French léopard dorée','Des fleurs avec mes vernis','Une pose facile à réaliser'];
 const creditCost=Number(access?.operations?.[mode]?.credits||0);
 const canSubmit=!busy&&prompt.trim()&&(mode==='local'||(access?.allowed&&consent))&&(mode!=='vision'||attachment)&&(!['illustration','realistic'].includes(mode)||idea);
 return <Sheet title="NailMoods AI" eyebrow="UNE ENVIE, TA PROCHAINE POSE" className="nmAISheet" onClose={onClose}>
 <div className="nmAIWorkspace"><div className="nmAIConversation">
  <div className="nmAIIntro"><AtelierArt source="inspire"/><div><p>Une envie, une photo, tes vernis.</p><span>Créons une pose qui te ressemble.</span></div></div>
  <div className="nmAIIntentTabs" role="group" aria-label="Que souhaites-tu créer ?">
   {[['conversation','Créer une pose',Sparkles],['trends','Les tendances',TrendingUp],['vision','Avec une photo',ImagePlus]].map(([value,label,Icon])=><button type="button" key={value} aria-pressed={value==='conversation'?['conversation','local','illustration','realistic'].includes(mode):mode===value} disabled={busy||(!access?.allowed&&value!=='conversation')||value!=='conversation'&&!access?.operations?.[value]?.enabled} onClick={()=>chooseMode(value==='conversation'&&!access?.allowed?'local':value)}><Icon size={18}/><span>{label}</span></button>)}
  </div>
  {mode==='local'&&<p className="nmAINotice nmAILocalNote">Tu composes avec les outils NailMoods, sans envoi à l’IA. Enregistre ta pose pour la conserver.</p>}
  {['illustration','realistic'].includes(mode)&&<div className="nmAISelectedOutput"><Brush size={18}/><span>{mode==='illustration'?'Un dessin de ta composition':'Un aperçu réaliste de ta composition'}</span><button type="button" disabled={busy} onClick={()=>chooseMode('conversation')}>Revenir à ma pose</button></div>}
  {mode==='vision'&&<div className="nmAIPhotoBox">{attachment?<><img className="nmAIReference" src={attachment} alt="Ta photo d’inspiration"/><span>Ta photo est prête</span></>:<><AtelierArt source="photos"/><p>Choisis une photo qui t’inspire.</p></>}<label className="nmAIPhotoPick"><ImagePlus size={18}/>{attachment?'Changer de photo':'Ajouter ma photo'}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={photo} disabled={busy}/></label><small>JPG, PNG ou WebP · 5 Mo maximum</small></div>}
  <form className="nmAIComposer" onSubmit={run}>
   <label className="nmAIPromptLabel" htmlFor="nm-ai-prompt">{modeText[0]}</label><textarea id="nm-ai-prompt" value={prompt} maxLength={3000} rows={3} onChange={e=>setPrompt(e.target.value)} placeholder={modeText[1]} disabled={busy}/>
   {!messages.length&&!['illustration','realistic'].includes(mode)&&<div className="nmAISuggestions" aria-label="Quelques idées pour commencer">{suggestions.map(t=><button type="button" key={t} disabled={busy} onClick={()=>setPrompt(t)}>{t}<ArrowUp size={13}/></button>)}</div>}
   <label className="nmAICheck"><input type="checkbox" checked={only} disabled={busy} onChange={e=>setOnly(e.target.checked)}/><span>Utiliser uniquement mes vernis</span></label>
   {mode!=='local'&&<div className="nmAIConsent"><label className="nmAICheck"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/><span>J’autorise l’envoi de cette demande à l’IA.</span></label><details><summary>Quelles données sont envoyées ?</summary><p>Ton texte, les références utiles de tes vernis et les derniers échanges sont transmis à OpenAI.{['vision','illustration','realistic'].includes(mode)?' La photo ou l’aperçu de ta pose est également transmis.':''} Tes échanges restent privés dans NailMoods et tu peux les supprimer. Aucun achat automatique.</p></details></div>}
   <button className="nmAIPrimary" disabled={!canSubmit}>{busy?(progress||'Préparation…'):modeText[2]}<ArrowUp size={18}/></button>
   {busy&&<button className="nmAIQuiet" type="button" onClick={()=>controller.current?.abort()}><Square size={14}/>Arrêter l’attente</button>}
   {access?.admin&&mode!=='local'&&<p className="nmAITrial"><ShieldCheck size={14}/>Ton essai privé est {access.enabled?'actif':'en pause'}{creditCost>0?' · '+creditCost+' jeton'+(creditCost>1?'s':'')+' pour cette demande':''}.</p>}
  </form>
  {error&&<p role="alert" className="formError nmAIAlert">{error}</p>}{notice&&<p role="status" className="nmAIStatus"><Check size={16}/>{notice}</p>}
  <div className="nmAIMessages" role="log" aria-live="polite">{messages.map((m,i)=><article key={i} className={'nmAIMessage '+m.role}><small>{m.role==='user'?'Toi':'NailMoods'}</small><p>{m.text}</p>{m.sources?.map(source=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer">{source.title} · consulté le {new Date(source.accessedAt).toLocaleDateString('fr-FR')}{source.publishedAt?' · publié le '+source.publishedAt:''}</a>)}{m.action==='share'&&idea&&onShare&&<button className="nmAISecondary" onClick={()=>onShare(idea)}>Choisir ma PO et confirmer</button>}</article>)}</div>
 </div>
 <aside className={'nmAIPreview'+(!idea?' nmAIPreviewEmpty':'')}><span className="nmAIEyebrow">TON ATELIER</span><h3>{idea?'Ta pose prend forme':'De l’idée à ta pose'}</h3>
 {idea?<><div ref={preview}><NailPreview idea={idea}/></div><p className="nmAIPoseTitle">{idea.title}</p><p className="nmAINotice">Un aperçu pour t’inspirer. Vérifie tes couleurs et tes produits avant la réalisation.</p><div className="nmAIActions"><button className="nmAIPrimary" onClick={()=>onOpen(idea)}><Palette size={17}/>Personnaliser ma pose</button><button className="nmAISecondary" onClick={()=>{if(onSave(idea)!==false)setNotice('Ta pose est enregistrée dans tes projets.');}}><Check size={17}/>Enregistrer</button><button className="nmAISecondary" aria-expanded={tutorial} onClick={()=>setTutorial(v=>!v)}>Voir les étapes<ChevronRight size={17}/></button></div>
 <div className="nmAIOutputActions"><p>Envie de voir ta pose autrement ?</p><button disabled={busy||!access?.allowed||!access?.operations?.illustration?.enabled} onClick={()=>preparePreview('illustration')}><Brush size={20}/><span><b>En dessin</b><small>Une illustration de ta pose</small></span><ChevronRight size={16}/></button><button disabled={busy||!access?.allowed||!access?.operations?.realistic?.enabled} onClick={()=>preparePreview('realistic')}><Camera size={20}/><span><b>En rendu réaliste</b><small>Un aperçu généré par l’IA</small></span><ChevronRight size={16}/></button></div>
 {image&&<figure><img src={image} alt="Aperçu synthétique IA de la composition"/><figcaption>Aperçu créé par l’IA · vérifie les motifs et les couleurs.</figcaption></figure>}
 {tutorial&&<div className="nmAITutorial"><h4>Ta pose, étape par étape</h4><p className="nmAINotice">Guide NailMoods : complète-le avec les notices de tes produits.</p><ol>{tutorialFor(idea).map(step=><li key={step.id}><b>{step.title}</b><p>{step.body}</p></li>)}</ol><button className="nmAISecondary" onClick={()=>onTutorial(idea)}>Ouvrir ma pose guidée<ChevronRight size={17}/></button></div>}</>:<><AtelierArt source="manual"/><p>Décris ton envie : ta composition sur cinq ongles apparaîtra ici.</p><span className="nmAINotice">Tu pourras l’ajuster, l’enregistrer et suivre ses étapes.</span></>}
 </aside></div>
 <div className="nmAIFooter">
 <details className="nmAIDisclosure"><summary>Mes conversations<small>{threads.length?threads.length+' enregistrée'+(threads.length>1?'s':''):'Privées et supprimables'}</small></summary><div className="nmAIDisclosureBody"><button className="nmAISecondary" disabled={busy} onClick={()=>{setThread(crypto.randomUUID());setMessages([]);setImage(null);setIdea(null);setTutorial(false);setError('');setNotice('');chooseMode(access?.allowed?'conversation':'local');}}>Nouvelle conversation</button>{threads.map(t=><button className="nmAIHistoryRow" key={t.id} disabled={busy} onClick={()=>load(t.id)}>{t.title}<ChevronRight size={15}/></button>)}{!threads.length&&<p className="nmAINotice">Tes conversations IA apparaîtront ici après ta première demande.</p>}{threads.some(t=>t.id===thread)&&<button className="nmAIQuiet" onClick={()=>setDeleteAsk(true)}><Trash2 size={14}/>Supprimer cette conversation</button>}{deleteAsk&&<div className="nmAIConfirmation"><p>Supprimer les échanges et aperçus de cette conversation ? Tes poses enregistrées sont conservées.</p><button className="nmAISecondary" disabled={busy} onClick={remove}>Confirmer la suppression</button><button className="nmAIQuiet" onClick={()=>setDeleteAsk(false)}>Conserver</button></div>}</div></details>
 <details className="nmAIDisclosure"><summary>Mes préférences<small>Créer avec ou sans IA</small></summary><div className="nmAIDisclosureBody"><button className="nmAISecondary" disabled={busy} aria-pressed={mode==='local'} onClick={()=>chooseMode(mode==='local'&&access?.allowed?'conversation':'local')}>{mode==='local'&&access?.allowed?'Retrouver l’assistante IA':'Composer sans IA'}</button><p className="nmAINotice">Sans IA, NailMoods utilise ses règles de création. Les échanges restent sur cet écran ; enregistre ta pose pour la conserver.</p></div></details>
 {access?.admin&&<details className="nmAIDisclosure nmAIAdmin"><summary>Mon essai privé<small>Arrêt et consommation</small></summary><div className="nmAIDisclosureBody"><p>Ton plafond d’essai : <b>{access.dailyBudget} $ par jour</b> et <b>{access.monthlyBudget} $ par mois</b>.</p><button className="nmAISecondary nmAIPower" disabled={switching} onClick={async()=>{setSwitching(true);try{const next=await assistantCall(social.client,{action:'switch',enabled:!access.enabled});setAccess(next);if(!busy)chooseMode(next.enabled?'conversation':'local');setNotice(next.enabled?'Ton essai IA est réactivé.':'Ton essai IA est en pause. Les demandes déjà envoyées peuvent se terminer.');}catch{setError('Le changement n’a pas été confirmé.');}finally{setSwitching(false);}}}><Power size={17}/>{access.enabled?'Mettre l’IA en pause':'Réactiver mon essai IA'}</button><p className="nmAINotice">La pause empêche les nouvelles demandes. Celles déjà envoyées peuvent se terminer.</p><div className="nmAIAdminTools"><button className="nmAIQuiet" onClick={async()=>{try{const d=await assistantCall(social.client,{action:'diagnostics'});setNotice(d.authenticated?'La connexion IA fonctionne. Ce contrôle n’a lancé aucune création.':'La connexion IA doit être vérifiée.');}catch{setError('La vérification n’est pas disponible.');}}}>Vérifier la connexion</button><button className="nmAIQuiet" onClick={async()=>{try{const [bilan,health]=await Promise.all([assistantCall(social.client,{action:'metrics'}),assistantCall(social.client,{action:'health'})]);setMetrics({...bilan,health});}catch{setError('La consommation n’a pas pu être chargée.');}}}>Voir ma consommation</button></div>{metrics&&<div className="nmAIBudget"><p>{metrics.health?.queued??0} demandes en attente · {metrics.health?.running??0} en cours</p><table><thead><tr><th>Création</th><th>Demandes</th><th>Coût estimé</th></tr></thead><tbody>{metrics.byOperation.map((r,i)=><tr key={i}><td>{{conversation:'Pose',trends:'Tendances',vision:'Photo',illustration:'Dessin',realistic:'Rendu'}[r.operation]||r.operation}</td><td>{r.requests}</td><td>{r.estimated_usd==null?'À vérifier':Number(r.estimated_usd).toFixed(3)+' $'}</td></tr>)}</tbody></table><p className="nmAINotice">Estimation de l’usage IA, à rapprocher de la facture.</p></div>}</div></details>}
 </div></Sheet>;
}
