import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {setup,login,rpc,A,B,C} from './helpers/pro-db.js';
const migrations=['20261009095000_admob_disabled_reward_ledger.sql','20261009103000_admob_callback_platform_guard.sql','20261010115500_admob_consent_and_reward_guards.sql'];
async function database(){const db=await setup();await db.exec(`create role service_role;grant usage on schema public,private to service_role;
 alter table public.user_consents add column terms_version text default '0.6-beta',add column terms_accepted_at timestamptz default now();
 create function private.nm_age_band(actor uuid) returns text language sql stable as $$select case when adult_confirmed_at is not null then '18_plus' else 'unknown' end from public.user_consents where user_id=actor$$;`);
 for(const file of migrations)await db.exec(readFileSync(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));return db;}
const confirm=async(db,ticket,tx,platform='ios')=>{await db.exec('reset role;set role service_role');return rpc(db,'nm_ad_confirm_platform_reward',[ticket,tx,platform]);};
test('Reward reservations, ownership and confirmation stay gated and idempotent',async()=>{const db=await database();try{
 await login(db,C);assert.equal((await rpc(db,'nm_ad_state',['ios'])).config.enabled,false);
 await assert.rejects(rpc(db,'nm_ad_reward_ticket',['ios']),/ads_unavailable/);
 await db.exec("reset role;update private.ad_config set enabled=true;");await login(db,C);
 await assert.rejects(rpc(db,'nm_ad_reward_ticket',['ios']),/ads_unavailable/);
 await db.exec('reset role;update private.ad_config set test_only=false');await login(db,C);
 const ticket=(await rpc(db,'nm_ad_reward_ticket',['ios'])).ticket;
 assert.equal((await rpc(db,'nm_ad_reward_ticket',['ios'])).ticket,ticket);
 assert.deepEqual(await rpc(db,'nm_ad_reward_status',[ticket]),{confirmed:false,used:false,expired:false});
 await assert.rejects(rpc(db,'nm_ad_confirm_platform_reward',[ticket,'forged','ios']),/permission denied/);
 await assert.rejects(db.query('select * from private.ad_reward_tickets'),/permission denied/);
 await login(db,B);assert.equal(await rpc(db,'nm_ad_reward_status',[ticket]),null);
 await assert.rejects(rpc(db,'nm_ad_reward_ticket',['ios']),/ads_unavailable/);
 assert.equal(await confirm(db,ticket,'verified','android'),false);
 assert.equal(await confirm(db,ticket,null),false);
 assert.equal(await confirm(db,ticket,'verified'),true);
 assert.equal(await confirm(db,ticket,'verified'),true);
 assert.equal(await confirm(db,ticket,'other-tx'),false);
 await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from private.ad_reward_tickets where confirmed_at is not null')).rows[0].n,1);
 await login(db,C);await assert.rejects(rpc(db,'nm_ad_reward_ticket',['android']),/ad_daily_limit/);
 await db.exec('reset role');await db.query("update private.ad_reward_tickets set expires_at=now()-interval '1 hour' where id=$1",[ticket]);
 assert.equal(await confirm(db,ticket,'verified'),true);
 await db.exec('reset role;set role anon');await assert.rejects(rpc(db,'nm_ad_reward_status',[ticket]),/permission denied/);
 }finally{await db.close();}});
test('Eligibility is rechecked at confirmation and transaction IDs cannot cross accounts',async()=>{const db=await database();try{
 await db.exec('update private.ad_config set enabled=true,test_only=false,daily_limit=3');await login(db,C);
 const ios=(await rpc(db,'nm_ad_reward_ticket',['ios'])).ticket,android=(await rpc(db,'nm_ad_reward_ticket',['android'])).ticket;
 await db.exec('reset role');await db.query('insert into private.suspended values($1)',[C]);
 assert.equal(await confirm(db,ios,'suspended'),false);
 await db.exec('reset role;delete from private.suspended');
 await db.query('update public.user_consents set adult_confirmed_at=null where user_id=$1',[C]);assert.equal(await confirm(db,ios,'minor'),false);
 await db.exec('reset role');await db.query("update public.user_consents set adult_confirmed_at=now() where user_id=$1",[C]);
 await db.query("update public.profiles set account_tier='plus' where id=$1",[C]);assert.equal(await confirm(db,ios,'paid'),false);
 await db.exec('reset role');await db.query("update public.profiles set account_tier='free' where id=$1",[C]);
 const wid=(await db.query("insert into public.workspaces(owner_user_id,kind,organization_type,name) values($1,'institute','institute','Salon') returning id",[A])).rows[0].id;
 await db.query('insert into public.workspace_entitlements(workspace_id,active) values($1,true)',[wid]);await db.query("insert into public.workspace_members values($1,$2,'member')",[wid,C]);
 await login(db,C);const state=await rpc(db,'nm_ad_state',['ios']);assert.equal(state.rights.instituteActive,true);assert.equal(state.config.enabled,false);
 assert.equal(await confirm(db,ios,'salon'),false);
 await db.exec('reset role');await db.query('delete from public.workspace_members where workspace_id=$1',[wid]);
 assert.equal(await confirm(db,ios,'one-transaction'),true);
 assert.equal(await confirm(db,android,'one-transaction','android'),false);
 await db.exec('reset role');await db.query("update private.ad_reward_tickets set expires_at=now()-interval '1 minute' where id=$1",[android]);
 assert.equal(await confirm(db,android,'expired','android'),false);
 await db.exec('reset role');assert.deepEqual((await db.query('select * from private.nm_legal_versions()')).rows[0],{privacy_version:'0.9-beta',terms_version:'0.6-beta'});
 const secured=await db.query("select relname,relrowsecurity from pg_class where relname in ('ad_config','ad_reward_tickets')");assert.equal(secured.rows.every(r=>r.relrowsecurity),true);
 }finally{await db.close();}});
