import test from 'node:test';
import assert from 'node:assert/strict';
import {appleRecord,resolveAccess} from '../supabase/functions/_shared/appleCore.mjs';
import {SignedDataVerifier,Environment} from '@apple/app-store-server-library';
const now=Date.now(),token='00000000-0000-4000-8000-000000000001';
const tx={bundleId:'com.nailmoods.app',environment:'Production',appAccountToken:token,productId:'nailmoods_plus',type:'Auto-Renewable Subscription',transactionId:'100',originalTransactionId:'99',purchaseDate:now-1000,expiresDate:now+100000,signedDate:now};
const renewal={originalTransactionId:'99',environment:'Production',autoRenewStatus:1};
const options={bundleId:tx.bundleId,environment:tx.environment,accountToken:token,now};
const record=(t={},r={},status=1)=>appleRecord({...tx,...t},{...renewal,...r},status,options);
for(const [name,status,expected] of [['B Apple Plus actif',1,'active'],['D expiré',2,'expired'],['F grâce',4,'grace'],['H révoqué',5,'revoked'],['facturation en échec',3,'billing_retry']])test(name,()=>assert.equal(record({}, {},status).status,expected));
test('C Apple Pro',()=>assert.equal(record({productId:'nailmoods_pro'}).tier,'pro'));
test('E annulé conserve période payée',()=>assert.equal(resolveAccess({apple:[record({}, {autoRenewStatus:0})]},now),'plus'));
test('grâce prolongée au-delà de la période payée',()=>assert.equal(record({expiresDate:now-1},{gracePeriodExpiresDate:now+5000},4).expiresAt,new Date(now+5000).toISOString()));
test('grâce terminée ne donne aucun accès',()=>assert.equal(record({expiresDate:now-1},{gracePeriodExpiresDate:now-1},4).status,'expired'));
test('G paiement en attente sans transaction ne donne aucun droit',()=>assert.equal(resolveAccess({apple:[{status:'pending',tier:'pro',environment:'Production',expiresAt:new Date(now+1000).toISOString()}]},now),'free'));
test('remboursement domine statut actif',()=>assert.equal(record({revocationDate:now-1}).status,'revoked'));
test('transaction remplacée après upgrade ne donne aucun accès',()=>assert.equal(record({isUpgraded:true}).status,'revoked'));
test('J/K upgrade puis downgrade',()=>{assert.equal(resolveAccess({apple:[record({productId:'nailmoods_pro'})]},now),'pro');assert.equal(resolveAccess({apple:[record()]},now),'plus');});
for(const tier of ['plus','pro'])test(`L/M/N droit manuel ${tier} persiste malgré Apple expiré/révoqué`,()=>{for(const status of [2,5])assert.equal(resolveAccess({manual:{tier,status:'active'},apple:[record({}, {},status)]},now),tier);});
test('droit manuel expiré ne reste pas actif',()=>assert.equal(resolveAccess({manual:{tier:'pro',status:'active',expiresAt:new Date(now-1).toISOString()}},now),'free'));
test('un abonnement Pro peut dépasser un droit manuel Plus sans le modifier',()=>assert.equal(resolveAccess({manual:{tier:'plus',status:'active'},apple:[record({productId:'nailmoods_pro'})]},now),'pro'));
test('O Google valide sur iPhone',()=>assert.equal(resolveAccess({google:[{status:'active',tier:'pro',expiresAt:new Date(now+1000).toISOString()}]},now),'pro'));
test('P Apple valide sur Android',()=>assert.equal(resolveAccess({apple:[record()]},now),'plus'));
test('Sandbox ne débloque pas un compte de production',()=>{const sandbox={...record(),environment:'Sandbox'};assert.equal(resolveAccess({apple:[sandbox]},now),'free');assert.equal(resolveAccess({apple:[sandbox],sandboxEnabled:true},now),'plus');});
test('mauvais compte, bundle, environnement et produit refusés',()=>{for(const invalid of [{appAccountToken:'other'},{bundleId:'other'},{environment:'Sandbox'},{productId:'fake'}])assert.throws(()=>record(invalid));});
test('JWS forgé refusé par la bibliothèque officielle Apple',async()=>{const v=new SignedDataVerifier([],true,Environment.SANDBOX,tx.bundleId);await assert.rejects(v.verifyAndDecodeTransaction('forged.payload.signature'));});
