import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {setup,login,insert,A,B,WA} from './helpers/pose-db.js';import {newProject} from '../src/poseCycle/model.js';
async function fixture(){const db=await setup();await db.exec(`create schema storage;create table storage.objects(bucket_id text,name text,owner_id text);create table public.media_cleanup_jobs(bucket text,object_path text,reason text,status text default 'pending');create unique index cleanup_unique on public.media_cleanup_jobs(bucket,object_path) where status in ('pending','processing','failed');create function public.media_cleanup_in_use(p_bucket text,p_path text) returns boolean language sql as $$select p_path='legacy-image'$$;`);for(const name of ['20261004142348_pose_outfit_source.sql','20261004155630_pose_followup_tracking.sql','20261004160931_pose_followup_journal_access.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));return db;}
test('Free tracking, owner isolation, media references and cleanup on replacement/deletion',async()=>{const db=await fixture();try{await login(db,A);let p=await insert(db,'pose_projects',newProject({userId:A,workspaceId:WA}));const e={id:crypto.randomUUID(),date:'2026-09-30',note:'J+7',feeling:'comfortable',state:'growth',media:null};const update=d=>db.query('update pose_projects set details=$2,status=$3 where id=$1 returning *',[p.id,d,'follow_up']);p=(await update({...p.details,realizedOn:'2026-09-23',followUp:[e]})).rows[0];assert.equal(p.details.followUp.length,1);await login(db,B);assert.equal((await db.query('select * from pose_projects where id=$1',[p.id])).rows.length,0);assert.equal((await db.query('update pose_projects set title=$2 where id=$1 returning id',[p.id,'foreign'])).rows.length,0);await login(db,A);await assert.rejects(update({...p.details,followUp:[{...e,date:'2026-09-01'}]}),/DATE_INVALID/);await assert.rejects(update({...p.details,followUp:[e,e]}),/INVALID/);await assert.rejects(update({...p.details,removedOn:'2026-09-01'}),/REMOVAL_DATE/);
 const path=`${A}/${WA}/followup/${p.id}-${e.id}-${crypto.randomUUID()}.jpg`;const media={bucket:'nailmoods-private',path,bytes:100,contentType:'image/jpeg'};await assert.rejects(update({...p.details,followUp:[{...e,media}]}),/MEDIA_MISSING/);await db.exec('reset role');await db.query("insert into storage.objects values('nailmoods-private',$1,$2)",[path,A]);await login(db,A);p=(await update({...p.details,followUp:[{...e,media}]})).rows[0];await db.exec('reset role');assert.equal((await db.query("select public.media_cleanup_in_use('nailmoods-private',$1) used",[path])).rows[0].used,true);await login(db,A);await update({...p.details,followUp:[e]});await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from media_cleanup_jobs where object_path=$1',[path])).rows[0].n,1);assert.equal((await db.query("select public.media_cleanup_in_use('nailmoods-private',$1) used",[path])).rows[0].used,false);assert.equal((await db.query("select public.media_cleanup_in_use('nailmoods-private','legacy-image') used")).rows[0].used,true);
 }finally{await db.close();}});
test('downgraded photo-project owner can follow up without unlocking premium creation or editing',async()=>{const db=await fixture();try{await db.query("update private.account_entitlements set tier='plus' where user_id=$1",[A]);await login(db,A);let p=await insert(db,'pose_projects',newProject({userId:A,workspaceId:WA,source:'outfit'}));await db.exec('reset role');await db.query("update private.account_entitlements set tier='free' where user_id=$1",[A]);await login(db,A);const d={...p.details,realizedOn:'2026-09-30',followUp:[{id:crypto.randomUUID(),date:'2026-09-30',note:'Ma pose',feeling:'',state:'',media:null}]};await db.query("update pose_projects set details=$2,status='follow_up' where id=$1",[p.id,d]);await assert.rejects(db.query('update pose_projects set details=$2 where id=$1',[p.id,{...d,notes:'Premium source edit'}]),/FEATURE_REQUIRES_PLUS/);await assert.rejects(db.query('update pose_projects set details=$2 where id=$1',[p.id,{...d,source:'manual'}]),/FEATURE_REQUIRES_PLUS/);await assert.rejects(insert(db,'pose_projects',newProject({userId:A,workspaceId:WA,source:'outfit'})),/FEATURE_REQUIRES_PLUS/);
 }finally{await db.close();}});

test('Free can follow an owned photographic Journal entry; foreign Journal links remain forbidden',async()=>{const db=await fixture();try{const jid=crypto.randomUUID();await db.query('insert into journal_entries(id,workspace_id,created_by,performed_on) values($1,$2,$3,$4)',[jid,WA,A,'2026-09-30']);const p=newProject({userId:A,workspaceId:WA,source:'journal'});p.journal_entry_id=jid;p.details.composition={intent:'photos',palette:[],nails:[{},{},{},{},{}]};p.details.realizedOn='2026-09-30';p.status='done';await login(db,A);await insert(db,'pose_projects',p);const foreign=newProject({userId:A,workspaceId:WA,source:'journal'});foreign.journal_entry_id=crypto.randomUUID();await assert.rejects(insert(db,'pose_projects',foreign),/JOURNAL_FORBIDDEN/); }finally{await db.close();}});
