import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {setup,login,A,B,WA} from './helpers/pose-db.js';import {outfitDirections,outfitProject,outfitEvent} from '../src/poseCycle/outfit.js';
const migration='supabase/migrations/20261004142348_pose_outfit_source.sql';
async function fixture(){const db=await setup();await db.exec(`create schema storage;create table storage.objects(bucket_id text,name text,owner_id text);create table public.media_cleanup_jobs(bucket text,object_path text,reason text,status text default 'pending');create unique index cleanup_unique on public.media_cleanup_jobs(bucket,object_path) where status in ('pending','processing','failed');create function public.media_cleanup_in_use(p_bucket text,p_path text) returns boolean language sql as $$select p_path='legacy-image'$$;`);await db.exec(fs.readFileSync(migration,'utf8'));await db.exec("create function public.nm_capabilities() returns jsonb language sql as $$select jsonb_build_object('tier',private.effective_tier(auth.uid()))$$; create table private.analytics_event_catalog(event_name text primary key,category text,allowed_metadata_keys text[]);");await db.exec(fs.readFileSync('supabase/migrations/20261004143417_pose_outfit_access_analytics.sql','utf8'));return db;}
const analysis={colors:['#703650','#88916f'],ambience:'Douce',contrast:20};
async function project(db){const id=crypto.randomUUID(),path=`${A}/${WA}/pose/${id}.jpg`;await db.query("insert into storage.objects values('nailmoods-private',$1,$2)",[path,A]);return outfitProject({principal:{userId:A,workspaceId:WA},id,proposal:outfitDirections({analysis})[0],analysis,mode:'match',collectionOnly:false,crop:{zoom:1,x:50,y:50},media:{path,bucket:'nailmoods-private',contentType:'image/jpeg',bytes:100}});}
test('atomic outfit save, event in existing Planning, idempotent retry and cleanup references',async()=>{const db=await fixture();try{const p=await project(db),e=outfitEvent(p,{name:'Mon événement',date:'2026-10-10',timezone:'Europe/Paris'});await db.query("update private.account_entitlements set tier='plus' where user_id=$1",[A]);await login(db,A);const save=()=>db.query('select (public.save_pose_outfit($1,$2)).*',[p,e]);const saved=(await save()).rows[0];assert.equal(saved.id,p.id);await save();assert.equal((await db.query('select count(*)::int n from pose_plan_items')).rows[0].n,1);
await login(db,B);assert.equal((await db.query('select * from pose_projects where id=$1',[p.id])).rows.length,0);await assert.rejects(db.query('select public.save_pose_outfit($1,null)',[p]));await db.exec('reset role');assert.equal((await db.query("select public.media_cleanup_in_use('nailmoods-private',$1) used",[p.details.outfitMedia.path])).rows[0].used,true);assert.equal((await db.query("select public.media_cleanup_in_use('nailmoods-private','legacy-image') used")).rows[0].used,true);await login(db,A);await db.query('delete from pose_projects where id=$1',[p.id]);await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from media_cleanup_jobs')).rows[0].n,1);assert.equal((await db.query('select count(*)::int n from pose_plan_items')).rows[0].n,0);
}finally{await db.close();}});
test('Free and foreign/missing outfit paths refused; invalid event rolls back entire project',async()=>{const db=await fixture();try{const p=await project(db);await login(db,A);await assert.rejects(db.query('select public.save_pose_outfit($1,null)',[p]),/FEATURE_REQUIRES_PLUS/);await db.exec('reset role');await db.query("update private.account_entitlements set tier='plus' where user_id=$1",[A]);await login(db,A);await assert.rejects(db.query('select public.save_pose_outfit($1,null)',[{...p,details:{...p.details,outfitMedia:{...p.details.outfitMedia,path:p.details.outfitMedia.path.replace(A,B)}}}]));await assert.rejects(db.query('select public.save_pose_outfit($1,$2)',[p,{id:crypto.randomUUID(),title:'invalid',scheduled_on:'2026-02-30',timezone:'Europe/Paris'}]));assert.equal((await db.query('select count(*)::int n from pose_projects')).rows[0].n,0);}finally{await db.close();}});
test('empty-data rollback restores legacy cleanup and removes outfit RPC',async()=>{const db=await fixture();try{await db.exec(fs.readFileSync('docs/pose-lot2/ROLLBACK.sql','utf8'));assert.equal((await db.query("select to_regprocedure('public.save_pose_outfit(jsonb,jsonb)') fn")).rows[0].fn,null);assert.equal((await db.query("select public.media_cleanup_in_use('nailmoods-private','legacy-image') used")).rows[0].used,true);assert.equal((await db.query("select count(*)::int n from information_schema.tables where table_name in ('pose_projects','pose_plan_items','pose_reminders')")).rows[0].n,3);}finally{await db.close();}});
