import test from 'node:test';import assert from 'node:assert/strict';
import {setup,login,rpc,draft,A,B,C} from './helpers/pro-db.js';
test('Pro V2 isolation, public fields, seats and explicit team consent',async()=>{const db=await setup();try{
 await login(db,A);const wid=await rpc(db,'nm_pro_save',[null,draft()]);
 let state=await rpc(db,'nm_pro_state');assert.equal(state.spaces[0].seats.limit,1);assert.equal(state.spaces[0].fields.city,'Paris');
 await assert.rejects(rpc(db,'nm_pro_team',[wid,'invite',{handle:'artist.b'}]),/workspace_full/);
 await login(db,B);await assert.rejects(rpc(db,'nm_pro_save',[wid,draft()]),/showcase_editor_required/);
 let pub=await rpc(db,'nm_pro_public',['studio.a']);assert.equal(pub.professional.fields.city,undefined);assert.equal(pub.professional.fields.website,undefined);assert.equal(pub.professional.fields.bio,'Ma bio');assert.equal(pub.professional.team.length,0);
 await assert.rejects(db.query('select * from private.pro_showcase_details'),/permission denied/);
 await db.exec('reset role');await db.query('update public.workspace_entitlements set seat_limit=2 where workspace_id=$1',[wid]);
 await login(db,A);const invite=await rpc(db,'nm_pro_team',[wid,'invite',{handle:'artist.b'}]);
 await login(db,C);await assert.rejects(rpc(db,'nm_pro_team',[wid,'accept',{invitationId:invite.invitation_id}]),/invitation_unavailable/);await assert.rejects(rpc(db,'nm_pro_save',[null,draft('Free','free.store')]),/FEATURE_REQUIRES_PRO/);
 await login(db,B);await rpc(db,'nm_pro_team',[wid,'accept',{invitationId:invite.invitation_id}]);await rpc(db,'nm_pro_team',[wid,'visibility',{visible:true}]);
 pub=await rpc(db,'nm_pro_public',['studio.a']);assert.equal(pub.professional.team.length,1);
 state=await rpc(db,'nm_pro_state');assert.equal(state.spaces[0].fields.city,undefined);assert.equal(state.spaces[0].fields.website,'https://example.com');
 await rpc(db,'nm_pro_team',[wid,'leave',{}]);assert.equal((await rpc(db,'nm_pro_public',['studio.a'])).professional.team.length,0);
 }finally{await db.close();}});
test('creator verification, moderation, private products, assets and role escalation',async()=>{const db=await setup();try{
 await login(db,A);const d={...draft(),professionalType:'product_creator',organizationType:'creator_team'};const wid=await rpc(db,'nm_pro_save',[null,d]);
 const item={title:'Cassis',visibility:'public',claimStatus:'verified',details:{hex:'#800040',category:'Gel',description:'Teinte cassis'}};
 const iid=await rpc(db,'nm_pro_item',[wid,null,'product',item]);assert.equal((await rpc(db,'nm_pro_public',['studio.a'])).professional.items[0].claimStatus,'community');
 await assert.rejects(rpc(db,'nm_pro_review',[iid,null,null,true,'ref']),/staff_required/);
 await assert.rejects(rpc(db,'nm_pro_item',[wid,null,'product',{...item,details:{technical:'60s'}}]),/documented_source_required/);
 await assert.rejects(rpc(db,'nm_pro_item',[wid,null,'product',{...item,details:{officialUrl:'javascript:alert(1)'}}]),/invalid_public_url/);
 await login(db,B);await assert.rejects(rpc(db,'nm_pro_item',[wid,iid,'product',item]),/showcase_editor_required/);
 await assert.rejects(rpc(db,'nm_pro_team',[wid,'role',{userId:B,role:'admin'}]),/owner_required/);
 await db.exec('reset role');await db.query('insert into private.staff values($1)',[A]);await login(db,A);
 await rpc(db,'nm_pro_review',[iid,null,null,true,'catalog-real-reference']);
 await rpc(db,'nm_pro_item',[wid,iid,'product',{...item,title:'Modification non modérée'}]);
 assert.equal((await rpc(db,'nm_pro_public',['studio.a'])).professional.items[0].title,'Cassis');
 const path=`${A}/${wid}/picture.png`;await db.query("insert into storage.objects(bucket_id,name) values('nailmoods-pro',$1)",[path]);
 await login(db,B);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await login(db,A);d.fields.cover=path;d.visibility.cover='public';await rpc(db,'nm_pro_save',[wid,d]);
 await login(db,B);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await login(db,A);const moderation=await rpc(db,'nm_pro_moderation',['list',null,null,null]);const cover=moderation.images.find(i=>i.kind==='pro_cover');await rpc(db,'nm_pro_moderation',['approve','pro_cover',wid,cover.fingerprint]);
 await login(db,B);assert.equal((await db.query('select * from storage.objects')).rows.length,1);
 await login(db,A);d.isPublic=false;await rpc(db,'nm_pro_save',[wid,d]);await login(db,B);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 }finally{await db.close();}});
test('public portfolio consent applies to legacy readers and private collection IDs are redacted',async()=>{const db=await setup();try{await login(db,A);const wid=await rpc(db,'nm_pro_save',[null,{...draft(),professionalType:'product_creator'}]);
 await db.exec('reset role');const cid=(await db.query('insert into public.inspirations(workspace_id,created_by,is_public,title,snapshot) values($1,$2,true,$3,$4) returning id',[wid,A,'Public inspiration','{}'])).rows[0].id;
 await login(db,B);assert.equal((await rpc(db,'get_public_profile',['studio.a'])).inspirations.length,0);
 await login(db,A);await rpc(db,'nm_pro_portfolio',[wid,'inspiration',cid,null,true]);await login(db,B);assert.equal((await rpc(db,'get_public_profile',['studio.a'])).inspirations.length,1);
 await login(db,A);const pid=await rpc(db,'nm_pro_item',[wid,null,'product',{title:'Secret product',visibility:'private',details:{}}]);await rpc(db,'nm_pro_item',[wid,null,'collection',{title:'Public collection',visibility:'public',details:{productIds:[pid]}}]);
 await login(db,B);const pub=await rpc(db,'nm_pro_public',['studio.a']);assert.deepEqual(pub.professional.items[0].details.productIds,[]);
 }finally{await db.close();}});
