import test from 'node:test';import assert from 'node:assert/strict';
import {lifestyle,practicalSuggestions,colorSuggestions} from '../src/lifestyle/model.js';
import {PRODUCT_DOCUMENTS} from '../src/productKnowledge/registry.js';
import {productDocument,ingredientReport,inciEntries,inciFor,recordIngredients,documentedCompatibility,productAlternatives} from '../src/productKnowledge/model.js';
import {manufacturerProtocols,documentedCuring} from '../src/poseCycle/protocols.js';
import {productRow,productFromRow,profilePatch,viewsFromRemote} from '../src/cloud/mapping.js';
const green={...PRODUCT_DOCUMENTS[0].identity,id:'green',productKind:'Couleur'},flash={...PRODUCT_DOCUMENTS[1].identity,id:'flash',productKind:'Couleur'};
test('optional private profile bounded and unknown values ignored; no automatic preferences',()=>{assert.deepEqual(lifestyle().daily,[]);assert.deepEqual(lifestyle(null),lifestyle());assert.deepEqual(lifestyle({daily:1,nails:{},watch:[12,null]}),lifestyle());assert.equal(lifestyle().undertone,'off');const raw={daily:['keyboard','long','fake'],nails:['sensitive'],watch:['HEMA','HEMA'],undertone:'unknown'};assert.equal(lifestyle(raw).watch.length,1);assert.equal(practicalSuggestions(raw).length,3);assert.ok(practicalSuggestions(raw).every(s=>s.length==='Courte'));assert.deepEqual(raw.daily,['keyboard','long','fake']);assert.deepEqual(colorSuggestions(raw),[]);assert.equal(colorSuggestions({undertone:'warm'}).length,3);assert.deepEqual(practicalSuggestions({}),[]);});
test('INCI chemical parentheses, HEMA/Di-HEMA/Bis-HEMA not confused',()=>{const text='HEMA, Di-HEMA Trimethylhexyl Dicarbamate, bis-HEMA poly(1,4-butanediol)-9/IPDI copolymer, BHT';assert.equal(inciEntries(text).length,4);const r=ingredientReport(text,['HEMA','Di-HEMA','BHT']);assert.deepEqual(r.map(x=>x.watched),[['HEMA'],['Di-HEMA'],[],['BHT']]);assert.equal(ingredientReport('HEMA-free',['HEMA'])[0].watched.length,0);});
test('reviewed record requires exact identity; no metadata claims trusted',()=>{assert.ok(productDocument(flash));for(const k of Object.keys(flash).filter(k=>!['id','productKind'].includes(k)))assert.equal(productDocument({...flash,[k]:'different'}),null,k);assert.equal(productDocument({...green,collection:'Green Flash'}),null);assert.equal(inciFor({verified:true,inci:'HEMA'}),null);});
test('personal INCI needs actual source selection and is invalidated on identity change',()=>{let p={id:'x',name:'Private',type:'Gel'};p.ingredientRecord=recordIngredients(p,{text:'HEMA'});assert.equal(inciFor(p),null);p.ingredientRecord=recordIngredients(p,{source:'label'});assert.equal(inciFor(p).personal,true);assert.equal(inciFor({...p,name:'Other'}),null);assert.equal(inciFor({...p,ingredientRecord:null}),null);});
test('compatibility is independent from color / unverifiable personal claims',()=>{assert.equal(documentedCompatibility(green,flash).state,'incompatible');assert.equal(documentedCompatibility(flash,{...flash,id:'b',name:'Other color'}).state,'documented');assert.equal(documentedCompatibility(green,{...green,id:'b'}).state,'unknown');assert.equal(documentedCompatibility(flash,{...flash,type:'Gel'}).state,'unknown');assert.equal(documentedCompatibility(flash,{id:'b',verified:true,compatible:true}).state,'unknown');});
test('exact lamp and layer only, no watts heuristic',()=>{assert.equal(manufacturerProtocols(flash,'curing').length,2);assert.equal(documentedCuring(flash,'Manucurist · Lampe Slim 24W','color')[0].seconds,120);assert.equal(documentedCuring(flash,'24W','color').length,0);assert.equal(documentedCuring(flash,'Manucurist · Lampe Slim 24W','base').length,0);assert.equal(manufacturerProtocols(green,'curing').length,0);assert.equal(manufacturerProtocols({...flash,sku:''},'curing').length,0);});
test('alternatives respect type finish opacity and keep original HEX',()=>{const a={id:'a',name:'A',type:'Vernis',productKind:'Couleur',color:'#813c60',shade:'#813c60',colorSource:'manual',finish:'Crème',opacity:'Opaque'},b={...a,id:'b',name:'B',shade:'#823d60',color:'#823d60'};const before=JSON.stringify([a,b]);assert.equal(productAlternatives(a,[a,b]).state,'near');assert.equal(productAlternatives({...a,effect:'Aucun'},[a,b]).state,'near');assert.equal(productAlternatives(a,[a,{...b,type:'Gel'}]).state,'missing');assert.equal(productAlternatives(a,[a,{...b,opacity:'Translucide'}]).state,'missing');assert.equal(JSON.stringify([a,b]),before);});
test('existing profile and product JSON roundtrip preserve new fields',()=>{const p={name:'A',lifestyle:lifestyle({daily:['keyboard'],watch:['HEMA']})};assert.deepEqual(profilePatch(p,{legacy:true}).preferences.nailmoodsProfile.lifestyle,p.lifestyle);const product={...flash,ingredientRecord:recordIngredients(flash,{source:'label',text:'HEMA'}),opacity:'Opaque'};const row=productRow(product);assert.deepEqual(row.metadata.nailmoods.ingredientRecord,product.ingredientRecord);});

test('private ingredient transcription is excluded from inspiration snapshots',async()=>{const {snapshotIdea}=await import('../src/inspirations.js');const {outfitDirections}=await import('../src/poseCycle/outfit.js');const idea=outfitDirections({analysis:{colors:['#813c60','#eeeeee'],ambience:'Douce'},mode:'match'})[0].idea;idea.palette[0].ingredientRecord={source:'label',text:'PRIVATE-INCI'};const saved=snapshotIdea(idea);assert.equal(JSON.stringify(saved).includes('PRIVATE-INCI'),false);assert.equal(idea.palette[0].ingredientRecord.text,'PRIVATE-INCI');});
