import test from 'node:test';import assert from 'node:assert/strict';
import {timerNotice,createTimerScheduler,TIMER_NOTIFICATION_ID} from '../src/poseCycle/timerScheduler.js';import {newTutorial,updateTutorial,timerRemaining,readTutorials} from '../src/tutorial.js';import {outfitDirections} from '../src/poseCycle/outfit.js';
import {documentedCuring,manufacturerProtocols,validManufacturerProtocol} from '../src/poseCycle/protocols.js';
const session={id:'pose-test',status:'active',alertsEnabled:true,timer:{status:'running',endsAt:20000}},input={session,userId:'A',workspaceId:'WA',now:1000};
function adapter(){let pending=[{id:1700000000,extra:{scope:'pose-planning'}}],delivered=[],permission='granted',writes=0;return {get pending(){return pending;},get writes(){return writes;},set permission(v){permission=v;},getPending:async()=>({notifications:pending}),getDeliveredNotifications:async()=>({notifications:delivered}),removeDeliveredNotifications:async()=>{delivered=[];},checkPermissions:async()=>({display:permission}),cancel:async({notifications})=>{pending=pending.filter(n=>!notifications.some(x=>x.id===n.id));},schedule:async({notifications})=>{writes++;pending.push(...notifications);}};}
test('timer opt-in / notification privacy / pause, completion and expiration produce no notification',()=>{const n=timerNotice(input);assert.equal(n.id,TIMER_NOTIFICATION_ID);assert.equal(n.isExactNotification,false);assert.equal(n.extra.userId,'A');assert.equal(n.body.includes('test'),false);for(const s of [{...session,alertsEnabled:false},{...session,status:'completed'},{...session,timer:{status:'paused',endsAt:20000}}])assert.equal(timerNotice({...input,session:s}),null);assert.equal(timerNotice({...input,now:20001}),null);});
test('scheduler deduplicates, cancels pause/signout and preserves Planning',async()=>{const a=adapter(),s=createTimerScheduler(a);await s.sync(input);await s.sync(input);assert.equal(a.writes,1);await s.sync({...input,session:{...session,timer:{status:'paused'}}});assert.equal(a.pending.length,1);await s.sync(input);a.permission='denied';assert.equal((await s.sync(input)).state,'permission');assert.equal(a.pending.length,1);a.permission='granted';await s.sync(input);await s.clear();assert.deepEqual(a.pending.map(n=>n.id),[1700000000]);});
test('signout in-flight invalidates a schedule before another owner can see it',async()=>{const a=adapter();let release;const native=a.schedule;a.schedule=async args=>{await new Promise(r=>{release=r;});await native(args);};const s=createTimerScheduler(a),run=s.sync(input);while(!release)await new Promise(r=>setImmediate(r));const clear=s.clear();release();assert.equal((await run).state,'superseded');await clear;assert.equal(a.pending.length,1);});
test('timer persists an absolute deadline, pause survives reload, manual finish does not validate step',()=>{const idea=outfitDirections({analysis:{colors:['#713650','#d1a0ab'],ambience:'Douce'}})[0].idea;let s=newTutorial(idea,'test');s=updateTutorial(s,{type:'start'},1000);for(let i=0;i<2;i++)s=updateTutorial(s,{type:'complete'},1000);s=updateTutorial(s,{type:'timerStart',seconds:60},1000);assert.equal(timerRemaining(s.timer,31000),30000);s=readTutorials({getItem:()=>JSON.stringify({sessions:[s],activeId:s.id})}).sessions[0];s=updateTutorial(s,{type:'timerPause'},31000);assert.equal(timerRemaining(s.timer,99000),30000);s=updateTutorial(s,{type:'timerResume'},100000);assert.equal(s.timer.endsAt,130000);const completed=[...s.completed];s=updateTutorial(s,{type:'timerFinish'},100001);assert.equal(s.timer.remainingMs,0);assert.deepEqual(s.completed,completed);assert.equal(s.status,'active');});
test('manufacturer protocols require exact product/range/reference/lamp/layer, not watts or user claim',()=>{const p={version:1,id:'test-only',kind:'curing',brand:'Test',range:'Range',productType:'Gel',reference:'REF',title:'Fixture, not product advice',sourceUrl:'https://manufacturer.example/protocol',verifiedOn:'2026-10-04',seconds:60,lampModels:['Model A'],layer:'color'};assert.equal(validManufacturerProtocol(p),true);const product={brand:'Test',range:'Range',type:'Gel',reference:'REF',protocol:{seconds:30,verified:true}};assert.equal(manufacturerProtocols(product,'curing').length,0);assert.equal(documentedCuring(product,'Model A','color',[p]).length,1);assert.equal(documentedCuring(product,'48W','color',[p]).length,0);assert.equal(documentedCuring({...product,reference:'OTHER'},'Model A','color',[p]).length,0);assert.equal(validManufacturerProtocol({...p,sourceUrl:'javascript:alert(1)'}),false);assert.equal(validManufacturerProtocol({...p,seconds:0}),false);});
