import React,{useEffect,useRef,useState} from 'react';
import Sheet from '../Sheet';
import {messageId} from '../social/messageState';
import {useStorage} from '../StorageContext';
import {useSocial} from '../social/SocialContext';
import Feedback from '../Feedback';
import {LegalLinks} from '../privacy/PrivacyPanel';
import {BlockedAccounts} from './SafetyActions';
import {APP_VERSION,readDiagnostics} from './diagnostics';
import {supportCall,supportError,ticketPayload,ticketStatus} from './service';
import './support.css';

const FAQ=[['Ma photo reste-t-elle privée ?','Oui, par défaut. Public rend la copie publiée visible aux comptes autorisés. Repasser en privé bloque les nouvelles lectures. Les notes ne sont pas publiées.'],['Pourquoi mon vernis est-il « à vérifier » ?','Une couleur proche ou un numéro seul ne suffit pas à identifier un produit. Confirme la marque, la gamme et la référence sur le flacon.'],['Comment envoyer une inspiration à ma PO ?','Ouvre Envoyer à ma PO, choisis une PO parmi tes connexions acceptées, vérifie l’aperçu puis confirme. Notes et photos ne sont jointes que si tu les sélectionnes.'],['Une sauvegarde a échoué','Garde ton brouillon, retrouve une connexion puis utilise Réessayer. Ne vide pas les données du navigateur avant la synchronisation.'],['Comment retrouver mes données ou supprimer mon compte ?','Dans Profil → Confidentialité, utilise l’export ou la suppression du compte. Un espace Institut partagé demande d’abord un transfert de propriété.']];
export default function SupportPanel({screen='help',onClose}){
 const s=useSocial(),storage=useStorage(),client=s?.client,userId=s?.userId;
 const [tab,setTab]=useState('help'),[feedback,setFeedback]=useState(false),[staff,setStaff]=useState(null),[editor,setEditor]=useState(null);
 useEffect(()=>{let active=true;if(client&&userId)supportCall(client,'status').then(r=>{if(!active)return;const enabled=r.staff===true;setStaff(enabled);if(enabled)setTab(current=>current==='help'?'queue':current);}).catch(()=>{if(active)setStaff(false);});else setStaff(false);fetch(import.meta.env.BASE_URL+'legal/editor.json').then(r=>r.ok?r.json():null).then(r=>{if(active)setEditor(r);}).catch(()=>{});return()=>{active=false;};},[client,userId]);
 return <React.Fragment>
  <Sheet title="Aide & Support" eyebrow="ON T’ACCOMPAGNE" onClose={onClose}>
   <div className="supportPanel">
    <nav className="supportTabs" aria-label="Aide et support">{[['help','Aide'],['new','Contacter le support'],...(userId?[['list','Mes demandes'],['blocked','Comptes bloqués']]:[]),...(staff===true?[['queue','Boîte staff']]:[])].map(([v,l])=><button key={v} aria-pressed={tab===v} onClick={()=>setTab(v)}>{l}</button>)}</nav>
    {staff===null&&userId&&<small role="status">Vérification des droits support…</small>}
    {tab==='help'&&<><p>Une question ou un problème ? Retrouve les réponses et le suivi de tes demandes ici.</p>{FAQ.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}{editor?.supportContactEmail&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(editor.supportContactEmail)?<a href={'mailto:'+editor.supportContactEmail}>Contacter NailMoods par email</a>:<p>Pour contacter NailMoods, utilise « Contacter le support ». L’adresse email de support n’est pas encore publiée.</p>}<button onClick={()=>setFeedback(true)}>Donner mon avis / exporter un retour</button><LegalLinks/><small>NailMoods {APP_VERSION} · {import.meta.env.VITE_DEPLOYMENT_ENV==='production'?'Production':'Recette'}</small></>}
    {tab==='new'&&(userId?<NewTicket client={client} userId={userId} screen={screen} storage={storage} onSent={()=>setTab('list')}/>:<><p>Connecte-toi avec une adresse confirmée pour envoyer et suivre une demande. Sans compte, tu peux préparer un retour à transmettre.</p><button onClick={()=>setFeedback(true)}>Préparer mon retour</button></>)}
    {['list','queue'].includes(tab)&&<TicketList key={tab} client={client} staff={tab==='queue'}/>} {tab==='blocked'&&<BlockedAccounts client={client} onChange={s.refresh}/>}
   </div>
  </Sheet>
  {feedback&&<Feedback screen={screen} onClose={()=>setFeedback(false)}/>}
 </React.Fragment>;
}
function NewTicket({client,userId,screen,storage,onSent}){
 const [category,setCategory]=useState('bug'),[description,setDescription]=useState(''),[include,setInclude]=useState(false),[file,setFile]=useState(null),[preview,setPreview]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const attempt=useRef(null),[diagnostics]=useState(()=>readDiagnostics(storage));
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 async function submit(e){e.preventDefault();setBusy(true);setNotice('');try{
  const key=JSON.stringify({category,description,include,file:file?[file.name,file.size,file.lastModified]:null});if(attempt.current?.key!==key)attempt.current={key,id:messageId(),attachment:null};
  const a=attempt.current;
  if(file&&!a.attachment){const {data:workspace,error:we}=await client.from('workspaces').select('id').eq('owner_user_id',userId).eq('kind','personal').limit(1).single();if(we)throw we;
   const ext={'image/png':'png','image/jpeg':'jpeg','image/webp':'webp'}[file.type];const path=userId+'/'+workspace.id+'/support/'+a.id+'.'+ext;
   const {error}=await client.storage.from('nailmoods-private').upload(path,file,{contentType:file.type,upsert:true});if(error)throw error;a.attachment=path;
  }
  const r=await supportCall(client,'submit',ticketPayload({id:a.id,category,description,screen,diagnostics:include?diagnostics:[],attachment:a.attachment},import.meta.env.VITE_DEPLOYMENT_ENV,navigator.userAgent));
  setNotice('Demande reçue · '+r.id);setDescription('');setFile(null);attempt.current=null;
 }catch(e){setNotice(supportError(e));}finally{setBusy(false);}}
 return <form className="supportPanel" onSubmit={submit}><label>Catégorie<select disabled={busy} value={category} onChange={e=>setCategory(e.target.value)}>{[['bug','Bug'],['product','Référence produit'],['color','Couleur'],['idea','Inspiration'],['interface','Interface'],['account','Compte'],['suggestion','Suggestion'],['other','Autre']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Que s’est-il passé ?<textarea disabled={busy} minLength={5} maxLength={4000} required rows={5} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Les étapes, le résultat obtenu et ce que tu attendais…"/></label><p>La version, l’environnement, la plateforme et l’écran sont joints. Aucun contenu de ton journal, message ou collection n’est ajouté automatiquement.</p><label className="supportCheck"><input type="checkbox" disabled={busy} checked={include} onChange={e=>setInclude(e.target.checked)}/>Joindre les événements techniques affichés ci-dessous</label><details><summary>Voir les informations techniques proposées ({diagnostics.length})</summary><pre>{JSON.stringify(diagnostics,null,2)}</pre></details><label>Capture facultative · JPEG, PNG ou WebP · 2 Mo maximum<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>2*1024*1024){setNotice('Choisis une image JPEG, PNG ou WebP de 2 Mo maximum.');e.target.value='';return;}setFile(f);}}/></label>{preview&&<><img className="supportPreview" src={preview} alt="Capture que tu choisis de joindre"/><button type="button" disabled={busy} onClick={()=>setFile(null)}>Retirer la capture</button></>}<small>Vérifie la capture et masque les informations que tu ne souhaites pas transmettre à l’équipe support.</small>{notice&&<p role="status">{notice}</p>}<button className="supportPrimary" disabled={busy||description.trim().length<5}>{busy?'Envoi…':'Envoyer au support'}</button><button type="button" onClick={onSent}>Voir mes demandes</button></form>;
}
export function TicketList({client,staff,showRefresh=true}){
 const [page,setPage]=useState(0),[data,setData]=useState({items:[],hasMore:false}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [filters,setFilters]=useState({kind:'',status:'',priority:''});
 async function load(){setBusy(true);setError('');try{setData(await supportCall(client,staff?'queue':'list',{offset:page*20,...(staff?filters:{})}));}catch{setData({items:[],hasMore:false});setError('Demandes indisponibles. Réessaie.');}finally{setBusy(false);}}
 useEffect(()=>{load();},[client,page,staff,filters.kind,filters.status,filters.priority]);
 function updateFilter(name,value){setPage(0);setFilters(current=>({...current,[name]:value}));}
 return <div className="supportPanel">{staff&&<><p className="supportQueueIntro"><b>Boîte staff</b> · demandes support et signalements reçus.</p><div className="staffFilters" aria-label="Filtres de la boîte staff"><label>Type<select value={filters.kind} onChange={e=>updateFilter('kind',e.target.value)}><option value="">Tous les dossiers</option><option value="support">Support</option><option value="report">Modération</option></select></label><label>État<select value={filters.status} onChange={e=>updateFilter('status',e.target.value)}><option value="">Tous les états</option>{Object.entries(ticketStatus).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Priorité<select value={filters.priority} onChange={e=>updateFilter('priority',e.target.value)}><option value="">Toutes priorités</option>{[['low','Basse'],['normal','Normale'],['high','Élevée'],['urgent','Urgente']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div></>}{showRefresh&&<button disabled={busy} onClick={load}>Actualiser</button>}{error&&<p role="alert">Demandes indisponibles. Réessaie.</p>}{busy&&<p role="status">Chargement…</p>}{!busy&&!data.items.length&&<p>{staff?'Aucune demande ni signalement avec ces filtres.':'Aucune demande pour le moment.'}</p>}{data.items.map(t=><Ticket key={t.id} ticket={t} staff={staff} client={client} refresh={load}/>)}<div className="supportTabs"><button disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>Précédent</button><span>Page {page+1}</span><button disabled={!data.hasMore||busy} onClick={()=>setPage(p=>p+1)}>Suivant</button></div></div>;
}
function Ticket({ticket:t,staff,client,refresh}){
 const [reply,setReply]=useState(t.reply),[status,setStatus]=useState(t.status),[priority,setPriority]=useState(t.priority||'normal'),[internalNote,setInternalNote]=useState(''),[history,setHistory]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[image,setImage]=useState('');
 useEffect(()=>()=>{if(image)URL.revokeObjectURL(image);},[image]);
 async function loadHistory(){try{setHistory(await supportCall(client,'history',{kind:t.kind,id:t.id}));}catch{setError('Historique indisponible.');}}
 async function save(){setBusy(true);setError('');setNotice('');try{await supportCall(client,'review',{id:t.id,kind:t.kind,status,priority,reply,internalNote});setInternalNote('');await loadHistory();await refresh();setNotice('Traitement enregistré.');}catch{setError('Mise à jour non enregistrée.');}finally{setBusy(false);}}
 async function withdraw(){if(!window.confirm('Retirer ce contenu de toutes les surfaces publiques ?'))return;setBusy(true);setError('');setNotice('');try{await supportCall(client,'withdrawPublic',{id:t.id});await loadHistory();await refresh();setNotice('Contenu retiré des surfaces publiques.');}catch{setError('Le contenu n’a pas pu être retiré.');}finally{setBusy(false);}}
 async function restrictAccount(){const action=t.target_suspended?'restore':'suspend';const question=action==='suspend'?'Suspendre ce compte ? La personne ne pourra plus utiliser NailMoods jusqu’à réactivation.':'Réactiver ce compte ?';if(!window.confirm(question))return;setBusy(true);setError('');setNotice('');try{await supportCall(client,'accountRestriction',{id:t.id,action});await loadHistory();await refresh();setNotice(action==='suspend'?'Compte suspendu.':'Compte réactivé.');}catch{setError(action==='suspend'?'Le compte n’a pas pu être suspendu.':'Le compte n’a pas pu être réactivé.');}finally{setBusy(false);}}
 return <article className="supportCard"><b>{t.kind==='report'?'Signalement':'Support'} · {ticketStatus[t.status]}</b><small style={{display:'block'}}>Dossier {t.id} · {new Date(t.created_at).toLocaleDateString('fr-FR')}</small><p>{t.description||t.category}</p>{t.reply&&<p><b>Réponse NailMoods :</b> {t.reply}</p>}{t.attachment&&<button onClick={async()=>{try{const r=await client.storage.from('nailmoods-private').download(t.attachment);if(r.error)throw r.error;setImage(URL.createObjectURL(r.data));}catch{setError('Capture indisponible.');}}}>Voir la capture jointe</button>}{image&&<img src={image} className="supportPreview" alt="Capture jointe volontairement"/>}{staff&&<><small>Catégorie : {t.category} · Écran : {t.screen}{t.assigned_to_me?' · Assigné à moi':''}</small>{t.evidence&&<p><b>Élément signalé :</b> {t.evidence}</p>}<details><summary>Événements joints</summary><pre>{JSON.stringify(t.diagnostics,null,2)}</pre></details><label>État<select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(ticketStatus).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Priorité<select value={priority} onChange={e=>setPriority(e.target.value)}>{[['low','Basse'],['normal','Normale'],['high','Élevée'],['urgent','Urgente']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Réponse visible par l’autrice<textarea value={reply} maxLength={2000} onChange={e=>setReply(e.target.value)}/></label><label>Note interne <small>Non visible par l’autrice.</small><textarea value={internalNote} maxLength={2000} onChange={e=>setInternalNote(e.target.value)} placeholder="Décision, action ou information utile…"/></label>{t.kind==='report'&&['journal','inspiration','profile'].includes(t.screen)&&<button type="button" className="supportDanger" disabled={busy} onClick={withdraw}>{t.screen==='profile'?'Retirer le profil de Découvrir':'Retirer le contenu public'}</button>}{t.kind==='report'&&<button type="button" className="supportDanger" disabled={busy} onClick={restrictAccount}>{t.target_suspended?'Réactiver ce compte':'Suspendre ce compte'}</button>}<details onToggle={e=>{if(e.currentTarget.open&&!history)loadHistory();}}><summary>Historique de traitement</summary>{history===null?<p>Ouvre pour charger l’historique.</p>:!history.length?<p>Aucune décision enregistrée.</p>:<ol className="supportHistory">{history.map((h,i)=><li key={i}><b>{ticketStatus[h.to_status]}</b> · {h.priority} · {new Date(h.at).toLocaleString('fr-FR')} · {h.operator}{h.note&&<><br/>{h.note}</>}</li>)}</ol>}</details><button className="supportPrimary" disabled={busy} onClick={save}>{busy?'Enregistrement…':'Enregistrer le traitement'}</button></>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}</article>;
}
