import React, { useEffect, useState } from 'react';
import Sheet from '../Sheet';
import { identityService } from './service';
import { suggestHandle, normalizeHandle, handleError, rankProfiles } from './handles';
const labels={plus:'Plus',pro:'PO indépendante',institute:'Institut',creator:'Créateur / Marque'};
export default function IdentityPanel({client,userId,onSaved}){
 const [loaded,setLoaded]=useState(false),[handle,setHandle]=useState(''),[name,setName]=useState(''),[visibility,setVisibility]=useState('pros');
 const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[panel,setPanel]=useState(null),[query,setQuery]=useState(''),[kind,setKind]=useState(''),[city,setCity]=useState(''),[results,setResults]=useState([]);
 useEffect(()=>{let cancelled=false;setLoaded(false);setResults([]);if(!userId)return;
 identityService(client).mine().then(value=>{if(cancelled)return;setName(value.display_name||'');setHandle(value.username||suggestHandle(value.display_name));setVisibility(value.discovery_visibility);setLoaded(true);}).catch(()=>{if(!cancelled)setNotice('Ton identité publique n’est pas encore disponible. Ta collection et tes idées restent accessibles.');});
 return ()=>{cancelled=true;};},[client,userId]);
 if(!userId)return null;
 async function check(){setBusy(true);setNotice('');try{const error=handleError(handle);if(error){setNotice(error);return;}const available=await identityService(client).available(handle);setNotice(available?'Cet identifiant est disponible. Valide pour l’enregistrer.':'Cet identifiant est déjà utilisé. Essaie une variante, par exemple '+normalizeHandle(handle).slice(0,28)+'2.');}catch{setNotice('Impossible de vérifier maintenant. Réessaie.');}finally{setBusy(false);}}
 async function save(){setBusy(true);setNotice('');try{await identityService(client).save(handle,visibility,name);setHandle(normalizeHandle(handle));setNotice('Ton identité est enregistrée. Tes liens et messages restent liés à ton compte.');onSaved?.();}catch{setNotice('Enregistrement impossible. Cet identifiant a peut-être été choisi entre-temps. Vérifie sa disponibilité puis réessaie.');}finally{setBusy(false);}}
 async function search(e){e.preventDefault();setBusy(true);setNotice('');setResults([]);try{setResults(rankProfiles(await identityService(client).search(query,kind,city),query));}catch{setNotice('La recherche n’est pas disponible. Réessaie.');}finally{setBusy(false);}}
 return <section className="card privacySection"><h2>Mon NailMoods ID</h2><p>Ton nom public est distinct de tes informations privées.</p>{loaded&&<><label>Nom affiché<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><label>@NailMoodsID<input value={handle} maxLength={31} autoCapitalize="none" autoCorrect="off" onChange={e=>setHandle(e.target.value)}/></label><button disabled={busy} onClick={check}>Vérifier la disponibilité</button><label>Qui peut me trouver avec mon NailMoods ID ?<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="everyone">Tout le monde sur NailMoods</option><option value="pros">Uniquement les Pros</option><option value="nobody">Personne</option></select></label><button disabled={busy||!name.trim()||Boolean(handleError(handle))} onClick={save}>Enregistrer mon identité</button><p>Tu peux compléter cette étape plus tard. Ta collection et ton journal restent privés, quel que soit ton choix.</p></>}
 <button onClick={()=>{setPanel('search');setResults([]);setNotice('');}}>Rechercher sur NailMoods</button>{!panel&&notice&&<p role="status">{notice}</p>}
 {panel&&<Sheet title="Rechercher sur NailMoods" onClose={()=>setPanel(null)} className="privacySheet"><form onSubmit={search}><label>Nom ou @NailMoodsID<input value={query} minLength={2} maxLength={80} required onChange={e=>setQuery(e.target.value)}/></label><label>Type de profil<select value={kind} onChange={e=>{setKind(e.target.value);setResults([]);}}><option value="">Tous les profils visibles</option><option value="pro">PO indépendante</option><option value="institute">Institut</option><option value="creator">Créateur / Marque</option></select></label><label>Ville publique (facultatif)<input value={city} maxLength={80} onChange={e=>setCity(e.target.value)}/></label><button disabled={busy||query.trim().length<2}>{busy?'Recherche…':'Rechercher'}</button></form>
 {!busy&&!results.length&&<p>Aucun profil à afficher. Lance une recherche ou essaie un autre nom.</p>}
 {results.map(row=><article key={row.entity_type+row.entity_id} className="card"><h3>{row.display_name}</h3><p>@{row.handle} · {labels[row.kind]||row.kind}</p>{row.city&&<p>{row.city}</p>}{row.bio&&<p>{row.bio}</p>}{row.styles?.length>0&&<p>{row.styles.join(' · ')}</p>}</article>)}{notice&&<p role="status">{notice}</p>}
 </Sheet>}
 </section>;
}
