import ProDirectory from '../professional/ProDirectory.jsx';
import {proV2Enabled} from '../professional/service.js';
import React,{useState} from 'react';
import {Search,ChevronRight,SlidersHorizontal} from 'lucide-react';
import {identityService} from './service';
import {rankProfiles} from './handles';
import {professionalLabel} from '../workspaces/professionalProfile';
import PublicProfile from './PublicProfile';
import ContentImage from '../social/ContentImage';
export default function PeopleSearch({client,initialKind='',compact=false,children,onSearched}) {
 const [query,setQuery]=useState(''),[kind,setKind]=useState(initialKind),[city,setCity]=useState(''),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[searched,setSearched]=useState(false),[error,setError]=useState(''),[handle,setHandle]=useState(null);
 async function search(event){event.preventDefault();if(busy)return;setBusy(true);setError('');try{setRows(rankProfiles(await identityService(client).search(query,kind,city),query));setSearched(true);onSearched?.(true);}catch{setError('Recherche indisponible. Tes critères sont conservés ; réessaie.');}finally{setBusy(false);}}
 return <>{!compact&&proV2Enabled()&&<ProDirectory client={client}/>}<form className={'identitySearchForm '+(compact?'nmFilPeopleSearch':'')} onSubmit={search}><label>Nom ou @NailMoodsID<input type="search" minLength={2} maxLength={80} required value={query} onChange={e=>setQuery(e.target.value)} placeholder={compact?'Un nom ou un @pseudo':'ex. @studio.marie'}/></label><details className="nmDisclosure"><summary aria-label={compact?'Filtres des personnes':undefined}>{compact?<SlidersHorizontal size={20}/>:null}<span className={compact?'srOnly':''}>Type de profil et ville</span></summary><label>Type de profil<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">Tous les profils visibles</option><option value="independent">PO indépendante</option><option value="institute_owner">Propriétaire d’institut</option><option value="institute_associate">Collaboratrice d’institut</option><option value="institute">Institut</option><option value="creator">Créateur / Marque</option><option value="plus">Compte Plus</option></select></label><label>Ville publique · facultative<input value={city} maxLength={80} onChange={e=>setCity(e.target.value)}/></label></details><button className="detailPrimary" disabled={busy||query.trim().length<2}><Search/><span className={compact?'srOnly':''}>{busy?'Recherche…':'Rechercher une personne'}</span></button></form>{children}{error&&<p role="alert">{error}</p>}{!busy&&!error&&!rows.length&&<div className="searchEmpty"><b>{searched?'Aucun profil trouvé':'Trouve ta PO ou une personne'}</b><p>{searched?'Vérifie le nom, l’identifiant ou élargis les filtres.':'Seuls les profils qui ont choisi d’être trouvables apparaissent. Ouvre un profil pour inviter la personne à se connecter.'}</p>{searched&&<button onClick={()=>{setKind('');setCity('');setSearched(false);onSearched?.(false);}}>Réinitialiser les filtres</button>}</div>}<div className="identityResults">{rows.map(row=><button className="identityResultCard" key={row.entity_type+row.entity_id} onClick={()=>setHandle(row.handle)}><span className="resultAvatar"><span aria-hidden="true">{(row.display_name||'N')[0]}</span>{row.avatar_url&&<ContentImage client={client} kind="avatar" id={row.handle} title="Avatar public"/>}</span><span><b>{row.display_name}</b><small>@{row.handle}</small><small>{professionalLabel(row.kind)}{row.city?' · '+row.city:''}</small></span><ChevronRight/></button>)}</div>{handle&&<PublicProfile client={client} handle={handle} onClose={()=>setHandle(null)}/>}</>;
}
