import {SafetyActions} from '../support/SafetyActions';
import ContentImage from '../social/ContentImage';
import {ConnectionAction} from '../social/SocialHub';
import React,{useEffect,useState} from 'react';
import Sheet from '../Sheet';
import {professionalLabel} from '../workspaces/professionalProfile';
export default function PublicProfile({client,handle,onClose}){
 const [profile,setProfile]=useState(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;setProfile(null);setError('');client.rpc('get_public_profile',{p_handle:handle}).then(({data,error})=>{if(!active)return;if(error||!data)setError('Ce profil n’est pas public ou n’est plus disponible.');else setProfile(data);});return()=>{active=false;};},[client,handle,revision]);
 const image=(kind,id)=>`${client.supabaseUrl}/functions/v1/media-read?kind=${kind}&id=${encodeURIComponent(id)}`;
 return <Sheet title="Profil public" onClose={onClose} className="publicProfileSheet"><button className="quietButton refreshProfile" onClick={()=>setRevision(v=>v+1)}>Actualiser le profil</button>{error&&<p role="status">{error}</p>}{!error&&!profile&&<p>Chargement…</p>}{profile&&<section className="publicProfile"><div className="publicProfileIntro">{profile.avatarHandle&&<ContentImage key={revision} client={client} kind="avatar" id={profile.avatarHandle} title="Avatar public"/>}<div><span className="profileTypePill">{professionalLabel(profile.accountType)}</span><h2>{profile.displayName}</h2><p>@{profile.handle}</p></div></div>{profile.bio&&<p>{profile.bio}</p>}{profile.city&&<p className="publicCity">{profile.city}</p>}<ConnectionAction client={client} handle={handle}/><SafetyActions client={client} target={{kind:"profile",handle}} onBlocked={onClose}/><h3>{profile.accountType==='plus'?'Poses publiques':'Portfolio · poses publiques'}</h3>{!profile.journal?.length&&<p>Aucune pose publique pour le moment.</p>}{profile.journal?.map(entry=><article className="publicContentCard" key={entry.id}><h4>{entry.title||'Ma pose'}</h4><ContentImage client={client} kind="journal" id={entry.mediaId} title={entry.title||"Pose publique"} preview={entry.preview}/><p>{entry.performedOn} {entry.mood}</p></article>)}<h3>Inspirations publiques</h3>{!profile.inspirations?.length&&<p>Aucune inspiration publique pour le moment.</p>}{profile.inspirations?.map(entry=><article className="publicContentCard" key={entry.id}><h4>{entry.title}</h4><ContentImage client={client} kind="inspiration" id={entry.mediaId} title={entry.title||"Inspiration"} preview={entry.snapshot}/></article>)}</section>}</Sheet>;
}
