import React,{useEffect,useState} from 'react';
import Sheet from '../Sheet';
import {professionalLabel} from '../workspaces/professionalProfile';
export default function PublicProfile({client,handle,onClose}){
 const [profile,setProfile]=useState(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;setProfile(null);setError('');client.rpc('get_public_profile',{p_handle:handle}).then(({data,error})=>{if(!active)return;if(error||!data)setError('Ce profil n’est pas public ou n’est plus disponible.');else setProfile(data);});return()=>{active=false;};},[client,handle,revision]);
 const image=(kind,id)=>`${client.supabaseUrl}/functions/v1/media-read?kind=${kind}&id=${encodeURIComponent(id)}`;
 return <Sheet title="Profil public" onClose={onClose} className="publicProfileSheet"><button className="quietButton refreshProfile" onClick={()=>setRevision(v=>v+1)}>Actualiser le profil</button>{error&&<p role="status">{error}</p>}{!error&&!profile&&<p>Chargement…</p>}{profile&&<section className="publicProfile"><div className="publicProfileIntro">{profile.avatarHandle&&<img key={revision} src={image('avatar',profile.avatarHandle)} alt="Avatar public" onError={e=>{e.currentTarget.hidden=true;}}/>}<div><span className="profileTypePill">{professionalLabel(profile.accountType)}</span><h2>{profile.displayName}</h2><p>@{profile.handle}</p></div></div>{profile.bio&&<p>{profile.bio}</p>}{profile.city&&<p className="publicCity">{profile.city}</p>}<h3>Poses publiques</h3>{!profile.journal?.length&&<p>Aucune pose publique pour le moment.</p>}{profile.journal?.map(entry=><article className="publicContentCard" key={entry.id}><h4>{entry.title||'Ma pose'}</h4><img src={image('journal',entry.mediaId)} alt={entry.title||'Pose publique'} loading="lazy" onError={e=>{e.currentTarget.hidden=true;}}/><p>{entry.performedOn} {entry.mood}</p></article>)}<h3>Inspirations publiques</h3>{!profile.inspirations?.length&&<p>Aucune inspiration publique pour le moment.</p>}{profile.inspirations?.map(entry=><article className="publicContentCard" key={entry.id}><h4>{entry.title}</h4><img src={image('inspiration',entry.mediaId)} alt={entry.title||'Inspiration'} loading="lazy" onError={e=>{e.currentTarget.hidden=true;}}/></article>)}</section>}</Sheet>;
}
