import {UniverseTiles,PreferenceTiles} from '../design/ProfileModules';
import '../design/profile-experience.css';
import {Skeleton} from '../design/UI';
import {readPublicProfile} from './publicProfile.js';
import MoodGlyph from '../MoodGlyph';
import {preferenceFields} from '../design/onboarding.js';
import {SafetyActions} from '../support/SafetyActions';
import ContentImage from '../social/ContentImage';
import {ConnectionAction} from '../social/SocialHub';
import React,{useEffect,useState} from 'react';
import Sheet from '../Sheet';
import {professionalLabel} from '../workspaces/professionalProfile';
export default function PublicProfile({client,handle,onClose}){
 const [profile,setProfile]=useState(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;setProfile(null);setError('');readPublicProfile(client,handle).then(({data,error})=>{if(!active)return;if(error||!data)setError('Ce profil n’est pas public ou n’est plus disponible.');else setProfile(data);});return()=>{active=false;};},[client,handle,revision]);
 const image=(kind,id)=>`${client.supabaseUrl}/functions/v1/media-read?kind=${kind}&id=${encodeURIComponent(id)}`;
 return <Sheet title="Profil public" onClose={onClose} className="publicProfileSheet"><button className="quietButton refreshProfile" onClick={()=>setRevision(v=>v+1)}>Actualiser le profil</button>{error&&<p role="status">{error}</p>}{!error&&!profile&&<Skeleton label="Ouverture du profil…"/>}{profile&&<section className="publicProfile"><div className="publicProfileIntro">{!profile.avatarHandle&&<span className="nmPublicInitial" aria-hidden="true">{(profile.displayName||'N')[0]}</span>}{profile.avatarHandle&&<ContentImage key={revision} client={client} kind="avatar" id={profile.avatarHandle} title="Avatar public"/>}<div><span className="profileTypePill">{professionalLabel(profile.accountType)}</span><h2>{profile.displayName}</h2><p>@{profile.handle}</p></div></div>{(profile.personalBio||profile.bio)&&<p>{profile.personalBio||profile.bio}</p>}{profile.universes?.length>0&&<section className="nmBento"><h3>Mes univers</h3><UniverseTiles values={profile.universes}/></section>}{profile.preferences&&<section className="nmBento"><h3>Mes préférences</h3><PreferenceTiles profile={profile.preferences} onlyPresent/></section>}{profile.styles?.length>0&&<section className="nmBento"><h3>Mes styles</h3><div className="favoriteStyles">{profile.styles.map(v=><span className="nmMoodChip" key={v}><MoodGlyph value={v}/>{v}</span>)}</div></section>}{profile.city&&<p className="publicCity">{profile.city}</p>}<ConnectionAction client={client} handle={handle}/><details className="conversationMenu"><summary>Options du profil</summary><SafetyActions client={client} target={{kind:"profile",handle,label:'@'+profile.handle}} onBlocked={onClose}/></details><h3>{profile.accountType==='plus'?'Poses publiques':'Portfolio · poses publiques'}</h3>{!profile.journal?.length&&<p>Aucune pose publique pour le moment.</p>}{profile.journal?.map(entry=><article className="publicContentCard" key={entry.id}><h4>{entry.title||'Ma pose'}</h4><ContentImage client={client} kind="journal" id={entry.mediaId} title={entry.title||"Pose publique"} preview={entry.preview}/><p>{entry.performedOn} {entry.mood}</p><SafetyActions client={client} target={{kind:'journal',id:entry.id,label:entry.title||'Ma pose'}}/></article>)}<h3>Inspirations publiques</h3>{!profile.inspirations?.length&&<p>Aucune inspiration publique pour le moment.</p>}{profile.inspirations?.map(entry=><article className="publicContentCard" key={entry.id}><h4>{entry.title}</h4><ContentImage client={client} kind="inspiration" id={entry.mediaId} title={entry.title||"Inspiration"} preview={entry.snapshot}/><SafetyActions client={client} target={{kind:'inspiration',id:entry.id,label:entry.title||'Inspiration'}}/></article>)}</section>}</Sheet>;
}
