import React,{useState} from 'react';
import {TECH_FIELDS} from '../catalogue/model';
import {safeSource} from './model';
import {Check,HelpCircle,TriangleAlert,BookOpen} from 'lucide-react';
import {lifestyle} from '../lifestyle/model';
import {manufacturerProtocols} from '../poseCycle/protocols';
import {productColor} from '../colorAnalysis';
import {productDocument,inciFor,ingredientReport,recordIngredients,documentedCompatibility,productAlternatives} from './model';
import './products.css';
function Source({record}){return record?.sourceUrl?<a href={record.sourceUrl} target="_blank" rel="noopener noreferrer">Source documentée{(record.checkedAt||record.verifiedOn)?' · consultée le '+(record.checkedAt||record.verifiedOn):''}</a>:null;}
export default function ProductKnowledge({product,items,profile,onChange,onProfile}){const [otherId,setOtherId]=useState(''),[lamp,setLamp]=useState('');const doc=productDocument(product),inci=inciFor(product),watch=lifestyle(profile?.lifestyle).watch,report=ingredientReport(inci?.text,watch),hits=report.filter(r=>r.watched.length),alternatives=productAlternatives(product,items),protocols=manufacturerProtocols(product,'curing'),selected=protocols.filter(p=>p.lampModels.includes(lamp)),other=items.find(p=>String(p.id)===otherId),compat=other?documentedCompatibility(product,other):null;
 const update=patch=>onChange({ingredientRecord:recordIngredients(product,patch)});
 return <section className="productKnowledge" aria-label="Informations produit"><div className="knowledgeHeading"><BookOpen size={21}/><div><small>MA FICHE, EN DÉTAIL</small><h2>Bien connaître mon produit</h2><p className="knowledgeIdentity">{[product.brand,product.name,product.collection].filter(Boolean).join(' · ')}</p></div></div>
 <details className="knowledgeBlock"><summary>Ingrédients & mes repères {hits.length?`· ${hits.length} mention${hits.length>1?'s':''}`:''}</summary><p>Ta liste de surveillance reste personnelle.</p>{inci?<><p className="knowledgeSource">{inci.label}</p><p>{hits.length?`${hits.length} mention(s) de ta liste repérée(s).`:watch.length?'Aucune correspondance exacte avec ta liste. Cela ne prouve pas l’absence de risque.':'Ajoute tes ingrédients à surveiller depuis ton profil.'}</p><ul className="inciList">{report.map((r,i)=><li key={i}>{r.watched.length?<mark><span aria-hidden="true">● </span>{r.name}<small>Dans ma liste : {r.watched.join(', ')}</small></mark>:r.name}</li>)}</ul>{!inci.personal&&<Source record={inci}/>}<p>Les formules peuvent évoluer. Vérifie la liste sur ton propre flacon.</p></>:<p>Liste INCI non disponible pour cette référence. Aucune conclusion sur sa composition.</p>}
 <button type="button" className="outline" onClick={onProfile}>Modifier mes ingrédients à surveiller</button><details className="knowledgeEdit"><summary>Transcrire la liste de mon flacon</summary><p>Recopie uniquement une liste INCI réelle. Cette saisie privée ne devient pas une donnée fabricant vérifiée.</p><label>Origine de la liste<select value={product.ingredientRecord?.source||''} onChange={e=>update({source:e.target.value})}><option value="">Choisir</option><option value="label">Étiquette de mon flacon</option><option value="manufacturer">Fiche fabricant</option></select></label><label>Liste INCI de mon produit<textarea rows={5} maxLength={12000} value={product.ingredientRecord?.text||''} onChange={e=>update({text:e.target.value})}/></label><label>Lien fabricant (facultatif)<input type="url" value={product.ingredientRecord?.sourceUrl||''} onChange={e=>update({sourceUrl:e.target.value})}/></label><button type="button" className="outline" onClick={()=>onChange({ingredientRecord:null})}>Effacer ma transcription</button></details></details>
 <details className="knowledgeBlock"><summary>Teintes proches dans ma Collection</summary><label>Opacité<select value={product.opacity||product.coverage||''} onChange={e=>onChange({opacity:e.target.value})}><option value="">Non renseignée</option>{(product.opacity||product.coverage)&&!['Opaque','Semi-opaque','Translucide','Transparent'].includes(product.opacity||product.coverage)&&<option>{product.opacity||product.coverage}</option>}{['Opaque','Semi-opaque','Translucide','Transparent'].map(v=><option key={v}>{v}</option>)}</select></label>{doc?.opacity&&<p>Couvrance publiée par le fabricant : {doc.opacity}. <Source record={doc}/></p>}<p>{alternatives.reason}</p>{alternatives.unknown.map(x=><p key={x}>{x}</p>)}<div className="knowledgeAlternatives">{alternatives.matches.map(p=><div key={p.id}><div className="neutralSwatch"><i style={{background:productColor(p)}}/></div><span><b>{p.name}</b><small>{[p.brand,p.finish,p.opacity||p.coverage].filter(Boolean).join(' · ')}</small><small>{alternatives.state==='owned'?'Référence exacte':'Teinte proche · pas une compatibilité chimique'}</small></span></div>)}</div><p>Comparaison de couleur, finition, opacité et famille de produit. Aucun « dupe exact » déduit d’une couleur.</p></details>
 <details className="knowledgeBlock"><summary>Compatibilité des systèmes</summary><label>Comparer avec un produit<select value={otherId} onChange={e=>setOtherId(e.target.value)}><option value="">Choisir dans ma Collection</option>{items.filter(p=>p.id!==product.id&&p.type!=='Matériel').map(p=><option value={p.id} key={p.id}>{p.brand} · {p.name} · {p.collection}</option>)}</select></label>{compat?<div className="compatibility" data-state={compat.state}>{compat.state==='documented'?<Check/>:compat.state==='incompatible'?<TriangleAlert/>:<HelpCircle/>}<div><b>{compat.label}</b><p>{compat.summary}</p><Source record={compat}/></div></div>:<p>Choisis deux références pour consulter les informations documentées.</p>}<p>Une information fabricant sur un système ne garantit pas la sécurité de toute combinaison.</p></details>
 {TECH_FIELDS.filter(([k])=>k!=='inci'&&product.catalogTechnical?.[k]?.value&&safeSource(product.catalogTechnical[k].sourceUrl)).map(([k,l])=><details className="knowledgeBlock" key={k}><summary>{l} · catalogue</summary><p>{product.catalogTechnical[k].value}</p><Source record={product.catalogTechnical[k]}/><p>Cette information concerne la référence et le protocole cités. Elle ne confirme pas automatiquement une combinaison avec un autre produit ou une autre lampe.</p></details>)}<details className="knowledgeBlock"><summary>Catalysation & notice fabricant</summary>{protocols.length?<><label>Mon modèle exact de lampe<select value={lamp} onChange={e=>setLamp(e.target.value)}><option value="">Choisir · aucune durée par défaut</option>{[...new Set(protocols.flatMap(p=>p.lampModels))].map(l=><option key={l}>{l}</option>)}<option value="other">Autre modèle / je ne sais pas</option></select></label>{selected.length?selected.map(p=><article key={p.id}><b>{p.seconds} s · {p.title}</b><p>{p.instructions}</p><Source record={p}/></article>):<p>Consulte les recommandations du fabricant de ton produit pour ton modèle exact de lampe.</p>}</>:<p>Consulte les recommandations du fabricant de ton produit. Aucune durée documentée pour cette référence.</p>}<p>Aucun temps n’est calculé à partir de la puissance en watts.</p></details></section>;
}
