import {takePoseShareLink} from './shareLinks.js';
import {useEffect,useRef} from 'react';
import {useSocial} from '../social/SocialContext';import {useStorage} from '../StorageContext';
import {poseRepository} from './repository.js';import {takeProjectLink} from './projectLinks.js';
import {clearPlanningNotifications,invalidatePlanningNotifications,syncPlanningNotifications,nativePlanning} from './notifications.js';
export default function PlanningRuntime({preferences}){const social=useSocial(),storage=useStorage(),local=useRef({userId:null,previous:null,overrides:{}});useEffect(()=>{
 let active=true,running=false,again=false;const uid=social?.userId;if(local.current.userId!==uid)local.current={userId:uid,previous:null,overrides:{}};if(local.current.previous){for(const key of ['pose','follow_up','maintenance','removal','project'])if((preferences?.[key]!==false)!==(local.current.previous[key]!==false))local.current.overrides[key]=preferences?.[key]!==false;}local.current.previous=preferences||{};
 const route=()=>{const share=takePoseShareLink(uid);if(share){location.hash='partage/'+share;return;}const id=takeProjectLink(uid);if(id)location.hash='creer/pose/'+id;};route();window.addEventListener('nm-project-link',route);window.addEventListener('nm-pose-share-link',route);
 const sync=async()=>{if(!active||document.visibilityState==='hidden')return;if(running){again=true;return;}if(!uid){await clearPlanningNotifications().catch(()=>{});return;}if(!nativePlanning()||!storage.workspaceId)return;running=true;try{const repo=poseRepository(social.client,{userId:uid,workspaceId:storage.workspaceId});const [plans,reminders,settings]=await Promise.all([repo.list('plan'),repo.list('reminders'),social.client.from('profiles').select('preferences').eq('id',uid).single()]);if(settings.error)throw settings.error;if(active){const remote=settings.data.preferences?.nailmoodsProfile?.planningNotifications||{};for(const [key,value] of Object.entries(local.current.overrides))if((remote[key]!==false)===value)delete local.current.overrides[key];const result=await syncPlanningNotifications({userId:uid,plans,reminders,preferences:{...remote,...local.current.overrides}});window.dispatchEvent(new CustomEvent('nm-planning-status',{detail:result}));}}catch{if(active)window.dispatchEvent(new CustomEvent('nm-planning-status',{detail:{state:'error'}}));}finally{running=false;if(again&&active){again=false;void sync();}}};
 void clearPlanningNotifications().then(()=>{if(active)void sync();}).catch(()=>{});const trigger=()=>{void sync();};window.addEventListener('nm-planning-changed',trigger);window.addEventListener('nm-native-state',trigger);window.addEventListener('online',trigger);document.addEventListener('visibilitychange',trigger);const interval=setInterval(trigger,60000);
 return()=>{active=false;invalidatePlanningNotifications();clearInterval(interval);window.removeEventListener('nm-project-link',route);window.removeEventListener('nm-pose-share-link',route);window.removeEventListener('nm-planning-changed',trigger);window.removeEventListener('nm-native-state',trigger);window.removeEventListener('online',trigger);document.removeEventListener('visibilitychange',trigger);};
 },[social?.client,social?.userId,storage.workspaceId,preferences]);return null;}
