import React,{useMemo,useState,useEffect,useRef} from 'react';
import {ArrowLeft,CalendarDays,Clock3,Bell,Plus,ChevronRight,Trash2,Check} from 'lucide-react';
import {Button} from '../design/UI';import {useSocial} from '../social/SocialContext';import {useStorage} from '../StorageContext';
import {poseRepository} from './repository.js';import {newProject,newReminder,planningGroups} from './model.js';
import {PLAN_LABELS,CATEGORY_LABELS,categoryFor,deviceZone,wallTime,planFromForm,reminderTime} from './planning.js';
import {exportCalendar} from './calendarExport.js';import {nativePlanning,requestPlanningNotifications,clearPlanningNotifications} from './notifications.js';import {track} from '../analytics/analytics';
import MonthCalendar from './MonthCalendar';
import {todayDate,dayAppointments} from './month';
import './planning.css';
const dateLabel=p=>new Date(p.scheduled_on+'T12:00:00Z').toLocaleDateString('fr-FR',{timeZone:'UTC',weekday:'short',day:'numeric',month:'long'});
export default function PlanningView({profile,onChange,route}){
 const social=useSocial(),storage=useStorage();const principal=useMemo(()=>social?.userId&&storage.workspaceId?{userId:social.userId,workspaceId:storage.workspaceId}:null,[social?.userId,storage.workspaceId]);
 const repo=useMemo(()=>principal?poseRepository(social.client,principal):null,[principal,social?.client]);
 const [data,setData]=useState({projects:[],plan:[],reminders:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [form,setForm]=useState(null),[edit,setEdit]=useState(null),[filter,setFilter]=useState('upcoming'),[calendar,setCalendar]=useState(null),[details,setDetails]=useState(false),[settings,setSettings]=useState(false),[reminderForm,setReminderForm]=useState(null);
 const [month,setMonth]=useState(()=>todayDate().slice(0,7)),[day,setDay]=useState(todayDate);
 const [newTitle,setNewTitle]=useState('');const selected=route.split('/')[2],preset=route.split('/')[3],opened=useRef(null);const preferences=profile.planningNotifications||{};
 async function load(){if(!repo){setLoading(false);return;}const [projects,plan,reminders]=await Promise.all([repo.list('projects'),repo.list('plan'),repo.list('reminders')]);setData({projects,plan,reminders});setLoading(false);}
 useEffect(()=>{let active=true;setLoading(true);if(!repo){setLoading(false);return;}Promise.all([repo.list('projects'),repo.list('plan'),repo.list('reminders')]).then(([projects,plan,reminders])=>{if(active){setData({projects,plan,reminders});setLoading(false);}}).catch(e=>{if(active){setError(e.message);setLoading(false);}});return()=>{active=false;};},[repo,route]);
 useEffect(()=>{const status=e=>{if(e.detail.state==='error')setNotice('Le Planning est conservé. La synchronisation des notifications sur ce téléphone reste à reprendre.');else if(e.detail.state==='scheduled')setNotice(`${e.detail.count} rappel(s) programmé(s) sur ce téléphone.`);else if(e.detail.state==='permission')setNotice('Les rappels sont enregistrés ; autorise les notifications pour les recevoir sur ce téléphone.');};window.addEventListener('nm-planning-status',status);return()=>window.removeEventListener('nm-planning-status',status);},[]);
 async function action(job){setBusy(true);setError('');try{await job();await clearPlanningNotifications();await load();window.dispatchEvent(new Event('nm-planning-changed'));}catch(e){setError(e.message||'L’action n’a pas abouti. Réessaie.');}finally{setBusy(false);}}
 function openForm(p=null,date=day){setEdit(p);setForm(p?{project_id:p.project_id,title:p.title,kind:p.kind,date:p.scheduled_on,time:p.starts_at?wallTime(p.starts_at,p.timezone).slice(11):'',duration:p.ends_at?(Date.parse(p.ends_at)-Date.parse(p.starts_at))/60000:60,timezone:p.timezone,location:p.location,notes:p.notes}:{project_id:selected||data.projects[0]?.id||'',title:'Ma prochaine pose',kind:'pose',date,time:'',duration:60,timezone:deviceZone(),location:'',notes:''});setError('');requestAnimationFrame(()=>document.querySelector('.planningEditForm')?.scrollIntoView({behavior:'smooth',block:'start'}));}
 useEffect(()=>{if(!loading&&selected&&data.projects.some(p=>p.id===selected)&&['follow_up','maintenance','removal'].includes(preset)&&opened.current!==route){opened.current=route;openForm();setForm(f=>({...f,kind:preset,title:PLAN_LABELS[preset]+' · '+data.projects.find(p=>p.id===selected).title}));}},[loading,selected,preset,route,data.projects]);
 function field(key,value){setForm({...form,[key]:value});}
 async function submit(e){e.preventDefault();await action(async()=>{const project=data.projects.find(p=>p.id===form.project_id);if(!project)throw Error('Choisis un projet.');const row=planFromForm(project,form,edit);await (edit?repo.save('plan',row):repo.create('plan',row));if(!edit)track('planning_created',{kind:row.kind},{screen:'planning'});setForm(null);setNotice('Ton moment est enregistré. Tu peux maintenant choisir un rappel.');});}
 async function saveReminder(e){e.preventDefault();await action(async()=>{const p=data.plan.find(p=>p.id===reminderForm.planId);const at=reminderTime(reminderForm.date,reminderForm.time,p.timezone);if(reminderForm.row)await repo.save('reminders',{...reminderForm.row,scheduled_at:at});else await repo.create('reminders',newReminder(p,{at,category:categoryFor(p.kind)}));track('reminder_created',{category:categoryFor(p.kind)},{screen:'planning'});setReminderForm(null);setNotice(nativePlanning()?'Rappel enregistré. Vérification de la programmation sur ce téléphone…':'Rappel enregistré. Pour le recevoir hors de l’app, utilise NailMoods sur téléphone et autorise les notifications.');});}
 const visible=selected?data.plan.filter(p=>p.project_id===selected):data.plan;const groups=planningGroups(visible);const sections=filter==='upcoming'?[['À reprogrammer',groups.overdue],['Cette semaine',groups.thisWeek],['Plus tard',groups.later]]:[['Tous mes moments',[...visible].sort((a,b)=>a.scheduled_on.localeCompare(b.scheduled_on))]];
 function card(p){const reminders=data.reminders.filter(r=>r.plan_item_id===p.id);return <article className="planningCard planningAppointment" data-kind={p.kind} key={p.id}><div className="planningDate"><CalendarDays size={24}/><div><strong>{dateLabel(p)}</strong><small>{p.starts_at?wallTime(p.starts_at,p.timezone).slice(11)+' · '+p.timezone:'Toute la journée · '+p.timezone}</small></div></div><small className="planningKind">{PLAN_LABELS[p.kind]} {p.status!=='scheduled'&&'· '+(p.status==='done'?'Terminé':'Annulé')}</small><h3>{p.title}</h3><button className="nmQuiet" onClick={()=>{location.hash='creer/pose/'+p.project_id;}}>Ouvrir le projet <ChevronRight size={16}/></button>{p.location&&<p>{p.location}</p>}<div className="planningActions"><Button type="button" variant="secondary" disabled={busy} onClick={()=>openForm(p)}>Modifier</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>{setCalendar(p);setDetails(false);}}>Ajouter au calendrier</Button></div>{p.status==='scheduled'&&<><div className="planningReminders">{reminders.map(r=><div key={r.id}><span><Bell size={15}/> {new Date(r.scheduled_at).toLocaleString('fr-FR',{timeZone:p.timezone,dateStyle:'short',timeStyle:'short'})} · {Date.parse(r.scheduled_at)<=Date.now()?'Échu':!r.enabled?'Désactivé':preferences[r.category]===false?'Catégorie désactivée':'Activé'}</span><button disabled={busy} onClick={()=>action(()=>{if(!r.enabled&&Date.parse(r.scheduled_at)<=Date.now())throw Error('Choisis une date future avant de réactiver ce rappel.');return repo.save('reminders',{...r,enabled:!r.enabled});})}>{r.enabled?'Désactiver':'Activer'}</button><button disabled={busy} onClick={()=>setReminderForm({planId:p.id,row:r,date:wallTime(r.scheduled_at,p.timezone).slice(0,10),time:wallTime(r.scheduled_at,p.timezone).slice(11)})}>Changer la date</button><button aria-label="Supprimer ce rappel" disabled={busy} onClick={()=>action(()=>repo.remove('reminders',r))}><Trash2 size={16}/></button></div>)}</div><button className="nmQuiet" disabled={busy} onClick={()=>setReminderForm({planId:p.id,date:p.scheduled_on,time:'09:00'})}><Bell size={16}/> Ajouter un rappel</button></>}
 <details className="planningManage"><summary>Gérer ce moment</summary><p className="planningHint">Terminer un moment ne marque pas automatiquement la pose comme réalisée.</p>{p.status==='scheduled'&&<div className="planningActions"><Button type="button" variant="secondary" disabled={busy} onClick={()=>action(()=>repo.save('plan',{...p,status:'done'}))}><Check size={16}/> Terminer</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>action(()=>repo.save('plan',{...p,status:'canceled'}))}>Annuler ce moment</Button></div>}<Button type="button" variant="ghost" disabled={busy} onClick={()=>action(()=>repo.remove('plan',p))}>Supprimer ce moment et ses rappels</Button></details></article>;}
 return <section className="planningPage"><div className="planningTop"><button className="nmQuiet" onClick={()=>{location.hash=selected?'creer/pose/'+selected:'creer';}}><ArrowLeft size={17}/> {selected?'Mon projet':'Créer'}</button><button className="nmQuiet" onClick={()=>setSettings(!settings)}><Bell size={17}/> Mes rappels</button></div><div className="planningHero"><small>UN PEU DE TEMPS POUR TOI</small><h1>Ton prochain<br/><em>moment NailMoods.</em></h1><p>Prépare, réalise, puis prends soin de tes poses. À ton rythme.</p></div>
 {error&&<p role="alert" className="planningError">{error}</p>}{notice&&<p role="status" className="planningHint">{notice}</p>}
 {settings&&<section className="planningCard"><h2>Les rappels que tu choisis</h2><p className="planningHint">Choix communs à ton profil. Autorisation à activer sur chaque téléphone ; synchronisation à l’ouverture et au retour dans l’app.</p>{Object.entries(CATEGORY_LABELS).map(([id,label])=><label className="planningCheck" key={id}><input type="checkbox" checked={preferences[id]!==false} onChange={e=>onChange({...profile,planningNotifications:{...preferences,[id]:e.target.checked}})}/>{label}</label>)}{nativePlanning()?<Button type="button" onClick={async()=>{try{const p=await requestPlanningNotifications();setNotice(p.display==='granted'?'Notifications autorisées. Synchronisation des rappels…':'Notifications non autorisées. Ton Planning reste disponible.');window.dispatchEvent(new Event('nm-planning-changed'));}catch{setError('Les notifications ne peuvent pas être activées. Vérifie les réglages du téléphone.');}}}>Autoriser sur ce téléphone</Button>:<p>Les notifications hors de l’app nécessitent la version mobile. L’export calendrier fonctionne aussi depuis ce navigateur.</p>}<p className="planningHint">Sur mobile, jusqu’à 60 prochains rappels peuvent être programmés. Android peut les décaler pour économiser la batterie. Une déconnexion les retire de ce téléphone.</p></section>}
 {!repo?<p>Connecte-toi pour retrouver ton Planning personnel.</p>:loading?<p role="status">Ouverture de ton Planning…</p>:<><Button type="button" disabled={busy||!data.projects.length} onClick={()=>openForm()}><Plus size={18}/> Planifier un moment</Button>{!data.projects.length&&<section className="planningCard"><h2>Une envie, une date.</h2><p>Commence par une idée simple ou une inspiration enregistrée.</p><label>Nom du projet<input maxLength={120} value={newTitle} onChange={e=>setNewTitle(e.target.value)}/></label><Button type="button" disabled={busy||!newTitle.trim()} onClick={()=>action(async()=>{await repo.create('projects',newProject({...principal,title:newTitle.trim()}));setNewTitle('');})}>Créer mon projet personnel</Button></section>}
 {form&&<form className="planningCard planningEditForm" onSubmit={submit}><h2>{edit?'Modifier ce moment':'Un moment pour…'}</h2><label>Projet<select aria-label="Projet" value={form.project_id} disabled={Boolean(edit)} onChange={e=>field('project_id',e.target.value)}>{data.projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Type<select aria-label="Type" value={form.kind} onChange={e=>field('kind',e.target.value)}>{Object.entries(PLAN_LABELS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Titre<input required maxLength={120} value={form.title} onChange={e=>field('title',e.target.value)}/></label><div className="planningFields"><label>Date<input required type="date" value={form.date} onChange={e=>field('date',e.target.value)}/></label><label>Heure (facultatif)<input type="time" value={form.time} onChange={e=>field('time',e.target.value)}/></label></div>{form.time&&<label>Durée en minutes<input type="number" min="5" max="1440" value={form.duration} onChange={e=>field('duration',e.target.value)}/></label>}<label>Fuseau horaire<input required value={form.timezone} onChange={e=>field('timezone',e.target.value)}/></label><label>Lieu (facultatif)<input maxLength={240} value={form.location} onChange={e=>field('location',e.target.value)}/></label><label>Note privée<textarea maxLength={2000} value={form.notes} onChange={e=>field('notes',e.target.value)}/></label><div className="planningActions"><Button type="submit" busy={busy}>Enregistrer ce moment</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setForm(null)}>Fermer</Button></div></form>}
 {reminderForm&&<form className="planningCard" onSubmit={saveReminder}><h2>Quand te le rappeler ?</h2><p>Heure dans le fuseau du moment choisi.</p><div className="planningFields"><label>Date du rappel<input required type="date" value={reminderForm.date} onChange={e=>setReminderForm({...reminderForm,date:e.target.value})}/></label><label>Heure du rappel<input required type="time" value={reminderForm.time} onChange={e=>setReminderForm({...reminderForm,time:e.target.value})}/></label></div><Button type="submit" busy={busy}>Enregistrer le rappel</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setReminderForm(null)}>Fermer</Button></form>}
 {calendar&&<section className="planningCard"><h2>Dans ton calendrier</h2><p>{calendar.title} · {dateLabel(calendar)}</p><p className="planningHint">Le titre, le lieu et un lien privé seront copiés dans le calendrier choisi. Ce lien nécessite ton compte NailMoods.</p><label className="planningCheck"><input type="checkbox" checked={details} onChange={e=>setDetails(e.target.checked)}/>Inclure la recette, les produits et ma note privée</label><p className="planningHint">C’est une copie : tes changements dans NailMoods ne modifieront pas automatiquement le calendrier. Vérifie les doublons avant de confirmer.</p><div className="planningActions">{nativePlanning()&&<Button type="button" onClick={async()=>{try{setNotice(await exportCalendar(calendar,data.projects.find(p=>p.id===calendar.project_id),{includeDetails:details}));track('calendar_exported',{format:'native'},{screen:'planning'});}catch(e){setError(e.message+' Tu peux exporter le fichier .ics ci-dessous.');}}}>Ouvrir mon calendrier</Button>}<Button type="button" variant="secondary" onClick={async()=>{try{setNotice(await exportCalendar(calendar,data.projects.find(p=>p.id===calendar.project_id),{includeDetails:details,icsOnly:true}));track('calendar_exported',{format:'ics'},{screen:'planning'});}catch(e){setError(e.message);}}}>Exporter le fichier .ics</Button><Button type="button" variant="ghost" onClick={()=>setCalendar(null)}>Fermer</Button></div></section>}
 <div className="planningTabs"><button aria-pressed={filter==='upcoming'} onClick={()=>setFilter('upcoming')}>À venir</button><button aria-pressed={filter==='month'} onClick={()=>setFilter('month')}>Mois</button><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>Tout</button></div>{!visible.length&&<p className="planningEmpty">Ton Planning attend tes prochains moments ♡</p>}{filter==='month'&&<><MonthCalendar month={month} onMonth={setMonth} day={day} onDay={setDay} items={visible} onAdd={date=>openForm(null,date)} disabled={busy||!data.projects.length}/>{dayAppointments(visible,day).map(card)}</>}{filter!=='month'&&sections.map(([title,rows])=>rows.length>0&&<section key={title}><h2>{title}</h2>{rows.map(card)}</section>)}</>}
 </section>;
}
