import {newPlanItem,validatePlanItem,validateReminder,zonedDate,timezoneValid} from './model.js';
import {validDate} from '../journal.js';
export const PLAN_LABELS={pose:'Réaliser ma pose',event:'Événement',follow_up:'Photo de suivi',maintenance:'Entretien',removal:'Dépose',prepare:'Préparer mon projet',personal:'Moment personnel'};
export const CATEGORY_LABELS={pose:'Avant une pose',follow_up:'Suivi',maintenance:'Entretien',removal:'Dépose',project:'Projets et événements'};
export const categoryFor=kind=>['pose','follow_up','maintenance','removal'].includes(kind)?kind:'project';
export const deviceZone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Paris';
export function wallTime(instant,zone){const p=new Intl.DateTimeFormat('sv-SE',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(instant));const get=k=>p.find(x=>x.type===k).value;return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`;}
// Reject missing/ambiguous DST times rather than silently moving a user's appointment.
export function toInstant(date,time,zone){if(!validDate(date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)||!timezoneValid(zone))throw Error('Choisis une date, une heure et un fuseau valides.');const base=Date.parse(date+'T'+time+':00Z'),matches=[];for(let m=-840;m<=840;m+=15){const instant=new Date(base+m*60000).toISOString();if(wallTime(instant,zone)===date+'T'+time)matches.push(instant);}if(matches.length!==1)throw Error(matches.length?'Cette heure apparaît deux fois lors du changement d’heure. Choisis une autre heure.':'Cette heure n’existe pas dans ce fuseau lors du changement d’heure.');return matches[0];}
export function planFromForm(project,form,existing=null){const start=form.time?toInstant(form.date,form.time,form.timezone):null;const duration=Number(form.duration||60);if(!Number.isInteger(duration)||duration<5||duration>1440)throw Error('Choisis une durée entre 5 et 1 440 minutes.');const row=newPlanItem(project,{title:form.title,kind:form.kind,date:form.date,timezone:form.timezone,startsAt:start,endsAt:start?new Date(Date.parse(start)+duration*60000).toISOString():null,location:form.location||'',notes:form.notes||''});return existing?validatePlanItem({...existing,...row,id:existing.id,revision:existing.revision,status:existing.status}):row;}
export function reminderTime(date,time,zone,now=Date.now()){const instant=toInstant(date,time,zone);if(Date.parse(instant)<=now)throw Error('Choisis un rappel dans le futur.');return instant;}
export function noticeCandidates({userId,plans,reminders,preferences={},now=Date.now(),limit=60}){const byId=new Map(plans.filter(p=>p.user_id===userId&&p.status==='scheduled').map(p=>[p.id,p]));return reminders.filter(r=>r.user_id===userId&&r.enabled&&preferences[r.category]!==false&&Date.parse(r.scheduled_at)>now&&byId.has(r.plan_item_id)).sort((a,b)=>a.scheduled_at.localeCompare(b.scheduled_at)||a.id.localeCompare(b.id)).slice(0,limit).map((r,i)=>{validateReminder(r);return {id:1700000000+i,title:'NailMoods',body:{pose:'Ton moment NailMoods approche ♡',follow_up:'Un moment pour suivre ta pose ♡',maintenance:'Ton rappel d’entretien NailMoods ♡',removal:'Ton rappel de dépose NailMoods ♡',project:'Ton projet NailMoods t’attend ♡'}[r.category],schedule:{at:new Date(r.scheduled_at)},extra:{scope:'pose-planning',userId,projectId:byId.get(r.plan_item_id).project_id,reminderId:r.id},channelId:'nailmoods-planning',isExactNotification:false};});}
export {zonedDate};
