import React,{useEffect,useMemo,useState} from 'react';
import {Camera,Check,CalendarDays,Trash2} from 'lucide-react';
import {Button} from '../design/UI';
import ProductPhoto from '../ProductPhoto';
import {useSocial} from '../social/SocialContext';import {useStorage} from '../StorageContext';
import {localDate,journalDate} from '../journal';
import {dayAge,poseAge,FOLLOW_FEELINGS,FOLLOW_STATES} from './followUp';import {followUpService} from './followUpService';
import './followUp.css';
function PrivatePhoto({reference,service}){const [src,setSrc]=useState(''),[error,setError]=useState(false);useEffect(()=>{let active=true,url;setSrc('');setError(false);service.image(reference).then(value=>{url=value;if(active)setSrc(value);else if(value)URL.revokeObjectURL(value);}).catch(()=>{if(active)setError(true);});return()=>{active=false;if(url)URL.revokeObjectURL(url);};},[reference?.path,service]);return src?<img className="followPhoto" src={src} alt="Photo privée de l’évolution de la pose"/>:error?<p role="status">Photo indisponible. Réouvre la fiche pour réessayer.</p>:<p role="status">Ouverture de la photo…</p>;}
export default function PoseFollowUp({project,onSaved}){
 const social=useSocial(),storage=useStorage();const service=useMemo(()=>followUpService(social.client,{userId:social.userId,workspaceId:storage.workspaceId}),[social.client,social.userId,storage.workspaceId]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[form,setForm]=useState(null),[photo,setPhoto]=useState(''),[photoBusy,setPhotoBusy]=useState(false),[confirm,setConfirm]=useState(null);
 const [date,setDate]=useState(project.details.realizedOn||localDate()),[removed,setRemoved]=useState(project.details.removedOn||'');const age=poseAge(project),d=project.details;
 useEffect(()=>{setDate(project.details.realizedOn||localDate());setRemoved(project.details.removedOn||'');},[project.id,project.details.realizedOn,project.details.removedOn]);
 async function run(task){setBusy(true);setError('');try{const saved=await task();onSaved(saved);setForm(null);setPhoto('');setConfirm(null);window.dispatchEvent(new Event('nm-planning-changed'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 function edit(entry=null){setPhoto('');setForm(entry?{...entry}:{id:crypto.randomUUID(),date:localDate(),note:'',feeling:'',state:'',media:null});}
 return <section className="poseFollowUp"><div className="followHeading"><small>MES ONGLES, AU FIL DES JOURS</small><h2>{d.realizedOn?'L’histoire de ta pose':'Je l’ai faite'}</h2><p>Photos, tenue et ressenti : un suivi personnel, à ton rythme.</p></div>{error&&<p role="alert" className="outfitError">{error} Recharge la fiche si elle a changé sur un autre appareil.</p>}
 {!d.realizedOn?<form className="followSurface" onSubmit={e=>{e.preventDefault();run(()=>service.dates(project,date));}}><label>Date réelle de la pose<input type="date" required max={localDate()} value={date} onChange={e=>setDate(e.target.value)}/></label><Button type="submit" busy={busy}><Check size={17}/> Je l’ai faite</Button><p className="outfitHint">Elle apparaîtra dans Mes poses. Le projet garde sa recette et son Planning.</p></form>:<>
 <div className="followAge"><b>{age}</b><div><strong>{d.removedOn?'jours portée':age===1?'jour depuis ta pose':'jours depuis ta pose'}</strong><small>{d.removedOn?'Déposée le '+journalDate(d.removedOn):'Réalisée le '+journalDate(d.realizedOn)}</small></div><Camera size={28}/></div>
 <div className="followActions"><Button disabled={busy} onClick={()=>edit()}><Camera size={17}/> Ajouter une observation</Button><Button variant="secondary" onClick={()=>{location.hash='creer/planning/'+project.id;}}><CalendarDays size={17}/> Prévoir un suivi ou un entretien</Button></div>
 <p className="outfitHint">Tes photos et notes restent privées, même si une pose du Journal est publique. Les jours sont des repères, sans délai de dépose imposé.</p>
 <details className="followDates"><summary>Dates de réalisation et de dépose</summary><form onSubmit={e=>{e.preventDefault();run(()=>service.dates(project,date,removed||null));}}><label>Date réelle de la pose<input type="date" required max={localDate()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Date réelle de dépose (facultatif)<input type="date" min={date} max={localDate()} value={removed} onChange={e=>setRemoved(e.target.value)}/></label><p className="outfitHint">La date de dépose arrête le compteur. Laisse-la vide tant que tu portes cette pose.</p><Button type="submit" busy={busy} variant="secondary">Enregistrer les dates</Button></form></details>
 {form&&<form className="followSurface" onSubmit={e=>{e.preventDefault();run(()=>service.save(project,form,photo));}}><h3>Un instant de ton suivi</h3><fieldset disabled={busy}><label>Date de l’observation<input type="date" required min={d.realizedOn} max={localDate()} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label>{form.media&&!photo&&<><PrivatePhoto reference={form.media} service={service}/><button type="button" className="nmQuiet" onClick={()=>setForm({...form,media:null})}>Retirer cette photo du suivi</button></>}<ProductPhoto value={photo} onChange={setPhoto} onBusy={setPhotoBusy} alt="Photo à ajouter à mon suivi" cameraLabel="Photographier le suivi de ma pose"/><label>Ce que j’observe<select aria-label="Ce que j’observe" value={form.state} onChange={e=>setForm({...form,state:e.target.value})}><option value="">Facultatif</option>{Object.entries(FOLLOW_STATES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Mon ressenti<select aria-label="Mon ressenti" value={form.feeling} onChange={e=>setForm({...form,feeling:e.target.value})}><option value="">Facultatif</option>{Object.entries(FOLLOW_FEELINGS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Ma note privée<textarea aria-label="Ma note privée" maxLength={2000} rows={3} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></fieldset><Button type="submit" busy={busy} disabled={photoBusy}>Enregistrer l’observation</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setForm(null)}>Fermer</Button></form>}
 <ol className="followTimeline"><li><span className="followDay">J0</span><div><h3>Une nouvelle pose</h3><small>{journalDate(d.realizedOn)}</small></div></li>{[...d.followUp].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)).map(e=><li key={e.id}><span className="followDay">J+{dayAge(d.realizedOn,e.date)}</span><article><small>{journalDate(e.date)}</small>{e.media&&<PrivatePhoto reference={e.media} service={service}/>}<div className="followTags">{e.state&&<span>{FOLLOW_STATES[e.state]}</span>}{e.feeling&&<span>{FOLLOW_FEELINGS[e.feeling]}</span>}</div>{e.note&&<p>{e.note}</p>}<div className="followActions"><button className="nmQuiet" disabled={busy} onClick={()=>edit(e)}>Modifier</button><button className="nmQuiet" disabled={busy} aria-label={'Supprimer l’observation du '+e.date} onClick={()=>setConfirm(e.id)}><Trash2 size={16}/> Supprimer</button></div>{confirm===e.id&&<div role="alert"><p>Retirer cette observation et sa photo privée ?</p><Button variant="outline" busy={busy} onClick={()=>run(()=>service.remove(project,e.id))}>Confirmer la suppression</Button><Button variant="ghost" onClick={()=>setConfirm(null)}>Garder</Button></div>}</article></li>)}{d.removedOn&&<li><span className="followDay">Fin</span><div><h3>Pose déposée</h3><small>{journalDate(d.removedOn)}</small></div></li>}</ol>
 </>}
 </section>;
}
