import React,{useMemo,useState} from 'react';
import {Brush,CalendarDays,Send,Sparkles,Save,Trash2} from 'lucide-react';
import {useSocial} from '../social/SocialContext';import {useStorage} from '../StorageContext';
import {Button} from '../design/UI';import NailPreview from '../NailPreview';import RecipeSummary from '../RecipeSummary';
import {validIdea} from '../inspirations';import {diyColor} from './diy';import {poseRepository} from './repository';import {STATUS_LABELS} from './model';
import {PLAN_LABELS} from './planning';import {exportCalendar} from './calendarExport';import {nativePlanning} from './notifications';
import PoseFollowUp from './PoseFollowUp';import {ProjectShareSheet} from './ProjectShare';
import './projectSheet.css';
export default function PoseProjectSheet({project,onSaved,items,image,plans,onVariant,onDelete}){
 const social=useSocial(),storage=useStorage();const repo=useMemo(()=>poseRepository(social.client,{userId:social.userId,workspaceId:storage.workspaceId}),[social.client,social.userId,storage.workspaceId]);
 const [share,setShare]=useState(false),[title,setTitle]=useState(project.title),[notes,setNotes]=useState(project.details.notes),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[calendar,setCalendar]=useState(''),[include,setInclude]=useState(false),[deleting,setDeleting]=useState(false);
 const idea=validIdea(project.details.composition)?project.details.composition:null,canEdit=!(['outfit','image'].includes(project.details.source)||idea?.intent==='photos')||['plus','pro'].includes(social.tier);
 const upcoming=plans.filter(p=>p.status==='scheduled'),event=upcoming.find(p=>p.id===calendar);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const p=await repo.save('projects',{...project,title:title.trim(),details:{...project.details,notes}});onSaved(p);setNotice('Ton projet est enregistré.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="poseProjectSheet"><div className="outfitHeading"><small>MON PROJET · {STATUS_LABELS[project.status]?.toUpperCase()} · PRIVÉ</small><h1>{project.title}</h1><p>Ton envie prend forme.</p></div>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <section className="poseSheetCard poseProjectHero">{idea?<><div className="poseSheetVisual"><NailPreview idea={idea}/></div><div className="poseSheetFacts"><span><small>Forme</small><b>{idea.shape}</b></span><span><small>Longueur</small><b>{idea.length}</b></span><span><small>Décor</small><b>≈ {idea.minutes} min</b></span></div><div className="posePalette">{idea.palette.filter(p=>!p.unpainted).map(p=><span key={p.id}><i style={{background:diyColor(p)||'transparent'}}/><small>{diyColor(p)?.toUpperCase()||'À préciser'}</small></span>)}</div>{idea.options?.mood&&<p className="poseMoodSignature">{idea.options.mood} · {idea.options?.style||'À ton image'}</p>}</>:<p>Tu peux déjà planifier cette envie. Sa composition reste à préciser.</p>}</section>
 <div className="posePrimaryActions">{idea&&<Button onClick={()=>{location.hash='creer/diy/'+project.id;}}><Brush size={18}/> Je la fais moi-même</Button>}<Button variant="secondary" onClick={()=>{location.hash='creer/planning/'+project.id;}}><CalendarDays size={18}/> Planifier cette pose</Button>{idea&&<Button variant="outline" onClick={()=>setShare(true)}><Send size={18}/>{['plus','pro'].includes(social.tier)?'Envoyer à ma PO':'Partage PO · Plus / Pro'}</Button>}{idea&&<Button variant="ghost" disabled={!canEdit} onClick={()=>onVariant(idea)}><Sparkles size={18}/> Créer une variante</Button>}</div>
 {image&&<section className="poseSheetCard poseOutfitReference"><img src={image} alt="Ma tenue privée à l’origine du projet"/><div><small>MON POINT DE DÉPART</small><h2>Une tenue, une envie.</h2><p>Ta photo reste privée. Tu choisis explicitement de la joindre ou non à une fiche PO.</p></div></section>}
 {idea&&<section className="poseSheetCard"><small>TOUS LES DÉTAILS DE TON IDÉE</small><h2>Ta recette de pose</h2><RecipeSummary idea={idea}/><Button variant="ghost" onClick={()=>{location.hash='creer/diy/'+project.id;}}>Vérifier avec ma Collection</Button></section>}
 <section className="poseSheetCard poseCalendar"><CalendarDays size={24}/><h2>Une place dans ton calendrier</h2>{upcoming.length?<><label>Moment à ajouter<select aria-label="Moment à ajouter au calendrier" value={calendar} onChange={e=>setCalendar(e.target.value)}><option value="">Choisir un moment planifié</option>{upcoming.map(p=><option key={p.id} value={p.id}>{p.title} · {p.scheduled_on} · {PLAN_LABELS[p.kind]}</option>)}</select></label>{event&&<><label className="poseCheck"><input type="checkbox" checked={include} onChange={e=>setInclude(e.target.checked)}/><span>Inclure la recette, les produits et la note de ce rendez-vous</span></label><p className="poseFinePrint">Le titre et le lieu seront copiés dans le calendrier choisi. Le lien vers le projet reste privé. Une modification ultérieure ne met pas cette copie à jour.</p><div className="poseActionRow">{nativePlanning()&&<Button onClick={async()=>{try{setNotice(await exportCalendar(event,project,{includeDetails:include}));}catch(e){setError(e.message);}}}>Ouvrir mon calendrier</Button>}<Button variant="secondary" onClick={async()=>{try{setNotice(await exportCalendar(event,project,{includeDetails:include,icsOnly:true}));}catch(e){setError(e.message);}}}>Exporter le fichier .ics</Button></div></>}</>:<><p>Choisis librement ta date de pose, d’entretien ou ton rendez-vous personnel.</p><Button variant="secondary" onClick={()=>{location.hash='creer/planning/'+project.id;}}>Choisir une date</Button></>}</section>
 <details className="poseSheetCard poseEdit"><summary>Personnaliser ma fiche</summary><form onSubmit={save}><label>Nom du projet<input aria-label="Nom de ma fiche pose" value={title} maxLength={120} disabled={!canEdit||busy} required onChange={e=>setTitle(e.target.value)}/></label><label>Ma note privée<textarea aria-label="Ma note de projet privée" value={notes} maxLength={4000} rows={4} disabled={!canEdit||busy} onChange={e=>setNotes(e.target.value)}/></label><p className="poseFinePrint">Cette note n’est pas partagée automatiquement.</p><Button type="submit" busy={busy} disabled={!canEdit||!title.trim()}><Save size={16}/> Enregistrer ma fiche</Button>{!canEdit&&<p>La modification d’un projet photo ou tenue nécessite Plus ou Pro.</p>}</form></details>
 <PoseFollowUp project={project} onSaved={onSaved}/>
 <details className="poseSheetCard"><summary>Gérer ce projet</summary><p>Supprimer ce projet retire ses rendez-vous, rappels, médias et fiches PO liées. Les autres inspirations restent conservées.</p><Button variant="outline" onClick={()=>setDeleting(true)}><Trash2 size={17}/> Supprimer le projet</Button>{deleting&&<div role="alert"><p>Confirmer la suppression de ce projet et de ses partages ?</p><Button busy={busy} onClick={async()=>{setBusy(true);try{await onDelete(project);}catch(e){setError(e.message);setBusy(false);}}}>Confirmer la suppression</Button><Button variant="ghost" onClick={()=>setDeleting(false)}>Garder le projet</Button></div>}</details>
 {share&&<ProjectShareSheet project={project} onClose={()=>setShare(false)}/>}
 </div>;
}
