import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Capacitor} from '@capacitor/core';
import {Copy,Send,Link,QrCode,Trash2,ArrowLeft} from 'lucide-react';
import {useSocial} from '../social/SocialContext';
import {Button} from '../design/UI';
import Sheet from '../Sheet';
import {RecipientIdentity} from '../social/PoShare';
import {ShareDetails} from '../social/ShareCard';
import {filterRecipients,poShareService} from '../social/poShareService';
import PoseSharedSummary from './PoseSharedSummary';
import {poseShareLink,projectShareService,shareFailure,rememberPoseShare} from './shareLinks';
import {projectIdValid} from './projectLinks';
import './projectSheet.css';
export function ShareLinkTools({id}){
 const canvas=useRef(),[qr,setQr]=useState(false),[notice,setNotice]=useState(''),[qrError,setQrError]=useState('');
 const link=poseShareLink(id,{environment:import.meta.env.VITE_DEPLOYMENT_ENV,native:Capacitor.isNativePlatform(),webBase:location.href});
 useEffect(()=>{let alive=true;if(qr){setQrError('');import('bwip-js/browser').then(m=>{if(alive&&canvas.current)m.default.toCanvas(canvas.current,{bcid:'qrcode',text:link,scale:4,eclevel:'M',padding:4,backgroundcolor:'FFFFFF'});}).catch(()=>{if(alive)setQrError('Le QR n’a pas pu être préparé. Le lien reste disponible.');});}return()=>{alive=false;};},[qr,link]);
 async function share(){try{if(Capacitor.isNativePlatform()){const {Share}=await import('@capacitor/share');await Share.share({title:'Fiche pose NailMoods',text:'Une fiche privée NailMoods, réservée aux participantes autorisées.',url:link});}else if(navigator.share)await navigator.share({title:'Fiche pose NailMoods',url:link});else{await navigator.clipboard.writeText(link);setNotice('Lien copié. Seules les participantes autorisées pourront l’ouvrir.');}}catch(e){setNotice(e.name==='AbortError'?'Partage annulé.':'Partage indisponible. Tu peux copier le lien ci-dessous.');}}
 return <div className="poseLinkTools"><p>Ce lien et ce QR ouvrent uniquement la fiche autorisée. Une connexion NailMoods est nécessaire ; transférer le lien ne donne aucun accès supplémentaire.</p><div className="poseActionRow"><Button variant="secondary" onClick={share}><Send size={17}/> Partager le lien</Button><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(link);setNotice('Lien privé copié.');}catch{setNotice('Copie indisponible : sélectionne le lien ci-dessous.');}}}><Copy size={17}/> Copier</Button><Button variant="outline" onClick={()=>setQr(!qr)}><QrCode size={17}/>{qr?'Masquer le QR':'Afficher le QR'}</Button></div><label>Lien privé<input readOnly aria-label="Lien privé de la fiche" value={link} onFocus={e=>e.target.select()}/></label>{qr&&<div className="poseQR"><canvas ref={canvas} aria-label="QR du lien privé NailMoods" role="img"/>{qrError&&<p role="alert">{qrError}</p>}</div>}{notice&&<p role="status">{notice}</p>}</div>;
}
export function ProjectShareSheet({project,onClose}){
 const social=useSocial(),service=useMemo(()=>projectShareService(social.client),[social.client]);const allowed=['plus','pro'].includes(social.tier);
 const [recipients,setRecipients]=useState([]),[history,setHistory]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[notes,setNotes]=useState(false),[images,setImages]=useState(false),[preview,setPreview]=useState(null),[sent,setSent]=useState(null),[activeLink,setActiveLink]=useState(null),[confirm,setConfirm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const attempt=useRef(crypto.randomUUID());
 useEffect(()=>{let alive=true;Promise.all([allowed?poShareService(social.client).recipients():[],service.list(project.id)]).then(([people,shares])=>{if(alive){setRecipients(people);setHistory(shares);}}).catch(e=>{if(alive)setError(shareFailure(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[service,project.id,allowed,social.client]);
 useEffect(()=>{let alive=true;setPreview(null);setError('');if(selected&&allowed)service.preview(project.id,notes,images).then(p=>{if(alive){setPreview(p);attempt.current=crypto.randomUUID();}}).catch(e=>{if(alive)setError(shareFailure(e));});return()=>{alive=false;};},[selected,service,project.id,notes,images,allowed]);
 async function send(){setBusy(true);setError('');try{const id=await service.send({id:project.id,revision:preview.project_revision,recipient:selected.entity_id,clientId:attempt.current,notes,images});setSent(id);social.refresh?.();}catch(e){setError(shareFailure(e));}finally{setBusy(false);}}
 return <Sheet title="Ma fiche PO" eyebrow="PARTAGE PRIVÉ" className="poseShareSheet" onClose={busy?()=>{}:onClose}><div className="poseShareBody">{error&&<p role="alert">{error}</p>}{loading?<p role="status">Ouverture de tes partages…</p>:sent?<><h2>Ta fiche est envoyée.</h2><p>Elle est disponible dans votre conversation privée. Le projet original et son suivi restent dans ton compte.</p><ShareLinkTools id={sent}/><Button variant="secondary" onClick={()=>{location.hash='partage/'+sent;onClose();}}>Ouvrir la fiche envoyée</Button></>:selected?<><button className="nmQuiet" disabled={busy} onClick={()=>setSelected(null)}><ArrowLeft size={16}/> Changer de PO</button><RecipientIdentity client={social.client} row={selected}/><p>Vérifie exactement ce qui sera envoyé avant de confirmer.</p><label className="poseCheck"><input type="checkbox" checked={notes} disabled={busy} onChange={e=>setNotes(e.target.checked)}/>Joindre ma note de projet (2 000 caractères maximum)</label>{project.details.outfitMedia&&<label className="poseCheck"><input type="checkbox" checked={images} disabled={busy} onChange={e=>setImages(e.target.checked)}/>Joindre ma photo de tenue</label>}<p className="poseFinePrint">Ta Collection complète, les observations et les photos de suivi ne sont jamais jointes.</p>{preview?<PoseSharedSummary client={social.client} snapshot={preview}/>:<p role="status">Préparation de l’aperçu sécurisé…</p>}<Button busy={busy} disabled={!preview} onClick={send}><Send size={17}/> Confirmer et envoyer à cette PO</Button></>:<>
 {allowed?<><h2>À qui confier cette envie ?</h2><p>Choisis parmi tes connexions Pro acceptées.</p><label>Rechercher une PO<input type="search" aria-label="Rechercher une PO connectée" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom ou @NailMoodsID"/></label><div className="poseRecipients">{filterRecipients(recipients,query).map(r=><button key={r.entity_id} onClick={()=>{setError('');setSelected(r);}}><RecipientIdentity client={social.client} row={r}/></button>)}</div>{!recipients.length&&<p>Aucune PO connectée pour le moment. Tu peux créer une connexion depuis ton Profil.</p>}</>:<p>L’envoi à une PO est inclus dans Plus et Pro. Tu peux toujours retirer un partage antérieur ci-dessous.</p>}
 {history.length>0&&<section className="poseShareHistory"><h3>Mes fiches envoyées</h3><p className="poseFinePrint">Chaque envoi garde la version confirmée. Modifier ton projet ne modifie pas une fiche déjà envoyée.</p>{history.map(row=><article key={row.id}><b>{row.display_name||'Ma PO'} {row.handle&&'· @'+row.handle}</b><small>{new Date(row.created_at).toLocaleDateString('fr-FR')} · version {row.revision}</small><div className="poseActionRow"><Button variant="ghost" onClick={()=>setActiveLink(activeLink===row.id?null:row.id)}><Link size={16}/> Lien / QR</Button><Button variant="ghost" onClick={()=>setConfirm(row.id)}><Trash2 size={16}/> Retirer l’accès</Button></div>{activeLink===row.id&&<ShareLinkTools id={row.id}/>} {confirm===row.id&&<div className="poseNote"><p>Le lien et la fiche dans NailMoods deviendront inaccessibles. Une copie déjà faite par la destinataire ne peut pas être effacée à distance.</p><Button busy={busy} onClick={async()=>{setBusy(true);try{await service.revoke(row.id);setHistory(h=>h.filter(s=>s.id!==row.id));setConfirm(null);}catch(e){setError(shareFailure(e));}finally{setBusy(false);}}}>Confirmer le retrait</Button><Button variant="ghost" onClick={()=>setConfirm(null)}>Garder le partage</Button></div>}</article>)}</section>}
 </>}</div></Sheet>;
}
export function SharedPoseView({route}){
 const social=useSocial(),[snapshot,setSnapshot]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const id=route.split('/')[1];
 useEffect(()=>{let active=true,run=0;const load=async()=>{const current=++run;setSnapshot(null);if(!social.client||!social.userId||!projectIdValid(id)){setLoading(false);return;}setLoading(true);try{const s=await projectShareService(social.client).detail(id);if(active&&current===run){setSnapshot(s);setError('');}}catch{if(active&&current===run)setError('Cette fiche est indisponible ou tu n’es pas autorisée à la consulter.');}finally{if(active&&current===run)setLoading(false);}};void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);const timer=setInterval(refresh,60000);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[social.client,social.userId,id]);
 return <div className="posePublicView"><Button variant="ghost" onClick={()=>{location.hash='creer';}}><ArrowLeft size={17}/> NailMoods</Button>{loading?<p role="status">Vérification de l’accès à la fiche…</p>:!social.userId?<section className="poseSheetCard"><h1>Une fiche privée t’attend.</h1><p>Connecte-toi au compte qui a reçu ce partage pour l’ouvrir.</p><Button onClick={()=>{rememberPoseShare(id);location.hash='profil/account';}}>Mon compte</Button></section>:error?<section className="poseSheetCard"><h1>Fiche privée</h1><p role="alert">{error}</p></section>:snapshot?<section className="poseSheetCard"><ShareDetails client={social.client} snapshot={snapshot} id={id}/><p className="poseFinePrint">Version partagée à ta connexion. Le projet personnel, son Planning et son suivi ne sont pas accessibles depuis cette fiche.</p><ShareLinkTools id={id}/></section>:<p>Ce lien n’est pas valide.</p>}</div>;
}
