import React,{useState,useEffect,useRef} from 'react';
export function parseInstituteCode(value){const v=String(value||'').trim();const match=/^nailmoods:institute:(request|invite):([a-z0-9]+)$/i.exec(v);return match?{action:match[1]==='invite'?'accept_invite':'request',data:{[match[1]==='invite'?'token':'code']:match[2]}}:{action:'request',data:{code:v}};}
const messages={rate_limit:'Trop de tentatives. Patiente une minute.',code_unavailable:'Ce code est invalide ou désactivé.',invitation_unavailable:'Cette invitation est expirée, révoquée, déjà utilisée ou destinée à une autre adresse.',workspace_full:'Toutes les places sont occupées.',entitlement_inactive:'L’offre institut est inactive. Les données restent conservées.',manager_required:'Cette action est réservée à une responsable.',already_member:'Tu fais déjà partie de cet institut.'};
export default function InstituteAccess({client,workspaceId=null,manager=false,onChanged}){
 const [input,setInput]=useState(''),[email,setEmail]=useState(''),[state,setState]=useState(null),[shared,setShared]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const canvas=useRef(null);
 async function request(action,data={},id=workspaceId){const {data:result,error}=await client.rpc('nm_institute_access',{p_action:action,p_workspace:id,p_data:data});if(error||result?.error)throw Error(result?.error||error?.message);return result;}
 async function refresh(){if(manager&&workspaceId)setState(await request('state'));}
 useEffect(()=>{if(import.meta.env.VITE_INSTITUTE_ACCESS_ENABLED==='true')void refresh().catch(()=>{});},[workspaceId,manager]);
 useEffect(()=>{let alive=true;if(shared?.qrPayload)import('bwip-js/browser').then(m=>{if(alive&&canvas.current)m.default.toCanvas(canvas.current,{bcid:'qrcode',text:shared.qrPayload,scale:3,padding:4,backgroundcolor:'FFFFFF'});}).catch(()=>{});return()=>{alive=false};},[shared]);
 if(import.meta.env.VITE_INSTITUTE_ACCESS_ENABLED!=='true')return null;
 async function act(action,data={},id=workspaceId){setBusy(true);setNotice('');try{const result=await request(action,data,id);if(result.qrPayload)setShared(result);await refresh();await onChanged?.();setNotice(result.requested?'Demande envoyée. La responsable doit l’approuver.':action==='accept_invite'?'Tu as rejoint l’équipe.':'Enregistré.');}catch(e){setNotice(Object.entries(messages).find(([key])=>e.message?.includes(key))?.[1]||'La demande n’a pas abouti. Réessaie.');}finally{setBusy(false);}}
 async function scan(file){if(!file)return;setBusy(true);try{const {readBarcodesFromImageFile}=await import('zxing-wasm/reader');const results=await readBarcodesFromImageFile(file,{formats:['QRCode']});const found=results.find(r=>r.text?.startsWith('nailmoods:institute:'));if(!found)throw Error();setInput(found.text);setNotice('QR lu. Vérifie puis confirme le rattachement.');}catch{setNotice('QR non reconnu. Tu peux saisir le code.');}finally{setBusy(false);}}
 return <section className="instituteBlock"><h3>{manager?'Codes & demandes':'Rejoindre un institut'}</h3>{!manager?<><label>Code ou contenu du QR<input value={input} onChange={e=>setInput(e.target.value)} autoCapitalize="none" maxLength={150}/></label><label>Scanner un QR<input type="file" accept="image/*" capture="environment" onChange={e=>scan(e.target.files?.[0])}/></label><button disabled={busy||!input.trim()} onClick={()=>{const parsed=parseInstituteCode(input);void act(parsed.action,parsed.data,null);}}>Confirmer</button><p>Le code commun envoie une demande à la responsable. Tes données personnelles restent privées.</p></>:<><p>{state?.used??'—'} / {state?.limit??'—'} places utilisées</p><div className="buttonPair"><button disabled={busy} onClick={()=>act('rotate_code')}>Renouveler le code / QR</button><button disabled={busy||!state?.codeEnabled} onClick={()=>{setShared(null);void act('disable_code');}}>Désactiver le code</button></div><label>Invitation individuelle · adresse e-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoCapitalize="none" maxLength={254}/></label><button disabled={busy||!email.includes('@')} onClick={()=>act('invite_email',{email})}>Préparer l’invitation</button><p>Partage ce QR avec la personne concernée. Il expire après 7 jours et fonctionne uniquement avec son adresse confirmée.</p>{state?.requests?.map(r=><div className="instituteItem" key={r.id}><b>{r.name||'Demande de rattachement'}</b><div className="buttonPair"><button disabled={busy} onClick={()=>act('approve',{id:r.id})}>Accepter</button><button disabled={busy} onClick={()=>act('decline_request',{id:r.id})}>Refuser</button></div></div>)}{state?.invitations?.map(i=><div className="pendingInvite" key={i.id}><span>{i.email}</span><button disabled={busy} onClick={()=>act('revoke_invite',{id:i.id})}>Révoquer</button></div>)}</>}{shared&&<div><canvas ref={canvas} aria-label="QR de rattachement institut" style={{maxWidth:'100%',height:'auto'}}/><p style={{overflowWrap:'anywhere'}}>{shared.code||shared.qrPayload}</p><button onClick={()=>navigator.clipboard?.writeText(shared.qrPayload)}>Copier</button></div>}{notice&&<p role="status">{notice}</p>}</section>;
}
