import React,{useEffect,useMemo,useState} from 'react';
import {Building2,Check,ChevronRight,Eye,Scissors,ShieldCheck,UsersRound} from 'lucide-react';
import Sheet from '../Sheet';
import PublicProfile from '../identity/PublicProfile';
import InstitutePanel from './InstitutePanel';
import WorkspaceAvatar from './WorkspaceAvatar';
import {PROFESSIONAL_STATUSES,professionalStatus} from './professionalProfile';
import {professionalError,professionalService} from './professionalService';
import './professional.css';

const emptyForm={name:'',handle:'',bio:'',city:'',isPublic:false,avatarUrl:null};

export default function ProfessionalProfilePanel({client,userId,tier}){
 const [state,setState]=useState(null),[status,setStatus]=useState(''),[form,setForm]=useState(emptyForm),[createName,setCreateName]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[closeOpen,setCloseOpen]=useState(false),[confirmation,setConfirmation]=useState(''),[previewHandle,setPreviewHandle]=useState('');
 const service=useMemo(()=>userId?professionalService(client,userId):null,[client,userId]);
 async function load(){if(!service)return;const next=await service.state();setState(next);setStatus(professionalStatus(next.status));return next;}
 useEffect(()=>{let active=true;setState(null);setNotice('');if(!service||tier!=='pro')return;service.state().then(next=>{if(active){setState(next);setStatus(professionalStatus(next.status));}}).catch(()=>{if(active)setNotice('Le profil Pro n’est pas accessible pour le moment.');});return()=>{active=false;};},[service,tier]);
 const workspace=state?.workspaces.find(item=>item.owner_user_id===userId&&(status==='institute_owner'?item.kind==='institute':status==='independent'?item.kind==='pro':false));
 useEffect(()=>{if(!workspace){setForm(emptyForm);return;}setForm({name:workspace.profile?.display_name||workspace.name||'',handle:workspace.public_handle||'',bio:workspace.profile?.bio||'',city:workspace.profile?.city||'',isPublic:workspace.profile?.is_public===true,avatarUrl:workspace.profile?.avatar_url||null});},[workspace?.id,state]);
 if(!userId||tier!=='pro')return null;
 async function selectStatus(next){setBusy(true);setNotice('');try{await service.setStatus(next);setStatus(next);await load();setNotice('Ton statut Pro est enregistré.');}catch(error){setNotice(professionalError(error));}finally{setBusy(false);}}
 async function createSpace(){setBusy(true);setNotice('');try{await service.create(status==='institute_owner'?'institute':'pro',createName);setCreateName('');await load();setNotice(status==='institute_owner'?'Ton Institut est créé. Il reste privé tant que tu ne le publies pas.':'Ton espace Pro personnel est créé.');}catch(error){setNotice(professionalError(error));}finally{setBusy(false);}}
 async function saveSpace(event){event.preventDefault();setBusy(true);setNotice('');try{await service.saveWorkspace(workspace.id,form);await load();setNotice('Ton identité Pro est enregistrée.');}catch(error){setNotice(professionalError(error));}finally{setBusy(false);}}
 async function closeInstitute(){setBusy(true);setNotice('');try{await service.close(workspace.id,confirmation);setCloseOpen(false);setConfirmation('');await load();setNotice('L’Institut a été fermé. Ton profil personnel est conservé.');}catch(error){setNotice(professionalError(error));}finally{setBusy(false);}}
 return <section className="card professionalProfile" aria-labelledby="pro-profile-title"><div className="proTitle"><div><small>ESPACE PROFESSIONNEL</small><h2 id="pro-profile-title">Mon profil Pro</h2><p>Choisis la structure qui correspond à ton activité. Ce choix ne remplace jamais les droits réels de chaque espace.</p></div><ShieldCheck aria-hidden="true"/></div>
   <section className="proSection" aria-labelledby="pro-status-title"><h3 id="pro-status-title">Mon statut Pro</h3><p>Quel type de profil Pro êtes-vous ?</p><div className="proStatusGrid">{PROFESSIONAL_STATUSES.map(option=><button type="button" key={option.value} className={status===option.value?'selected':''} aria-pressed={status===option.value} disabled={busy} onClick={()=>selectStatus(option.value)}><span className="statusIcon">{option.value==='institute_owner'?<Building2/>:option.value==='independent'?<Scissors/>:<UsersRound/>}</span><span><b>{option.label}</b><small>{option.description}</small></span>{status===option.value?<Check className="statusCheck"/>:<ChevronRight className="statusArrow"/>}</button>)}</div></section>
   {status&&<section className="proSection" aria-labelledby="pro-space-title"><h3 id="pro-space-title">{status==='institute_owner'?'Mon institut':status==='independent'?'Mon activité indépendante':'Mon espace / Mon institut'}</h3>
     {status==='institute_associate'?<InstitutePanel client={client} userId={userId} mode={status} onChanged={load}/>:workspace?<>
       <form className="proIdentityForm" onSubmit={saveSpace}><div className="formSectionHeading"><span>A</span><div><h4>Mon identité Pro</h4><p>Seules les informations que tu rends publiques apparaissent dans la recherche.</p></div></div>
       <WorkspaceAvatar client={client} userId={userId} workspaceId={workspace.id} path={form.avatarUrl} label={status==='institute_owner'?'Logo ou photo de l’institut':'Photo professionnelle'} onChanged={avatarUrl=>setForm(current=>({...current,avatarUrl}))}/>
       <label><span>{status==='institute_owner'?'Nom de l’institut':'Nom professionnel'}</span><input value={form.name} maxLength={80} required onChange={event=>setForm(current=>({...current,name:event.target.value}))}/></label>
       <label><span>@NailMoodsID professionnel</span><div className="handleField"><i>@</i><input value={form.handle} maxLength={30} autoCapitalize="none" autoCorrect="off" placeholder={status==='institute_owner'?'institut.cassis':'studio.marie'} onChange={event=>setForm(current=>({...current,handle:event.target.value.replace(/^@+/,''),}))}/></div></label>
       <label><span>Bio / présentation</span><textarea value={form.bio} maxLength={320} rows={4} placeholder="Présente ton univers en quelques mots." onChange={event=>setForm(current=>({...current,bio:event.target.value}))}/></label>
       <label><span>Ville <small>facultative</small></span><input value={form.city} maxLength={80} placeholder="Visible uniquement si le profil est public" onChange={event=>setForm(current=>({...current,city:event.target.value}))}/></label>
       <label className="visibilityToggle"><input type="checkbox" checked={form.isPublic} onChange={event=>setForm(current=>({...current,isPublic:event.target.checked}))}/><span><b>Profil public</b><small>Nom, ID, bio, ville et contenus publiés pourront être vus. Ta collection et ton journal privé restent invisibles.</small></span></label>
       <button className="primaryAction" disabled={busy||!form.name.trim()}>{busy?'Enregistrement…':'Enregistrer mon identité Pro'}</button>
       {workspace.profile?.is_public&&workspace.public_handle&&<button className="secondaryAction proPreviewButton" type="button" onClick={()=>setPreviewHandle(workspace.public_handle)}><Eye/>Voir mon profil comme les autres</button>}</form>
       {status==='institute_owner'&&<><div className="formSectionHeading"><span>B</span><div><h4>Mon espace Institut</h4><p>Les memberships et les rôles définissent les droits réels.</p></div></div><InstitutePanel client={client} userId={userId} mode={status} onChanged={load}/><button className="dangerText closeInstitute" type="button" onClick={()=>setCloseOpen(true)}>Fermer cet Institut</button></>}
       {status==='independent'&&<div className="independentNote"><Scissors/><span><b>Tu exerces en indépendante.</b><small>Aucun espace Institut ni aucune gestion d’équipe ne t’est imposé.</small></span></div>}
     </>:<div className="createProSpace"><p>{status==='institute_owner'?'Crée ton espace Institut pour inviter ton équipe et définir les rôles.':'Crée un espace Pro personnel pour séparer ton activité de ton espace NailMoods personnel.'}</p><label><span>{status==='institute_owner'?'Nom de l’institut':'Nom professionnel'}</span><input value={createName} maxLength={80} placeholder={status==='institute_owner'?'Institut Cassis':'Studio Marie'} onChange={event=>setCreateName(event.target.value)}/></label><button className="primaryAction" type="button" disabled={busy||createName.trim().length<2} onClick={createSpace}>{status==='institute_owner'?'Créer mon institut':'Créer mon espace Pro'}</button></div>}
   </section>}
   {notice&&<p className="proNotice" role="status">{notice}</p>}
   {closeOpen&&workspace&&<Sheet title="Fermer cet Institut ?" eyebrow="ACTION SENSIBLE" className="privacySheet closeInstituteSheet" onClose={()=>{if(!busy){setCloseOpen(false);setConfirmation('');}}}><p>Les membres perdront l’accès à cet espace. Ton profil personnel sera conservé.</p><label><span>Recopie « {workspace.name} » pour confirmer</span><input value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><button className="dangerAction" disabled={busy||confirmation!==workspace.name} onClick={closeInstitute}>Fermer définitivement l’Institut</button><button className="quietButton" disabled={busy} onClick={()=>{setCloseOpen(false);setConfirmation('');}}>Annuler</button></Sheet>}
   {previewHandle&&<PublicProfile client={client} handle={previewHandle} onClose={()=>setPreviewHandle('')}/>}
 </section>;
}
