import React,{useMemo,useRef,useState} from 'react';
import {Brush,Check,ChevronLeft,Copy,Delete,Eraser,Redo2,Undo2} from 'lucide-react';
import {addStroke,editableProNailDesign,normaliseProNailDesign,PRO_FINGERS,PRO_NAIL_LENGTHS,PRO_NAIL_SHAPES,updateDesignNail} from './proNailEditorModel.js';
import ProDesignPreview,{ProNailArtwork} from './ProNailArtwork';
const fallbackColors=['#f4d8d0','#813c60','#c99073','#d7ae58','#718d82','#6279ad','#ffffff','#252326'];
function colorsFrom(roles,collection){
 const source=[...(collection||[]).map(item=>({color:item.hex,label:item.shade_name||'Ma collection'})),...(roles||[]).map(item=>({color:item.color,label:item.role})),...fallbackColors.map(color=>({color,label:'Couleur NailMoods'}))];
 const colors=new Map();for(const item of source)if(/^#[0-9a-f]{6}$/i.test(item.color||'')&&!colors.has(item.color.toLowerCase()))colors.set(item.color.toLowerCase(),{...item,color:item.color.toLowerCase()});return [...colors.values()].slice(0,24);
}
export default function ProNailEditor({design,colorRoles,collectionColors,defaultShape,defaultLength,onSave,onClose}){
 const initial=useMemo(()=>editableProNailDesign(design,{shape:defaultShape,length:defaultLength,base:colorRoles?.find(item=>item.role==='base')?.color}),[]);
 const [history,setHistory]=useState([initial]),[cursor,setCursor]=useState(0),[tool,setTool]=useState('brush'),[color,setColor]=useState(colorRoles?.find(item=>item.role==='principale')?.color||'#813c60'),[size,setSize]=useState(4),[active,setActive]=useState(null),[selected,setSelected]=useState(initial.focalFinger),[view,setView]=useState('single');
 const svg=useRef(null),surface=useRef(null),strokeRef=useRef(null);
 const current=history[cursor],nail=current.nails[selected],palette=colorsFrom(colorRoles,collectionColors);
 function commit(next){const clean=normaliseProNailDesign(next);setHistory(value=>[...value.slice(0,cursor+1),clean].slice(-31));setCursor(value=>Math.min(value+1,30));}
 function location(event){const matrix=surface.current?.getScreenCTM();if(!matrix||!svg.current)return null;const p=svg.current.createSVGPoint();p.x=event.clientX;p.y=event.clientY;const local=p.matrixTransform(matrix.inverse());return {x:Math.max(0,Math.min(100,local.x)),y:Math.max(0,Math.min(160,local.y))};}
 function begin(event){if(event.pointerType==='mouse'&&event.button!==0||strokeRef.current)return;const p=location(event);if(!p)return;event.currentTarget.setPointerCapture?.(event.pointerId);strokeRef.current={pointerId:event.pointerId,points:[p],color:tool==='erase'?nail.base:color,size:tool==='erase'?Math.max(10,size*2):size,mode:tool==='erase'?'erase':'draw'};setActive(strokeRef.current);}
 function move(event){const stroke=strokeRef.current;if(!stroke||stroke.pointerId!==event.pointerId)return;const p=location(event);if(!p)return;const points=stroke.points.length>=240?stroke.points.filter((_,index)=>index%2===0):stroke.points;strokeRef.current={...stroke,points:[...points,p]};setActive(strokeRef.current);}
 function finish(event){const stroke=strokeRef.current;if(!stroke||stroke.pointerId!==event.pointerId)return;commit(addStroke(current,stroke,selected));strokeRef.current=null;setActive(null);}
 function cancel(){strokeRef.current=null;setActive(null);}
 function selectFinger(index){setSelected(index);setView('single');}
 function copyAll(){commit({...current,scope:'set',nails:current.nails.map(()=>structuredClone(nail))});}
 const preview=active?addStroke(current,active,selected):current;
 return <section className="proNailEditor" aria-label="Éditeur de nail art">
  <header className="proEditorHeader"><button type="button" className="round" onClick={onClose} aria-label="Retour à la création"><ChevronLeft/></button><div><small>ÉDITEUR PRO</small><h3>{view==='set'?'Ma composition':PRO_FINGERS[selected]}</h3></div><button type="button" className="editorSave" onClick={()=>onSave(normaliseProNailDesign(current))}><Check/>Valider</button></header>
  <p className="proEditorIntro">Dessine sur chaque ongle et vérifie l’ensemble en vue de dessus. Valide ensuite pour enregistrer ta création.</p>
  <div className="proEditorGeometry"><label><span>Forme de l’ongle</span><select aria-label="Forme de l’ongle" value={current.shape} onChange={event=>commit({...current,shape:event.target.value})}>{PRO_NAIL_SHAPES.map(value=><option key={value}>{value}</option>)}</select></label><label><span>Longueur de l’ongle</span><select aria-label="Longueur de l’ongle" value={current.length} onChange={event=>commit({...current,length:event.target.value})}>{PRO_NAIL_LENGTHS.map(value=><option key={value}>{value}</option>)}</select></label></div>
  <div className="proEditorViews" aria-label="Vue du dessin"><button type="button" aria-pressed={view==='single'} onClick={()=>setView('single')}>Un ongle</button><button type="button" aria-pressed={view==='set'} onClick={()=>setView('set')}>5 ongles · Vue de dessus</button></div>
  {view==='set'?<><ProDesignPreview design={preview} onSelect={selectFinger} selectedIndex={selected}/><p className="proEditorIntro">Touche un ongle pour le dessiner en détail.</p></>:<><div className="proEditorFingerTabs" aria-label="Ongle à dessiner">{PRO_FINGERS.map((name,index)=><button type="button" key={name} aria-pressed={selected===index} onClick={()=>setSelected(index)}>{name}</button>)}</div><label className="proEditorColorChoice"><span>Base · {PRO_FINGERS[selected]}</span><input type="color" aria-label="Couleur de base du dessin" value={nail.base} onChange={event=>commit(updateDesignNail(current,selected,{base:event.target.value}))}/></label>
  <div className="proEditorCanvas"><svg ref={svg} viewBox="0 0 100 180" role="img" aria-label={`Silhouette d’ongle à dessiner : ${PRO_FINGERS[selected]}`} onPointerDown={begin} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel}><ProNailArtwork surfaceRef={surface} nail={preview.nails[selected]} shape={current.shape} length={current.length}/></svg></div></>}
  <div className="proEditorTools"><div className="proEditorActions"><button type="button" className={tool==='brush'?'selected':''} aria-pressed={tool==='brush'} onClick={()=>{setTool('brush');setView('single');}}><Brush/>Pinceau</button><button type="button" className={tool==='erase'?'selected':''} aria-pressed={tool==='erase'} onClick={()=>{setTool('erase');setView('single');}}><Eraser/>Gomme</button><button type="button" disabled={cursor===0} onClick={()=>setCursor(cursor-1)}><Undo2/>Annuler</button><button type="button" disabled={cursor===history.length-1} onClick={()=>setCursor(cursor+1)}><Redo2/>Rétablir</button><button type="button" className="dangerText" disabled={!nail.strokes.length} onClick={()=>commit(updateDesignNail(current,selected,{strokes:[]}))}><Delete/>Effacer l’ongle</button><button type="button" onClick={copyAll}><Copy/>Sur les 5 ongles</button></div>
   <label className="proEditorSize"><span>Épaisseur</span><input type="range" min="1" max="14" value={size} onChange={event=>setSize(Number(event.target.value))}/><b>{size}</b></label>
   <div className="proEditorPalette"><b>Couleur du pinceau</b><label className="proEditorColorChoice"><span>Autre couleur</span><input type="color" aria-label="Couleur du pinceau personnalisée" value={color} onChange={event=>{setColor(event.target.value);setTool('brush');}}/></label><div>{palette.map(item=><button type="button" key={item.color} title={item.label} aria-label={`${item.label} ${item.color}`} aria-pressed={color.toLowerCase()===item.color} className={color.toLowerCase()===item.color?'selected':''} onClick={()=>{setColor(item.color);setTool('brush');}}><i style={{background:item.color}}/></button>)}</div>{collectionColors?.length>0&&<small>Les premières teintes viennent de ta Collection.</small>}</div>
  </div>
 </section>;
}
