import React,{useState,useEffect} from 'react';import {createRoot} from 'react-dom/client';
import NailPreview from '../src/NailPreview';import MoodGlyph from '../src/MoodGlyph';
import {visualMoods,themeStyle} from '../src/design/themes';
import {snapshotIdea} from '../src/inspirations';import {newProject,newPlanItem,newReminder,projectView,planningGroups,STATUS_LABELS} from '../src/poseCycle/model';
import {poseRepository} from '../src/poseCycle/repository';import {createReviewClient} from './query-client';import './pose-foundations.css';
const userId='10000000-0000-4000-8000-000000000001',workspaceId='20000000-0000-4000-8000-000000000001';
const repo=poseRepository(createReviewClient(q=>fetch('/__pose-foundations',{method:'POST',body:JSON.stringify(q)}).then(r=>r.json()),()=>userId),{userId,workspaceId});
const demoIdea=()=>snapshotIdea({key:'demo',title:'Cassis, tout simplement',shape:'Amande',length:'Courte',palette:[{id:'demo-polish',name:'Cassis de démonstration',type:'Vernis',color:'#713449'}],resources:[],nails:Array.from({length:5},()=>({productId:'demo-polish',color:'#713449'})),minutes:30,rank:0,reasons:['Composition de démonstration'],options:{mood:'Doux'},intent:'inspire'});
function App(){
 const [projects,setProjects]=useState([]),[plan,setPlan]=useState([]),[reminders,setReminders]=useState([]),[mood,setMood]=useState(visualMoods[0]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState('Mon prochain instant NailMoods'),[date,setDate]=useState('2026-10-10'),[reminderAt,setReminderAt]=useState('2026-10-09T18:00:00+02:00');
 const project=projects[0],view=project&&projectView(project),groups=planningGroups(plan,{today:'2026-10-04'});
 async function load(){const [p,a,r]=await Promise.all([repo.list('projects'),repo.list('plan'),repo.list('reminders')]);setProjects(p);if(p[0])setTitle(p[0].title);setPlan(a);setReminders(r);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function action(fn,message){setBusy(true);setError('');setNotice('');try{await fn();await load();setNotice(message);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="reviewShell" style={themeStyle(mood)}><header><img src="/nailmoods-symbol.png" alt=""/><span>NailMoods<small>ATELIER · LOT 1</small></span><span className="privateBadge">Privé ♡</span></header>
 <main><p className="eyebrow">UNE ENVIE. UN FIL CONDUCTEUR.</p><h1>De l’idée<br/><em>à ta prochaine pose.</em></h1><p className="intro">Un projet qui garde le lien entre ton inspiration, tes préparatifs et tes souvenirs.</p>
 <p className="reviewNote">Démonstration locale des fondations · données fictives · aucune notification envoyée.</p>
 <div className="moods" aria-label="Ambiance">{visualMoods.map(m=><button key={m.id} onClick={()=>setMood(m)} aria-pressed={mood.id===m.id}>{m.name}</button>)}</div>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!project?<section className="card"><h2>Tout commence par une envie.</h2><p>Retrouve une composition existante et conserve-la dans un projet privé.</p><button disabled={busy} className="primary" onClick={()=>action(()=>repo.create('projects',newProject({userId,workspaceId,title,idea:demoIdea(),source:'inspiration'})),'Projet enregistré')}>Créer le projet de démonstration</button></section>:<>
 <section className="card hero"><div className="cardTop"><span className="eyebrow">MON PROJET DE POSE</span><span className="status">{STATUS_LABELS[project.status]}</span></div><h2>{project.title}</h2><div className="preview"><NailPreview idea={project.details.composition}/></div><div className="chips"><span>{view.shape}</span><span>{view.length}</span><span>{view.estimatedMinutes} min estimées</span></div><p className="small">Couleur de démonstration fixe · le mood ne la recolore pas.</p><div className="journey"><b>01<br/>Inspiration</b><b>02<br/>Préparation</b><b>03<br/>Réalisation</b><b>04<br/>Souvenir</b></div></section>
 <section className="card"><h2>Une idée qui t’appartient.</h2><label>Nom du projet<input aria-label="Nom du projet" value={title} onChange={e=>setTitle(e.target.value)} maxLength={120}/></label><button disabled={busy} onClick={()=>action(()=>repo.save('projects',{...project,title}),'Modification enregistrée')}>Enregistrer le nom</button><p className="small">Révision {project.revision} · tes modifications restent attachées au même projet.</p></section>
 <div className="bento"><section className="card soft"><MoodGlyph value="Witchy"/><h2>La même<br/>inspiration.</h2><p>Le rendu et la recette existants sont réutilisés.</p></section><section className="card"><span className="bigNumber">{view.steps.length}</span><h2>étapes du guide</h2><p>Le moteur de tutoriel reste unique.</p></section></div>
 <section className="card"><p className="eyebrow">À TON RYTHME</p><h2>Prévoir ton instant.</h2><label>Date de la pose<input type="date" value={date} onChange={e=>setDate(e.target.value)} aria-label="Date de la pose"/></label><p className="small">Journée entière · Europe/Paris · aucune anticipation imposée.</p><button disabled={busy} className="primary" onClick={()=>action(async()=>{await repo.create('plan',newPlanItem(project,{date}));await repo.save('projects',{...project,status:'planned'});},'Date enregistrée')}>Planifier cette pose</button></section>
 <section className="card"><p className="eyebrow">MON PLANNING</p><h2>Les prochains petits pas.</h2>{['thisWeek','later','overdue'].map(key=><div key={key}><h3>{{thisWeek:'Cette semaine',later:'Plus tard',overdue:'Dates passées'}[key]}</h3>{groups[key].length?groups[key].map(item=><div className="planRow" key={item.id}><span className="dateBadge">{item.scheduled_on.slice(8)}<small>{item.scheduled_on.slice(5,7)}</small></span><span><b>{item.title}</b><small>{item.kind==='pose'?'Pose personnelle':item.kind} · journée entière</small></span><button disabled={busy} aria-label="Supprimer cette date" onClick={()=>action(()=>repo.remove('plan',item),'Date et rappels associés supprimés')}>×</button></div>):<p className="small">Rien de prévu.</p>}</div>)}</section>
 {plan.length>0&&<section className="card"><h2>Un rappel, si tu le souhaites.</h2><label>Instant choisi (avec fuseau)<input aria-label="Instant du rappel" value={reminderAt} onChange={e=>setReminderAt(e.target.value)}/></label><button disabled={busy} onClick={()=>action(()=>repo.create('reminders',newReminder(plan[0],{at:reminderAt})),'Rappel enregistré, sans envoi')}>Enregistrer le rappel</button>{reminders.map(r=><div key={r.id} className="reminderRow"><label><input disabled={busy} type="checkbox" checked={r.enabled} onChange={()=>action(()=>repo.save('reminders',{...r,enabled:!r.enabled}),'Préférence de rappel enregistrée')}/> Rappel {r.enabled?'actif':'désactivé'}</label><button aria-label="Supprimer le rappel" onClick={()=>action(()=>repo.remove('reminders',r),'Rappel supprimé')}>×</button></div>)}<p className="small">L’envoi et le calendrier système seront intégrés au lot 3.</p></section>}
 <button disabled={busy} className="delete" onClick={()=>action(()=>repo.remove('projects',project),'Projet et planning supprimés')}>Supprimer ce projet de démonstration</button></>}
 <aside><h2>IA+ · socle interne</h2><p>Droit additionnel indépendant de Free, Plus et Pro. Accès public masqué, flags serveur fermés, aucun appel payant.</p></aside><footer>Même app. Différents moods. Toujours toi. ♡</footer></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
