import React from 'react';import {createRoot} from 'react-dom/client';
import Assistant from '../../src/assistant/Assistant.jsx';
import {SocialProvider} from '../../src/social/SocialContext.jsx';
import {StorageContext} from '../../src/StorageContext.jsx';
import {applyMood,moodFor} from '../../src/design/themes.js';
import {localPlan} from '../../src/assistant/model.js';
import {CONCEPT_COLORS} from '../../supabase/functions/nailmoods-ai/contract.mjs';
import '../../src/style.css';import '../../src/design-system.css';import '../../src/design/da06.css';import '../../src/design/profile-experience.css';import '../../src/inspiration.css';
const params=new URLSearchParams(location.search);applyMood(moodFor(params.get('mood')));
const access={uiAccess:true,allowed:true,admin:true,enabled:true,dailyBudget:2,monthlyBudget:10,balance:{},operations:Object.fromEntries(['conversation','trends','vision','illustration','realistic'].map(o=>[o,{enabled:true,credits:0}]))};
const client={rpc:async()=>({data:null}),functions:{invoke:async(_,{body})=>{window.fixtureCalls.push(body);if(body.action==='access')return{data:{...access}};if(body.action==='history')return{data:{threads:[],messages:[]}};if(body.action==='switch'){access.enabled=body.enabled;access.allowed=body.enabled;return{data:{...access}};}if(body.action==='diagnostics')return{data:{authenticated:true}};if(body.action==='metrics')return{data:{byOperation:[],activeUsers:1}};if(body.action==='health')return{data:{queued:0,running:0}};if(body.operation==='trends')return {data:{status:'succeeded',result:{kind:'trends',message:'Trois inspirations à explorer.',products:CONCEPT_COLORS,cards:['French automnale','Fleurs de saison','Cassis et or'].map(title=>({plan:{...localPlan('French dorée',{profile:{}}),title},summary:'Une idée facile à adapter.',source:{url:'https://example.com/article',title:'Source de test'}}))}}};return {data:{status:'succeeded',result:{kind:'plan',plan:localPlan(body.prompt,{profile:{}}),products:CONCEPT_COLORS}}};}}};
window.fixtureCalls=[];
createRoot(document.getElementById('root')).render(<main className="app"><SocialProvider client={client} userId="10000000-0000-4000-8000-000000000001" tier="free"><StorageContext.Provider value={{workspaceId:'20000000-0000-4000-8000-000000000001'}}><Assistant items={[]} profile={{}} onClose={()=>{}} onSave={()=>true} onOpen={()=>{}} onTutorial={()=>{}}/></StorageContext.Provider></SocialProvider></main>);
