import React,{useState} from 'react';
import CreationSources from '../../src/CreationSources.jsx';
import '../../src/design/common-ux.css';
import '../../src/design/atelier.css';import {createRoot} from 'react-dom/client';
import Assistant,{AssistantRenderEntry} from '../../src/assistant/Assistant.jsx';
import NailPreview from '../../src/NailPreview.jsx';
import {SocialProvider} from '../../src/social/SocialContext.jsx';
import {StorageContext} from '../../src/StorageContext.jsx';
import {applyMood,moodFor} from '../../src/design/themes.js';
import {localPlan,ideaFromPlan} from '../../src/assistant/model.js';
import {CONCEPT_COLORS} from '../../supabase/functions/nailmoods-ai/contract.mjs';
import '../../src/style.css';import '../../src/creation.css';import '../../src/design-system.css';import '../../src/design/da06.css';import '../../src/design/profile-experience.css';import '../../src/inspiration.css';
const params=new URLSearchParams(location.search);applyMood(moodFor(params.get('mood')));
const access={uiAccess:true,allowed:true,admin:true,enabled:true,dailyBudget:2,monthlyBudget:10,balance:{},operations:Object.fromEntries(['conversation','trends','vision','illustration','realistic'].map(o=>[o,{enabled:true,credits:0}]))};
const client={rpc:async()=>({data:null}),functions:{invoke:async(_,{body})=>{window.fixtureCalls.push(body);if(body.action==='access')return{data:params.get('pilot')==='no'?{...access,allowed:false,uiAccess:false}:{...access}};if(body.action==='history')return{data:{threads:[],messages:[]}};if(body.action==='switch'){access.enabled=body.enabled;access.allowed=body.enabled;return{data:{...access}};}if(body.action==='diagnostics')return{data:{authenticated:true}};if(body.action==='metrics')return{data:{byOperation:[],activeUsers:1}};if(body.action==='health')return{data:{queued:0,running:0}};if(body.operation==='trends')return {data:{status:'succeeded',result:{kind:'trends',message:'Trois inspirations à explorer.',products:CONCEPT_COLORS,cards:['French automnale','Fleurs de saison','Cassis et or'].map(title=>({plan:{...localPlan('French dorée',{profile:{}}),title},summary:'Une idée facile à adapter.',source:{url:'https://example.com/article',title:'Source de test'}}))}}};if(['realistic','illustration'].includes(body.operation))return{data:{status:'succeeded',result:{kind:body.operation,message:'Visuel de test',imageUrl:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024"><rect width="1024" height="1024" fill="#c9bdad"/><text x="150" y="500">Rendu simulé pour le test</text></svg>')}}};const plan=localPlan(body.prompt,{profile:{shape:body.shape,length:body.length}});plan.level=body.level;if(body.designCount===10)plan.nails=[...plan.nails,...plan.nails.map((n,i)=>({...n,finger:i+5,designBrief:'Motif distinct main droite '+i}))];return {data:{status:'succeeded',result:{kind:'plan',plan,products:CONCEPT_COLORS}}};}}};
window.fixtureCalls=[];
function Fixture(){const [open,setOpen]=useState(false);const existing=params.has('idea')?ideaFromPlan(localPlan('French rose dorée',{profile:{shape:'Carrée',length:'Longue'}}),{products:CONCEPT_COLORS,items:[],profile:{}}):null;return <>{existing?<NailPreview idea={existing} controls renderAction={<AssistantRenderEntry onOpen={()=>setOpen(true)}/>}/>:<CreationSources onChoose={()=>{}} onJournal={()=>{}} onOpenAI={()=>setOpen(true)}/>} {open&&<Assistant items={[]} profile={{}} initialIdea={existing} initialRender={existing?'realistic':null} onClose={()=>setOpen(false)} onSave={idea=>{window.fixtureSaved=idea;return true;}} onOpen={()=>{}} onTutorial={()=>{}}/>}</>;}
createRoot(document.getElementById('root')).render(<main className="app"><SocialProvider client={client} userId="10000000-0000-4000-8000-000000000001" tier="free"><StorageContext.Provider value={{workspaceId:'20000000-0000-4000-8000-000000000001'}}><Fixture/></StorageContext.Provider></SocialProvider></main>);
