import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';
import CataloguePanel from '../../src/catalogue/CataloguePanel';import {ShareDetails} from '../../src/social/ShareCard';
import {StorageContext} from '../../src/StorageContext';import {SocialProvider} from '../../src/social/SocialContext';import {applyMood,visualMoods,moodFor}from'../../src/design/themes';
import '../../src/style.css';import '../../src/creation.css';import '../../src/design-system.css';import '../../src/finish.css';import '../../src/ux-polish.css';import '../../src/design/da06.css';import '../../src/workspaces/professional.css';
const ids={a:'10000000-0000-4000-8000-000000000001',b:'10000000-0000-4000-8000-000000000002',c:'10000000-0000-4000-8000-000000000003'},params=new URLSearchParams(location.search),actor=params.get('actor')||'b',userId=ids[actor],workspaceId='20000000-0000-4000-8000-00000000000'+(actor==='a'?'1':'2'),tier=actor==='a'?'plus':'pro';
const request=async(q)=>{const r=await fetch('/__catalogue_rpc',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...q,actor})});return r.json();};
const client={auth:{getUser:async()=>({data:{user:{id:userId}}}),getSession:async()=>({data:{session:null}})},storage:{from:()=>({createSignedUrl:async()=>({data:{signedUrl:null}})})},rpc:(name,args={})=>name==='nm_social'?Promise.resolve({data:[]}):request({name,args}),from(table){const q={table,action:'select',fields:'*',filters:[],limit:100,offset:0};const chain={select(v='*'){q.fields=v;return chain;},eq(k,v){q.filters.push([k,v]);return chain;},is(){return chain;},order(k){q.order=k;return chain;},range(a,b){q.offset=a;q.limit=b-a+1;return chain;},limit(n){q.limit=n;return chain;},insert(v){q.action='insert';q.values=v;return chain;},update(v){q.action='update';q.values=v;return chain;},single(){q.single=true;return chain;},maybeSingle(){q.single=true;return chain;},then(ok,fail){return(table.startsWith('pose_')?request({q}):Promise.resolve({data:[]})).then(ok,fail);}};return chain;}};
const storage={accountScoped:true,accountTier:tier,userId,workspaceId,getItem:k=>localStorage.getItem(actor+':'+k),setItem:(k,v)=>localStorage.setItem(actor+':'+k,v),removeItem:k=>localStorage.removeItem(actor+':'+k)};
function App(){const[space,setSpace]=useState(null),[snapshot,setSnapshot]=useState(null),[mood,setMood]=useState('soft-glam'),[id,setId]=useState(location.hash.slice(1).split('/').at(-1)||'30000000-0000-4000-8000-000000000001');useEffect(()=>{applyMood(moodFor(mood));},[mood]);useEffect(()=>{client.rpc('nm_pro_state').then(r=>setSpace(r.data?.spaces?.[0]));},[]);useEffect(()=>{const f=()=>setId(location.hash.slice(1).split('/').at(-1));window.addEventListener('hashchange',f);return()=>window.removeEventListener('hashchange',f);},[]);useEffect(()=>{setSnapshot(null);client.rpc('nm_share_detail',{p_id:id}).then(r=>setSnapshot(r.data));},[id]);return <main style={{maxWidth:700,margin:'auto',padding:'20px 16px 60px'}}><small>VALIDATION · DONNÉES DE DÉMONSTRATION</small><h1>NailMoods</h1><label>Mood<select aria-label="Mood" value={mood} onChange={e=>setMood(e.target.value)}>{visualMoods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{params.get('view')==='po'?snapshot?<ShareDetails client={client} id={id} snapshot={snapshot}/>:<p>Ouverture du brief…</p>:actor==='c'?<CataloguePanel client={client} staff/>:space?<CataloguePanel client={client} space={space}/>:<p>Ouverture de la vitrine…</p>}</main>}
createRoot(document.getElementById('root')).render(<StorageContext.Provider value={storage}><SocialProvider client={client} userId={userId} tier={tier}><App/></SocialProvider></StorageContext.Provider>);
