import React,{useEffect,useState} from 'react';
import {useSocial} from '../social/SocialContext';
import {readAIPlusAccess,AI_FEATURES} from '../poseCycle/aiAccess';
export function InternalAIEntry(){const s=useSocial(),[allowed,setAllowed]=useState(false);useEffect(()=>{let active=true;if(s?.client)readAIPlusAccess(s.client).then(a=>{if(active)setAllowed(a.allowed);}).catch(()=>{});return()=>{active=false;};},[s?.client,s?.userId]);return allowed?<button className="sourceJournalLink" onClick={()=>location.hash='creer/ia-interne'}>Laboratoire IA+ · interne</button>:null;}
export default function InternalLab(){const s=useSocial(),[state,setState]=useState('loading'),[projects,setProjects]=useState([]),[history,setHistory]=useState([]),[project,setProject]=useState(''),[feature,setFeature]=useState('generateVariation'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){const r=await s.client.rpc('nm_ai_history');if(r.error)throw r.error;setHistory(r.data||[]);}
 useEffect(()=>{let active=true;(async()=>{try{if(!s?.client)throw Error();const a=await readAIPlusAccess(s.client);if(!a.allowed)throw Error();const [p,h]=await Promise.all([s.client.from('pose_projects').select('id,title').eq('user_id',s.userId).order('created_at',{ascending:false}).limit(50),s.client.rpc('nm_ai_history')]);if(p.error||h.error)throw Error();if(active){setProjects(p.data);setProject(p.data[0]?.id||'');setHistory(h.data);setState('ready');}}catch{if(active)setState('denied');}})();return()=>{active=false;};},[s?.client,s?.userId]);
 async function run(){setBusy(true);setError('');try{const r=await s.client.functions.invoke('ai-internal',{body:{requestId:crypto.randomUUID(),projectId:project,feature}});if(r.error)throw Error('L’expérience est indisponible ou ton quota est atteint.');await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function remove(id){setBusy(true);try{const r=await s.client.rpc('nm_ai_delete',{p_id:id});if(r.error)throw r.error;await refresh();}catch{setError('Suppression impossible. Réessaie.');}finally{setBusy(false);}}
 return <section className="trainerPage"><button className="nmQuiet" onClick={()=>location.hash='creer'}>← Revenir à Créer</button><header><small>ACCÈS INTERNE</small><h1>Laboratoire IA+</h1><p>{state==='loading'?'Vérification de l’accès…':state==='denied'?'Cet espace est fermé.':'Vérification expérimentale du circuit serveur. Aucun fournisseur payant, aucune image générée et aucune analyse de photo dans cette version.'}</p></header>{state==='ready'&&<><label>Projet<select value={project} onChange={e=>setProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Fonction expérimentale<select value={feature} onChange={e=>setFeature(e.target.value)}>{AI_FEATURES.map(f=><option key={f}>{f}</option>)}</select></label><button className="trainerDone" disabled={busy||!project} onClick={run}>Tester le circuit interne</button>{error&&<p role="alert">{error}</p>}<h2>Historique privé</h2>{!history.length&&<p>Aucune expérience.</p>}{history.map(j=><article className="lifeCard" key={j.id}><b>{j.feature}</b><p>{j.status} · {new Date(j.createdAt).toLocaleString('fr-FR')}</p><p>{j.result?.message||j.error||'En cours'}</p><button disabled={busy} onClick={()=>remove(j.id)}>Supprimer de mon historique</button></article>)}</>}</section>;
}
