import React,{useEffect,useState,useRef} from 'react';
import NailPreview from '../NailPreview';
import {compositionImage} from './compositionImage';
import {useSocial} from '../social/SocialContext';
import {readAIPlusAccess,AI_FEATURES} from '../poseCycle/aiAccess';
export function InternalAIEntry(){const s=useSocial(),[allowed,setAllowed]=useState(false);useEffect(()=>{let active=true;if(s?.client)readAIPlusAccess(s.client).then(a=>{if(active)setAllowed(a.allowed);}).catch(()=>{});return()=>{active=false;};},[s?.client,s?.userId]);return allowed?<button className="sourceJournalLink" onClick={()=>location.hash='creer/ia-interne'}>Laboratoire IA+ · interne</button>:null;}
export default function InternalLab(){const s=useSocial(),[state,setState]=useState('loading'),[projects,setProjects]=useState([]),[history,setHistory]=useState([]),[project,setProject]=useState(''),[feature,setFeature]=useState('generateVariation'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[image,setImage]=useState(null);const preview=useRef(null),idea=projects.find(p=>p.id===project)?.details?.composition;
 async function refresh(){const r=await s.client.rpc('nm_ai_history');if(r.error)throw r.error;setHistory(r.data||[]);}
 useEffect(()=>{let active=true;(async()=>{try{if(!s?.client)throw Error();const a=await readAIPlusAccess(s.client);if(!a.allowed)throw Error();const [p,h]=await Promise.all([s.client.from('pose_projects').select('id,title,details').eq('user_id',s.userId).order('created_at',{ascending:false}).limit(50),s.client.rpc('nm_ai_history')]);if(p.error||h.error)throw Error();if(active){setProjects(p.data);setProject(p.data[0]?.id||'');setHistory(h.data);setState('ready');}}catch{if(active)setState('denied');}})();return()=>{active=false;};},[s?.client,s?.userId]);
 async function run(render=false){setBusy(true);setError('');try{const r=await s.client.functions.invoke('ai-internal',{body:{requestId:crypto.randomUUID(),projectId:project,feature:render?'generateVariation':feature,...(render?{referenceImage:await compositionImage(preview.current)}:{})}});if(r.error){let code;try{code=(await r.error.context.json()).error;}catch{}throw Error(code==='provider_not_configured'?'Le rendu IA n’est pas encore activé.':code==='provider_busy'?'Le fournisseur est occupé. Réessaie plus tard.':'L’expérience est indisponible ou ton quota est atteint.');}if(r.data?.imageUrl)setImage(r.data.imageUrl);await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function remove(id){setBusy(true);try{const r=await s.client.functions.invoke('ai-internal',{body:{action:'delete',jobId:id}});if(r.error)throw r.error;setImage(null);await refresh();}catch{setError('Suppression impossible. Réessaie.');}finally{setBusy(false);}}
 async function view(id){setBusy(true);setError('');try{const r=await s.client.functions.invoke('ai-internal',{body:{action:'read',jobId:id}});if(r.error||!r.data?.imageUrl)throw Error();setImage(r.data.imageUrl);}catch{setError('Ce rendu est indisponible. Réessaie.');}finally{setBusy(false);}}
 return <section className="trainerPage"><button className="nmQuiet" onClick={()=>location.hash='creer'}>← Revenir à Créer</button><div className="trainerHeading"><small>ACCÈS INTERNE</small><h1>Laboratoire IA+</h1><p>{state==='loading'?'Vérification de l’accès…':state==='denied'?'Cet espace est fermé.':'Aperçu réaliste expérimental de ta composition. Accès privé, soumis au quota interne et à l’activation du fournisseur.'}</p></div>{state==='ready'&&<><label>Projet<select value={project} onChange={e=>{setProject(e.target.value);setConsent(false);setImage(null);}}>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><section className="lifeCard"><h2>Rendu photo réaliste IA</h2>{idea?.nails?.length===5?<div ref={preview}><NailPreview idea={idea}/></div>:<p>Enregistre un projet avec une composition de cinq ongles pour créer son rendu.</p>}<label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Envoyer uniquement cette composition à OpenAI pour créer un aperçu IA.</label><p>Image synthétique, sans garantie de correspondance exacte des couleurs. Chaque génération utilise une tentative du quota.</p><button className="trainerDone" disabled={busy||!consent||idea?.nails?.length!==5} onClick={()=>run(true)}>{busy?'Traitement en cours…':'Générer un aperçu réaliste'}</button>{image&&<figure><img src={image} style={{width:'100%',borderRadius:16}} alt="Aperçu synthétique généré par IA de cinq ongles"/><figcaption>Aperçu IA · à valider avant réalisation</figcaption></figure>}</section><label>Fonction expérimentale<select value={feature} onChange={e=>setFeature(e.target.value)}>{AI_FEATURES.map(f=><option key={f}>{f}</option>)}</select></label><button className="trainerDone" disabled={busy||!project} onClick={()=>run(false)}>Tester le circuit interne</button>{error&&<p role="alert">{error}</p>}<h2>Historique privé</h2>{!history.length&&<p>Aucune expérience.</p>}{history.map(j=><article className="lifeCard" key={j.id}><b>{j.feature}</b><p>{j.status} · {new Date(j.createdAt).toLocaleString('fr-FR')}</p><p>{j.result?.message||j.error||'En cours'}</p>{j.result?.imagePath&&<button disabled={busy} onClick={()=>view(j.id)}>Voir le rendu IA</button>}<button disabled={busy} onClick={()=>remove(j.id)}>Supprimer de mon historique</button></article>)}</>}</section>;
}
