from pathlib import Path
import base64, json, html
root=Path(__file__).resolve().parents[1]
evidence=root/'docs/pose-lot4/evidence'
out=root.parent/'deliverables/NailMoods-Lot4-DIY'
out.mkdir(parents=True,exist_ok=True)
def picture(name,alt):
    image=base64.b64encode((evidence/name).read_bytes()).decode()
    return f'<img src="data:image/png;base64,{image}" alt="{html.escape(alt)}" loading="lazy">'
moods=[('soft-glam','Soft Glam'),('dark-feminine','Dark Feminine'),('cottagecore','Cottagecore'),('pop-pastel','Pop Pastel')]
tabs=''.join(f'<button type="button" role="tab" aria-controls="{slug}" aria-selected="{str(i==0).lower()}" id="tab-{slug}" data-mood="{slug}">{name}</button>' for i,(slug,name) in enumerate(moods))
shots=''.join(f'<section class="moodpanel" role="tabpanel" aria-labelledby="tab-{slug}" id="{slug}" '+('hidden' if i else '')+'>'+picture('diy-'+slug+'.png','Fiche DIY réelle — '+name)+'</section>' for i,(slug,name) in enumerate(moods))
results=json.loads((evidence/'browser-diy.json').read_text())
checks=''.join('<li>'+html.escape(s)+'</li>' for s in results['checks'])
document='''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>NailMoods — Lot 4 · De l’inspiration à la pose</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#382530;background:#fbf5ef;line-height:1.6}*{box-sizing:border-box}body{margin:0}main{max-width:1060px;margin:auto;padding:36px clamp(20px,5vw,50px) 64px}h1,h2,h3{font-family:Georgia,serif;font-weight:400;line-height:1.17;overflow-wrap:anywhere}h1{font-size:clamp(38px,8vw,68px);max-width:760px;margin:22px 0}h2{font-size:clamp(28px,5vw,40px);margin-top:0}h3{font-size:25px}p{max-width:760px}small{font-size:12px;color:#725864}.eyebrow{font-size:11px;letter-spacing:.16em;text-transform:uppercase}.intro{font-size:18px;color:#725864}.badges{display:flex;flex-wrap:wrap;gap:8px;margin:24px 0 40px}.badges span{padding:8px 13px;border-radius:30px;background:#efdce2;font-size:12px}.card{padding:clamp(20px,4vw,32px);border-radius:28px;border:1px solid #dcc7cc;background:#fffcfa;margin:30px 0}.accent{background:#f1e2e7}.two{display:grid;grid-template-columns:1fr 1fr;gap:24px}.two>div{min-width:0}.shot{max-width:440px;margin:24px auto;border-radius:24px;overflow:hidden;border:1px solid #dcc7cc;background:#fffcfa}.shot img,.moodpanel img{display:block;width:100%;height:auto}.moodpanel{max-width:460px;margin:24px auto;border-radius:24px;overflow:hidden;border:1px solid #dcc7cc}.tabs{display:flex;flex-wrap:wrap;gap:9px;margin:22px 0}.tabs button{border:1px solid #c4a4b0;background:#fffcfa;border-radius:30px;padding:12px 16px;min-height:44px;font:inherit;font-size:13px;color:#533043;cursor:pointer}.tabs button[aria-selected=true]{background:#82465f;color:white;border-color:#82465f}.tabs button:focus-visible,summary:focus-visible{outline:3px solid #82465f;outline-offset:3px}[hidden]{display:none!important}li{margin:10px 0}ul,ol{padding-left:22px}details{margin:22px 0;border-top:1px solid #dcc7cc;padding-top:16px}summary{cursor:pointer;min-height:44px;font-weight:650}code{overflow-wrap:anywhere;font-size:.85em}a{color:#82465f}table{border-collapse:collapse;width:100%;font-size:13px}td,th{text-align:left;vertical-align:top;padding:12px 8px;border-bottom:1px solid #dcc7cc}th{width:32%}.signature{text-align:center;margin-top:42px;color:#82465f;font-family:Georgia,serif;font-size:25px}.note{border-left:3px solid #bc8e9f;padding-left:16px;color:#725864;font-size:13px}@media(max-width:650px){.two{grid-template-columns:1fr}main{padding-top:24px}.card{margin:22px 0}.intro{font-size:16px}.tabs button{flex:1 1 40%}td,th{padding:10px 5px}}@media(prefers-reduced-motion:no-preference){.tabs button{transition:background .15s,color .15s}}
</style><main><div class="eyebrow">NailMoods · Revue du Lot 4 · 4 octobre 2026</div><h1>De l’inspiration<br>à ta prochaine pose.</h1><p class="intro">Les marges du suivi sont corrigées. Une nouvelle fiche DIY relie maintenant l’idée, les produits de ta Collection et le tutoriel existant, au sein du même Projet de pose.</p><div class="badges"><span>DA06 conservée</span><span>4 moods</span><span>Recette testée</span><span>À valider avant le Lot 5</span></div>
<section class="card accent"><h2>Les textes respirent.</h2><p>Le bloc de suivi possède désormais ses propres marges intérieures. Les titres, boutons et observations restent espacés des bords, même sur un petit écran.</p><p class="note">Contrôle à 320, 360, 390 et 430 px. Gouttières de page et cartes partagées ; la correction concerne aussi le Planning et les écrans Projet / Tenue / DIY.</p>FOLLOWUP</section>
<section class="card"><div class="eyebrow">Le parcours réellement exécuté</div><h2>Je veux la réaliser.</h2><ol><li>Ouvrir une inspiration et toucher <b>Je veux la réaliser</b>.</li><li>Retrouver la composition dans sa <b>fiche DIY privée</b>.</li><li>Vérifier les produits possédés, les teintes proches et le matériel manquant.</li><li>Ouvrir un produit de la Collection, reprendre le <b>tutoriel existant</b> ou planifier la pose.</li></ol><p>Deux ouvertures de la même inspiration reprennent le même projet. Une tenue déjà enregistrée ouvre cette fiche avec son identifiant actuel.</p></section>
<section class="card"><div class="eyebrow">Même écran · mêmes données</div><h2>Une fiche, quatre ambiances.</h2><p>Ce sont des captures de l’application exécutée en recette. La composition et les deux produits de test sont identiques dans les quatre vues. Les HEX produits restent inchangés.</p><div class="tabs" role="tablist" aria-label="Moods de la fiche DIY">TABS</div>SHOTS<p class="note">Captures longues à 390 px de large. Leur hauteur est adaptée au contenu pour que la barre de navigation fixe ne masque pas la fiche au milieu de l’image.</p></section>
<section class="card"><h2>Une Collection utile à ta recette.</h2><table><tr><th>✓ Je possède</th><td>La référence est présente et sa quantité est positive.</td></tr><tr><th>≈ Teinte proche</th><td>Couleur proche, même type/famille et finition renseignée identique. Si l’opacité manque, c’est indiqué.</td></tr><tr><th>− Il me manque</th><td>Aucun produit ni matériel suffisamment renseigné ne correspond.</td></tr><tr><th>? À vérifier</th><td>La référence a changé depuis l’enregistrement de l’inspiration.</td></tr></table><p class="note">Une ressemblance de couleur ne prouve aucune compatibilité chimique. Les suggestions ne remplacent jamais les produits de la recette automatiquement.</p>COMPARISON</section>
<section class="card"><h2>Un geste après l’autre.</h2><p>La fiche réutilise le tutoriel NailMoods et conserve son lien avec le projet. Elle n’ajoute pas une seconde architecture de recettes.</p>TUTORIAL<p class="note">Pour Chrome, Aura et les autres techniques complexes, le guide est explicitement présenté comme partiel. Les gestes spécialisés et les protocoles fabricant manquants ne sont pas inventés.</p></section>
<section class="card accent"><h2>Vérifié en recette.</h2><p><b>496 tests passent</b>, aucun échec ; deux anciens tests optionnels restent ignorés. Douze tests ciblent le nouveau moteur DIY. La compilation réussit.</p><details><summary>Voir les contrôles du parcours réel</summary><ul>CHECKS</ul></details><p>Trois vrais comptes de recette : Plus pour le parcours, Pro pour le refus d’accès au projet d’une autre personne, Free pour la fiche DIY personnelle et le tutoriel. Les données de démonstration ont été nettoyées.</p><p class="note">Les essais dans le navigateur ne remplacent pas des tests sur téléphones physiques. Les notifications et calendriers natifs du Lot 3 ne sont pas retestés sur appareils dans ce lot.</p></section>
<details><summary>Développement, limites et retour arrière</summary><p>Branche de travail : <code>feat/pose-diy-lot4</code>, issue du Lot 3 validé. Aucun déploiement Production, fusion ou AAB. IA+ reste fermé ; les imports photo et tenue restent Plus/Pro.</p><p><b>Aucune migration nouvelle.</b> La checklist est calculée avec la Collection actuelle, sans table ou modèle doublon. La session du tutoriel utilise le champ déjà prévu dans <code>pose_projects.details.tutorialSessionId</code>.</p><p>Ajouts : moteur <code>diy.js</code>, écran <code>DiyView.jsx</code>, styles, tests et route <code>#creer/diy/:projectId</code>. Intégration limitée à Inspiration, Créer et Projet ; tokens de marges partagés et suivi corrigé. Logo, illustrations et icônes d’univers conservés.</p><p>La proximité des teintes reste indicative. Les gestes avancés et les données fabricant absentes restent à compléter. La synchronisation automatique des dates entre un ancien Journal lié et son Projet n’a pas été modifiée.</p><p>Retour arrière : revenir au parent de cette branche. Aucune migration à annuler ; les projets et liens restent compatibles avec les lots précédents.</p><p>Le dossier technique et les résultats de tests sont dans <code>docs/pose-lot4</code> sur la branche de travail.</p></details><p class="signature">Même app. Différents moods.<br>Toujours toi. ♡</p></main><script>
const tabs=[...document.querySelectorAll('[role=tab]')];function select(tab){for(const b of tabs){const active=b===tab;b.setAttribute('aria-selected',active);document.getElementById(b.dataset.mood).hidden=!active;}}
for(const [i,tab] of tabs.entries()){tab.addEventListener('click',()=>select(tab));tab.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;select(tabs[j]);tabs[j].focus();}});}
</script></html>'''
document=document.replace('FOLLOWUP','<div class="shot">'+picture('suivi-marges.png','Suivi réel avec marges intérieures corrigées')+'</div>').replace('TABS',tabs).replace('SHOTS',shots).replace('COMPARISON','<div class="shot">'+picture('comparaison.png','Comparaison de la recette avec la Collection réelle de test')+'</div>').replace('TUTORIAL','<div class="shot">'+picture('tutoriel.png','Tutoriel existant ouvert depuis la fiche DIY')+'</div>').replace('CHECKS',checks)
p=out/'NailMoods-Lot4-DIY.html';p.write_text(document);print(str(p));print(p.stat().st_size)
