from pathlib import Path
import base64,json,html
root=Path(__file__).resolve().parents[1]
evidence=root/'docs/pose-lots6-7/evidence'
out=root.parent/'deliverables/NailMoods-Lots6-7'
out.mkdir(parents=True,exist_ok=True)
def image(file,alt):return '<img loading="lazy" src="data:image/png;base64,'+base64.b64encode((evidence/file).read_bytes()).decode()+'" alt="'+html.escape(alt)+'">'
results=json.loads((evidence/'browser-lots67.json').read_text())
assert results['passed']
moods=[('soft-glam','Soft Glam'),('dark-feminine','Dark Feminine'),('cottagecore','Cottagecore'),('pop-pastel','Pop Pastel')]
tabs=''.join(f'<button role="tab" aria-controls="{slug}" id="tab-{slug}" aria-selected="{str(i==0).lower()}" data-mood="{slug}">{name}</button>' for i,(slug,name) in enumerate(moods))
shots=''.join(f'<section role="tabpanel" id="{slug}" aria-labelledby="tab-{slug}" '+('hidden' if i else '')+'>'+image('suivi-'+slug+'.png','Même suivi réel — '+name)+'</section>' for i,(slug,name) in enumerate(moods))
checks=''.join('<li>'+html.escape(c)+'</li>' for c in results['checks'])
files=html.escape((root/'docs/pose-lots6-7/DELIVERY.md').read_text())
doc='''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NailMoods — Lots 6 & 7 · Ta pose, au fil des jours</title><style>
*{box-sizing:border-box}body{margin:0;background:#faf5ef;color:#35252f;font-family:system-ui,-apple-system,sans-serif;line-height:1.7}main{max-width:920px;margin:auto;padding:46px 22px 70px}h1,h2,h3{font-family:Georgia,serif;font-weight:400;line-height:1.14;text-wrap:balance}h1{font-size:clamp(38px,8vw,70px);margin:18px 0 24px}h2{font-size:clamp(28px,6vw,40px);margin:12px 0 22px}p{margin:14px 0}.eyebrow{font-size:11px;letter-spacing:.15em;text-transform:uppercase;font-weight:650;color:#80506a}.intro{max-width:620px;font-size:18px;color:#74606c}.badges{display:flex;gap:8px;flex-wrap:wrap;margin:26px 0 35px}.badges span{background:#f0e0e4;color:#75415b;font-size:12px;padding:7px 13px;border-radius:99px}.card{padding:clamp(20px,5vw,38px);border:1px solid #dccbd0;border-radius:28px;background:#fffaf6;margin:24px 0}.accent{background:#f1e4e9}.card>img,[role=tabpanel]>img{display:block;width:100%;max-width:450px;height:auto;margin:26px auto;border:1px solid #deced4;border-radius:22px}.note{font-size:13px;color:#756570}button,summary{min-height:46px;font:inherit;cursor:pointer}button{white-space:normal}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:24px 0}button[role=tab]{border:1px solid #c7a9b9;background:#fbf5f6;color:#684159;border-radius:99px;padding:10px 17px;font-size:13px}button[aria-selected=true]{background:#78445f;color:white;border-color:#78445f}button:focus-visible,summary:focus-visible{outline:3px solid #754591;outline-offset:4px}summary{font-weight:650;padding:10px 0}li{padding-left:4px;margin:12px 0}ol,ul{padding-left:23px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.7 system-ui;background:#f4ecee;border-radius:18px;padding:20px}.signature{font:italic 27px/1.45 Georgia,serif;text-align:center;color:#885269;margin-top:45px}.status{padding:18px 22px;border-radius:20px;background:#eadbe7;font-size:14px}a{color:#78445f}code{overflow-wrap:anywhere}[hidden]{display:none!important}@media(max-width:360px){main{padding:28px 16px}.card{padding:19px;border-radius:24px}.tabs button{flex:1 1 42%;padding:8px 10px}h1{font-size:38px}}
</style><main><div class="eyebrow">NailMoods · Recette · 4 octobre 2026</div><h1>Ta pose.<br>Au fil des jours.</h1><p class="intro">Créer, prendre le temps, garder une trace. Le tutoriel, le Journal et le suivi racontent maintenant la même histoire.</p><div class="badges"><span>Texte PO corrigé</span><span>Lot 6 · Minuteurs</span><span>Lot 7 · Suivi</span><span>4 moods</span></div><div class="status"><b>Version de recette à valider.</b> Les captures montrent l’application exécutée avec des comptes de test. Les essais de réception des notifications sur téléphones réels restent à faire avant une bêta.</div>
<section class="card"><div class="eyebrow">La correction demandée</div><h2>Une case discrète.<br>Un texte lisible.</h2><p>Le libellé retrouve sa place à côté de la case, avec un espace constant et des retours à la ligne naturels. Vérifié à 320, 360, 390 et 430 px.</p>CHECKBOX<p class="note">Aperçu réel de la fiche PO. Aucun envoi n’a été effectué pendant ce contrôle.</p></section>
<section class="card accent"><div class="eyebrow">Lot 6 · Un geste après l’autre</div><h2>Le temps que tu choisis.</h2><p>Démarrer, mettre en pause, reprendre ou terminer le minuteur. Ta progression reste enregistrée ; tu peux retrouver le temps après fermeture.</p>TIMER<p>La fin du temps laisse la validation de l’étape entre tes mains. Pour la catalysation, la référence du produit et sa notice font foi.</p><p class="note">Alertes facultatives : son dans le navigateur ouvert ; notifications locales sur mobile. La réception, le son et la vibration sur Android/iOS physiques restent à tester. Une notification peut être retardée par le système.</p></section>
<section class="card"><div class="eyebrow">Lot 7 · De la réalisation au souvenir</div><h2>La même pose,<br>dans ton Journal.</h2><ol><li>Ouvrir le projet et choisir <b>Je la fais moi-même</b>.</li><li>Suivre le tutoriel ou marquer la pose comme réalisée.</li><li>Retrouver sa fiche privée dans <b>Mes poses</b>.</li><li>Ajouter une photo, une note ou un ressenti dans son suivi.</li><li>Choisir ses propres dates d’entretien et de dépose.</li></ol>JOURNAL<p>La recette et ses techniques restent liées au projet. Les observations et photos du suivi restent privées.</p></section>
<section class="card"><div class="eyebrow">Même écran · mêmes données</div><h2>Ton suivi,<br>dans ton ambiance.</h2><p>Quatre captures du même suivi enregistré, avec la même illustration importée, les mêmes dates et les mêmes notes.</p><div role="tablist" class="tabs" aria-label="Ambiances du suivi">TABS</div>SHOTS<p class="note">L’image de démonstration a été importée avec le vrai sélecteur. Il s’agit d’une illustration NailMoods, pas d’une photo de suivi réelle.</p></section>
<section class="card accent"><div class="eyebrow">Planning · À ton rythme</div><h2>Un prochain moment,<br>si tu en as envie.</h2><p>Suivi, entretien ou dépose : le type est prérempli et tu choisis la date. Le mois complet et les couleurs des rendez-vous sont conservés. Les rappels restent facultatifs.</p>PLANNING</section>
<section class="card"><div class="eyebrow">Dépose · Une information fiable</div><h2>La bonne notice,<br>sans temps inventé.</h2><p>Le compteur s’arrête à ta date réelle de dépose. Pour le geste, l’app recherche un protocole vérifié pour la référence exacte. Aucun protocole fabricant vérifié n’est encore disponible dans le catalogue : l’écran le précise et invite à consulter le fabricant ou la professionnelle.</p>REMOVAL</section>
<section class="card accent"><h2>Vérifié en recette.</h2><p><b>508 tests automatisés passent</b>, sans échec. Deux anciens tests optionnels sont ignorés. Les nouveaux contrôles navigateur utilisent trois comptes distincts de recette.</p><details><summary>Voir le parcours testé</summary><ul>CHECKS</ul></details><p>Free peut enregistrer ses poses personnelles. Les droits photo/tenue et sociaux restent Plus/Pro. IA+ reste fermé.</p><p class="note">Aucun déploiement Production, aucune fusion et aucun AAB. Avant bêta : vérifier notifications, caméra native et reprise à froid sur Android et iOS réels.</p></section>
<details class="card"><summary>Fichiers, migrations, limites et retour arrière</summary><pre>TECHNICAL</pre></details><p class="signature">Même app. Différents moods.<br>Toujours toi. ♡</p></main><script>
const tabs=[...document.querySelectorAll('[role=tab]')];function select(tab){for(const b of tabs){const active=b===tab;b.setAttribute('aria-selected',active);document.getElementById(b.dataset.mood).hidden=!active;}}for(const [i,tab] of tabs.entries()){tab.addEventListener('click',()=>select(tab));tab.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;select(tabs[j]);tabs[j].focus();}});}
</script></html>'''
for key,value in {'CHECKBOX':image('partage-texte-corrige.png','Libellé PO corrigé'),'TIMER':image('minuteur-fin.png','Minuteur après expiration'),'JOURNAL':image('journal-lie.png','Journal lié à la même pose'),'TABS':tabs,'SHOTS':shots,'PLANNING':image('planning-entretien.png','Planning du suivi et entretien'),'REMOVAL':image('suivi-et-depose.png','Timeline et fallback de dépose'),'CHECKS':checks,'TECHNICAL':files}.items():doc=doc.replace(key,value)
path=out/'NailMoods-Lots6-7-Tutoriels-et-Suivi.html';path.write_text(doc);print(path)
