from pathlib import Path
import base64,json,html,re
root=Path(__file__).resolve().parents[1];ev=root/'docs/profile-products-lots8-9/evidence';out=root.parent/'deliverables/NailMoods-Lots8-9';out.mkdir(parents=True,exist_ok=True)
results=json.loads((ev/'browser-lots89.json').read_text());assert results['passed']
testlog=Path('/tmp/nm89-tests.log').read_text();counts={k:int(re.search('ℹ '+k+' (\\d+)',testlog).group(1)) for k in ['tests','pass','fail','skipped']};assert counts['fail']==0;(ev/'tests-summary.json').write_text(json.dumps(counts,indent=2))
def img(name,alt):return '<img loading="lazy" alt="'+html.escape(alt)+'" src="data:image/png;base64,'+base64.b64encode((ev/name).read_bytes()).decode()+'">'
moods=[('soft-glam','Soft Glam'),('dark-feminine','Dark Feminine'),('cottagecore','Cottagecore'),('pop-pastel','Pop Pastel')]
tabs=''.join(f'<button role="tab" id="tab-{s}" aria-controls="{s}" aria-selected="{str(i==0).lower()}" data-mood="{s}">{n}</button>' for i,(s,n) in enumerate(moods))
shots=''.join(f'<section role="tabpanel" id="{s}" aria-labelledby="tab-{s}" '+('hidden' if i else '')+'>'+img('profil-reperes-'+s+'.png',n+' · Repères personnels, application exécutée')+'</section>' for i,(s,n) in enumerate(moods))
checks=''.join('<li>'+html.escape(x)+'</li>' for x in results['checks'])
tech=html.escape((root/'docs/profile-products-lots8-9/DELIVERY.md').read_text())
doc='''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NailMoods — Lots 8 & 9 · Mes repères, mes produits</title><style>
*{box-sizing:border-box}body{margin:0;background:#faf5ef;color:#35252f;font:16px/1.7 system-ui,-apple-system,sans-serif}main{max-width:900px;margin:auto;padding:40px 22px 65px}h1,h2{font-family:Georgia,serif;font-weight:400;line-height:1.15;text-wrap:balance}h1{font-size:clamp(38px,8vw,68px);margin:20px 0}h2{font-size:clamp(28px,6vw,40px);margin:14px 0 24px}.eyebrow{font-size:11px;letter-spacing:.14em;color:#80506a;font-weight:650}.intro{max-width:600px;font-size:19px;color:#74606c}.card{padding:clamp(20px,5vw,36px);border:1px solid #dccbd0;border-radius:28px;background:#fffaf6;margin:26px 0}.accent{background:#f1e4e9}.status{padding:18px 22px;background:#eadbe7;border-radius:20px;font-size:14px}.card>img,[role=tabpanel]>img{display:block;width:100%;max-width:440px;margin:24px auto;border:1px solid #deced4;border-radius:20px}.note{font-size:13px;color:#756570}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:24px 0}button,summary{min-height:46px;font:inherit;cursor:pointer}button[role=tab]{border:1px solid #c7a9b9;background:#fbf5f6;color:#684159;border-radius:99px;padding:10px 17px;font-size:13px}button[aria-selected=true]{background:#78445f;color:#fff;border-color:#78445f}button:focus-visible,summary:focus-visible{outline:3px solid #754591;outline-offset:4px}summary{font-weight:650;padding:10px 0}li{margin:12px 0}ul,ol{padding-left:22px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.7 system-ui;background:#f4ecee;padding:20px;border-radius:18px}a{color:#78445f}p{margin:14px 0}[hidden]{display:none!important}.signature{text-align:center;font:italic 28px/1.5 Georgia,serif;color:#885269;margin-top:42px}@media(max-width:360px){main{padding:28px 16px}.card{padding:18px}.tabs button{flex:1 1 42%;padding:8px}h1{font-size:38px}}
</style><main><div class="eyebrow">NAILMOODS · LOTS 8 & 9 · RECETTE</div><h1>Mes repères.<br>Mes produits.</h1><p class="intro">Ce qui compte pour moi, dans mon quotidien. Ce que je sais vraiment de mes produits.</p><div class="status"><b>À valider visuellement.</b> Les captures montrent l’application exécutée avec des comptes de recette. Aucun AAB ni déploiement en Production.</div>
<section class="card"><div class="eyebrow">LOT 8 · PROFIL ENRICHI</div><h2>Une place pour mon quotidien.</h2><p>Clavier, sport, instrument, priorité confort… Quelques choix facultatifs suffisent pour découvrir des formes et longueurs à explorer. Tu gardes la main sur tes préférences.</p><ol><li>Profil → <b>Mes repères personnels</b>.</li><li>Renseigner son quotidien et ses observations, si on le souhaite.</li><li>Choisir une suggestion ou conserver ses préférences.</li><li>Ajouter ses ingrédients à surveiller.</li></ol><p>Ces repères restent privés, même si tu rends tes préférences de pose visibles. Ils sont accessibles aussi en Free.</p><div class="tabs" role="tablist" aria-label="Ambiances du profil">TABS</div>SHOTS<p class="note">Même compte et mêmes repères dans les quatre moods. Marges vérifiées sur 320, 360, 390 et 430 px.</p></section>
<section class="card accent"><div class="eyebrow">LOT 9 · FICHE PRODUIT</div><h2>Une information précise.<br>Une source visible.</h2><p>Les fiches accueillent les listes INCI, les mentions de ta liste personnelle, la comparaison des systèmes et les indications fabricant disponibles.</p>PRODUCT<p>Pour la catalysation, le modèle exact de lampe est choisi explicitement. Une lampe inconnue ne reçoit pas de durée automatique.</p><p class="note">Le premier registre couvre les deux références Red Cherry Green / Green Flash de Manucurist, avec leurs sources. Il ne couvre pas encore tout le catalogue : l’absence d’information est affichée clairement.</p><p class="note">Sources : <a href="https://www.manucurist.com/products/red-cherry-1">Manucurist Green Red Cherry</a> · <a href="https://www.manucurist.com/products/vernis-green-flash-red-cherry">Manucurist Green Flash Red Cherry</a>, consultées le 4 octobre 2026.</p></section>
<section class="card"><div class="eyebrow">MA COLLECTION · MES REPÈRES</div><h2>Repérer, comparer,<br>sans confondre.</h2><p>Une transcription depuis ton flacon reste une saisie personnelle. HEMA, Di-HEMA et Bis-HEMA ne sont pas confondus. Les alternatives comparent couleur, finition, opacité et famille de produit.</p>ALTERNATIVE<p class="note">Produit personnel et HEX de démonstration. La proximité de couleur ne vaut pas compatibilité chimique. Aucun produit n’est déclaré « sans danger ».</p></section>
<section class="card accent"><h2>Vérifié en recette.</h2><p><b>COUNT tests réussis, aucun échec.</b> Deux anciens tests optionnels ignorés. Build de recette réussi.</p><p>Trois comptes authentifiés ont servi aux contrôles de confidentialité, sauvegarde et droits. Les profils ont été restaurés et les produits temporaires supprimés après les tests.</p><details><summary>Voir le parcours réel testé</summary><ul>CHECKS</ul></details><p>Le test a aussi permis de corriger une projection du profil public manquante en recette. Les informations privées restent exclues.</p><p class="note">Android et iOS physiques : vérification du rendu et du clavier encore à effectuer avant la bêta. IA+ reste fermé. Les lots 10 et 11 ne sont pas lancés.</p></section>
<details class="card"><summary>Fichiers, migration, sources, limites et retour arrière</summary><pre>TECH</pre></details><p class="signature">Même app. Différents moods.<br>Toujours toi. ♡</p></main><script>
const tabs=[...document.querySelectorAll('[role=tab]')];function select(t){for(const b of tabs){const on=b===t;b.setAttribute('aria-selected',on);document.getElementById(b.dataset.mood).hidden=!on;}}for(const [i,t] of tabs.entries()){t.addEventListener('click',()=>select(t));t.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;select(tabs[j]);tabs[j].focus();}});}
</script></html>'''
for k,v in {'TABS':tabs,'SHOTS':shots,'PRODUCT':img('produit-inci-fabricant.png','Fiche réelle : INCI, lampe exacte et compatibilité documentée'),'ALTERNATIVE':img('produit-personnel-alternative.png','Transcription personnelle et alternative Collection'),'COUNT':str(counts['pass']),'CHECKS':checks,'TECH':tech}.items():doc=doc.replace(k,v)
p=out/'NailMoods-Lots8-9-Profil-et-Produits.html';p.write_text(doc);print(p)
