from pathlib import Path
import base64, json, html
root=Path(__file__).resolve().parents[1]
evidence=root/'docs/pose-lot5/evidence'
out=root.parent/'deliverables/NailMoods-Lot5-Fiche-Pose'
out.mkdir(parents=True,exist_ok=True)
def picture(name,alt):
    image=base64.b64encode((evidence/name).read_bytes()).decode()
    return f'<img src="data:image/png;base64,{image}" alt="{html.escape(alt)}" loading="lazy">'
moods=[('soft-glam','Soft Glam'),('dark-feminine','Dark Feminine'),('cottagecore','Cottagecore'),('pop-pastel','Pop Pastel')]
tabs=''.join(f'<button type="button" role="tab" aria-controls="{slug}" aria-selected="{str(i==0).lower()}" id="tab-{slug}" data-mood="{slug}">{name}</button>' for i,(slug,name) in enumerate(moods))
shots=''.join(f'<section class="moodpanel" role="tabpanel" aria-labelledby="tab-{slug}" id="{slug}" '+('hidden' if i else '')+'>'+picture('fiche-'+slug+'.png','Fiche pose réelle — '+name)+'</section>' for i,(slug,name) in enumerate(moods))
results=json.loads((evidence/'browser-sharing.json').read_text())
checks=''.join('<li>'+html.escape(s)+'</li>' for s in results['checks'])
style=(root/'scripts/build-diy-report.py').read_text().split('<style>')[1].split('</style>')[0]
document='''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>NailMoods — Lot 5 · Ma fiche pose / ma PO</title><style>STYLE</style><main><div class="eyebrow">NailMoods · Revue du Lot 5 · 4 octobre 2026</div><h1>Ton envie.<br>Une fiche qui la suit.</h1><p class="intro">Le Projet de pose rassemble maintenant la recette, le DIY, le Planning et le suivi. Tu peux transmettre une fiche technique à ta PO, après avoir choisi et confirmé exactement ce qu’elle recevra.</p><div class="badges"><span>DA06 conservée</span><span>4 moods</span><span>Partage privé</span><span>Recette uniquement</span><span>À valider avant le Lot 6</span></div>
<section class="card accent"><h2>Une fiche centrale.</h2><ol><li>Depuis <b>Créer → Mes projets de pose</b>, ouvrir un projet.</li><li>Retrouver l’aperçu, les teintes, la recette et le suivi.</li><li>Choisir <b>Je la fais moi-même</b>, <b>Planifier</b>, <b>Créer une variante</b> ou <b>Envoyer à ma PO</b>.</li><li>Ajouter un moment planifié au calendrier, avec export <b>.ics</b> disponible.</li></ol><p>Le même <code>pose_projects</code> porte ce parcours. Les fonctions et les marges validées des lots précédents sont conservées.</p></section>
<section class="card"><div class="eyebrow">Même écran · mêmes données</div><h2>Quatre ambiances,<br>ta même pose.</h2><p>Captures de l’application exécutée en recette avec un compte de test authentifié. Les couleurs produits restent identiques. Les textes et boutons disposent de marges intérieures, y compris à 320 px.</p><div class="tabs" role="tablist" aria-label="Moods de la fiche pose">TABS</div>SHOTS<p class="note">Captures longues à 390 px ; hauteur adaptée au contenu pour éviter que la barre fixe masque la fiche.</p></section>
<section class="card"><h2>Tu vérifies, puis tu envoies.</h2><p>La PO doit déjà être une connexion acceptée. Le serveur construit l’aperçu à partir de la version enregistrée. La note du projet et la photo de tenue sont facultatives, décochées par défaut.</p>PREVIEW<p class="note">La Collection complète, les notes du Planning, les observations et les photos de suivi ne sont jamais jointes.</p></section>
<section class="card"><h2>Une fiche utile à ta PO.</h2><p>Silhouette, longueur, mood, techniques, références, teintes, finitions et matériel sont réunis dans une vue lisible. Les informations fabricant absentes restent à préciser.</p>RECEIVED<p>La recette originale et le projet restent dans ton compte. La fiche envoyée conserve la composition confirmée : modifier ton projet ne modifie pas cet envoi.</p></section>
<section class="card accent"><h2>Un lien privé.<br>Un QR, les mêmes droits.</h2><p>Copier le lien, utiliser la feuille de partage du téléphone ou montrer le QR ne rend pas la fiche publique. Il faut se connecter avec un compte participant autorisé.</p>QRCODE<p><b>Retirer l’accès</b> invalide le lien et la fiche. Supprimer le projet retire aussi ses partages associés.</p><p class="note">Le QR est généré localement, sans service externe. Une copie déjà faite par une destinataire ne peut pas être effacée à distance. Les liens des captures appartiennent à la recette locale.</p></section>
<section class="card"><h2>Le compte tiers reste dehors.</h2><p>Le compte de test Pro destinataire ouvre sa fiche ; le compte Free tiers et une requête anonyme sont refusés. Le compte Pro n’accède pas au projet privé ni à son Planning.</p>DENIED</section>
<section class="card accent"><h2>Contrôlé en recette.</h2><p><b>500 tests automatisés passent</b>, aucun échec ; deux anciens tests optionnels sont ignorés. La compilation réussit. Le parcours connecté utilise trois vrais comptes de recette, avec des données de démonstration synthétiques.</p><details><summary>Voir les contrôles du parcours réel</summary><ul>CHECKS</ul></details><p>Les essais concernent l’application exécutée et les RPC de recette. Aucun message n’a été envoyé à une utilisatrice réelle.</p><p class="note">À vérifier sur téléphones avant une bêta : feuille de partage native, ouverture des liens à froid/à chaud et ajout au calendrier Android/iOS. Ces essais physiques ne sont pas revendiqués ici.</p></section>
<details><summary>Technique, droits, limites et retour arrière</summary><p>Branche <code>feat/pose-sharing-lot5</code>, issue du Lot 4 validé. Aucun déploiement Production, fusion ou AAB. IA+ reste fermé.</p><p><b>Une migration en recette</b> : ajout de <code>pose_project_id</code> dans le partage privé existant, aperçu sécurisé, envoi idempotent et gestion du retrait. Pas de nouveau modèle de pose, de messagerie, de calendrier ni de partage parallèle.</p><p>Les fonctions publiques vérifient l’identité, la propriété, la révision et les droits sociaux. Le système existant contrôle la connexion et la PO destinataire. Les routes web et natives ouvrent une fiche autorisée, sans token donnant accès aux données.</p><p>Free conserve sa fiche personnelle et son DIY. Envoyer à une PO reste Plus/Pro. Les imports photo/tenue gardent leurs droits, indépendamment d’IA+.</p><p>Les liens natifs nécessitent l’application installée ; aucun nouvel hébergement ou universal link public n’est déployé. Une image jointe référence le média privé existant. Le serveur refuse toute nouvelle lecture après retrait ; une fiche déjà affichée est revérifiée au retour au premier plan et chaque minute.</p><p>Le retour arrière recommandé restaure l’interface du commit parent et conserve l’extension SQL additive pour maintenir les liens de suppression. La procédure complète, les fichiers et les résultats sont dans <code>docs/pose-lot5/DELIVERY.md</code>.</p><p>Les alertes de sécurité antérieures de recette restent documentées ; aucune nouvelle alerte propre à ce lot. Les modules lourds signalés par Vite restent un point d’optimisation, le QR étant chargé à la demande.</p></details><p class="signature">Même app. Différents moods.<br>Toujours toi. ♡</p></main><script>
const tabs=[...document.querySelectorAll('[role=tab]')];function select(tab){for(const b of tabs){const active=b===tab;b.setAttribute('aria-selected',active);document.getElementById(b.dataset.mood).hidden=!active;}}
for(const [i,tab] of tabs.entries()){tab.addEventListener('click',()=>select(tab));tab.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;select(tabs[j]);tabs[j].focus();}});}
</script></html>'''
document=document.replace('STYLE',style).replace('TABS',tabs).replace('SHOTS',shots).replace('CHECKS',checks)
for key,name,alt in [('PREVIEW','apercu-po.png','Aperçu avant confirmation du partage PO'),('RECEIVED','fiche-recue-po.png','Fiche ouverte par le compte Pro destinataire'),('QRCODE','partage-qr.png','Partage privé, copie de lien et QR local'),('DENIED','acces-refuse.png','Accès refusé à un compte tiers')]:document=document.replace(key,'<div class="shot">'+picture(name,alt)+'</div>')
p=out/'NailMoods-Lot5-Fiche-Pose.html';p.write_text(document);print(str(p));print(p.stat().st_size)
