#!/usr/bin/env python3
"""Reproduce the static, public Phase 14D legal pages. No account or backend changes."""
from pathlib import Path
import json
import shutil

root = Path(__file__).resolve().parents[1]
out = root / 'public/legal'
archive = out / 'archives/2026-09-22'
archive.mkdir(parents=True, exist_ok=True)
for name in ('conditions-0.3-beta.html', 'confidentialite-0.4-beta.html', 'informations-0.3-beta.html', 'editor.json', 'editor.js'):
    if not (archive / name).exists():
        shutil.copy2(out / name, archive / name)

css = '''*{box-sizing:border-box}html{color-scheme:light}body{margin:0;background:#fdfaf7;color:#352c32;font:17px/1.7 system-ui,sans-serif}main,header,footer{max-width:820px;margin:auto;padding:24px}header{display:flex;align-items:center;gap:18px;border-bottom:1px solid #ead8e1}header img{width:44px;height:44px;object-fit:contain}a{color:#823b5c;text-underline-offset:3px}h1,h2{font-family:Georgia,serif;font-weight:400;line-height:1.2}h1{font-size:clamp(32px,7vw,46px)}h2{font-size:27px;margin-top:36px}.meta{color:#71636b;font-size:14px}.notice{padding:18px 22px;background:#f5e6ed;border-radius:18px;border:1px solid #e5ccd7}.button{display:inline-block;background:#823b5c;color:white;padding:12px 20px;border-radius:14px;text-decoration:none;font-weight:600;margin:8px 0}li{margin:10px 0}nav{display:flex;flex-wrap:wrap;gap:12px 22px;font-size:15px}footer{border-top:1px solid #ead8e1;color:#71636b;font-size:14px}td,th{text-align:left;padding:12px;border-bottom:1px solid #ead8e1;vertical-align:top}table{border-collapse:collapse;width:100%;font-size:15px}p,li,td{overflow-wrap:anywhere}:focus-visible{outline:3px solid #823b5c;outline-offset:4px}'''
(out / 'legal.css').write_text(css + '\n')
nav = '<nav aria-label="Informations NailMoods"><a href="confidentialite.html">Confidentialité</a><a href="conditions.html">CGU</a><a href="support.html">Support</a><a href="suppression-compte.html">Supprimer mon compte</a><a href="informations.html">Mentions légales</a></nav>'
def page(filename, title, body, version='Mise à jour : 28 septembre 2026'):
    html = f'''<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{title} de NailMoods. Informations publiques accessibles sans compte."><title>{title} — NailMoods</title><link rel="stylesheet" href="legal.css"></head>
<body><header><img src="../nailmoods-symbol.png" alt=""><a href="../">NailMoods</a></header><main><h1>{title}</h1><p class="meta">{version}</p>{body}</main><footer>{nav}<p>NailMoods · Explore. Crée. Ressens.</p></footer></body></html>'''
    (out / filename).write_text(html + '\n')

privacy = '''<p class="notice">Cette politique s’applique à la bêta NailMoods sur le web et Android. Les données Production et Recette sont séparées. Les fonctionnalités et vos choix déterminent les données utilisées.</p>
<h2>1. Qui est responsable ?</h2><p>La bêta NailMoods est portée par Marie Chatelain, personne physique, en France. Une activité sous le régime de la micro-entreprise est prévue ; son immatriculation reste à confirmer. Pour toute question ou l’exercice de vos droits : <a href="mailto:contact@nailmoods.com">contact@nailmoods.com</a>. Les informations professionnelles à publier figurent dans les <a href="informations.html">mentions légales</a>.</p>
<h2>2. Quelles données, pour quoi faire ?</h2><table><thead><tr><th>Données et usage</th><th>Base juridique</th></tr></thead><tbody>
<tr><td>Adresse email, identifiant de compte, authentification, offre et préférences : créer le compte, maintenir la session et fournir les fonctionnalités accessibles.</td><td>Exécution du service demandé.</td></tr>
<tr><td>Prénom ou pseudonyme, profil, ville professionnelle facultative, tranche d’âge lorsque demandée, collections, couleurs, matériel, idées, dessins, favoris, journal et photos : personnalisation, sauvegarde et synchronisation.</td><td>Exécution du service demandé. Vous choisissez les contenus ajoutés.</td></tr>
<tr><td>Profil découvrable, publications publiques, connexions, messages et partages : fonctionnalités communautaires selon l’âge et l’offre.</td><td>Exécution des fonctionnalités demandées.</td></tr>
<tr><td>Tickets de support, pièces jointes choisies et diagnostics transmis volontairement : répondre à une demande.</td><td>Exécution du service ; intérêt légitime à résoudre les incidents.</td></tr>
<tr><td>Signalements, éléments signalés et décisions de modération ; traces techniques d’accès et de sécurité des hébergeurs.</td><td>Intérêt légitime à protéger les personnes et le service ; obligations légales applicables.</td></tr>
<tr><td>Événements d’usage pseudonymisés : sessions, activation, génération, Collection, Journal, social et erreurs techniques agrégées.</td><td>Votre consentement, facultatif et révocable.</td></tr></tbody></table>
<p>L’inscription actuelle ne demande pas d’année de naissance. Une tranche d’âge peut être demandée lors des choix qui la nécessitent. Free est destiné aux personnes de 15 ans ou plus ; Plus et Pro aux adultes de 18 ans ou plus. Les personnes de 15 à 17 ans disposent d’usages personnels privés, sans fonctionnalités sociales.</p>
<h2>3. Photos, caméra et stockage local</h2><p>La caméra ou le sélecteur de photos sont utilisés à votre initiative pour scanner, importer ou joindre une image. L’application ne parcourt pas automatiquement votre galerie. Le système peut demander une autorisation au moment de l’action. Les photos que vous décidez de sauvegarder ou de partager sont transmises au stockage du service ; la reconnaissance OCR et le dessin sont traités dans l’application. Aucun contenu privé, photo, dessin ou texte de message n’est envoyé dans les événements analytics.</p><p>Des préférences, sessions et brouillons sont conservés sur votre appareil. Les brouillons strictement locaux au navigateur ne sont pas automatiquement transférés vers l’application Android. Une désinstallation ou un effacement du stockage local peut les retirer : sauvegardez les éléments importants dans votre compte avant cette opération.</p>
<h2>4. Ce qui est privé ou visible</h2><p>Les collections, dessins et journaux personnels sont privés. Une pose est rendue publique par une action explicite de publication. Les publications publiques peuvent être consultées par d’autres utilisatrices autorisées, même sans connexion ou amitié. Repasser une publication en privé retire son accès public dans NailMoods.</p><p>Pour les comptes adultes éligibles aux fonctionnalités sociales, le profil peut être découvrable par les autres membres selon les règles de visibilité de l’offre et du profil. Les informations que vous y ajoutez peuvent donc être visibles dans la recherche de personnes. Les messages restent destinés à leurs participantes ; les contenus privés n’alimentent pas le fil public. Le blocage et le signalement sont accessibles depuis les fonctionnalités sociales.</p><p>Le personnel habilité traite les tickets, les signalements et leurs éléments associés. Le service n’offre pas au staff une consultation générale des collections, journaux ou conversations privées. Les accès techniques nécessaires à la maintenance et à la sécurité restent réservés aux personnes autorisées.</p>
<h2>5. Hébergement et destinataires</h2><p>Supabase assure l’authentification, la base et le stockage. Les projets utilisés pour Production et Recette sont hébergés dans la région Paris (eu-west-3). GitHub Pages héberge le site web et les pages publiques. Ces prestataires peuvent traiter des informations techniques, notamment l’adresse IP et des journaux de connexion, pour fournir et sécuriser leurs services.</p><p>Des opérations de support ou sous-traitants de ces fournisseurs peuvent impliquer des transferts hors de l’Espace économique européen. Les garanties applicables sont décrites dans leurs documents contractuels, notamment les clauses contractuelles types lorsque nécessaires : <a href="https://supabase.com/privacy">confidentialité Supabase</a>, <a href="https://supabase.com/downloads/docs/Supabase%2BDPA%2B260317.pdf">accord de traitement Supabase</a> et <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">confidentialité GitHub</a>.</p><p>L’ouverture volontaire d’un site marchand, d’une URL produit ou d’un lien externe transmet les informations techniques habituelles à ce site. Ses propres règles s’appliquent. La bêta n’intègre pas de SDK de publicité, de paiement ni de notifications. NailMoods ne vend pas vos données.</p>
<h2>6. Durées de conservation</h2><ul><li><b>Compte et contenus :</b> pendant l’utilisation du compte, jusqu’à leur suppression ou celle du compte.</li><li><b>Suppression :</b> le parcours retire les médias associés du stockage avant de finaliser la suppression du compte. Les messages texte déjà envoyés peuvent rester chez leurs destinataires sous la mention « Compte supprimé ». Les copies exportées ou captures réalisées par d’autres personnes ne peuvent pas être effacées à distance.</li><li><b>Support :</b> objectif de conservation de trois mois en base active pour les dossiers clos. Les dossiers ouverts restent conservés jusqu’à leur résolution. La purge des dossiers clos nécessite encore un contrôle opérationnel et n’est pas présentée comme automatique.</li><li><b>Signalements et décisions :</b> objectif de douze mois après création pour les dossiers traités, avec contrôle opérationnel de purge. Une conservation justifiée par un litige ou une obligation légale peut être nécessaire.</li><li><b>Analytics consentis :</b> événements détaillés conservés au maximum treize mois ; agrégats quotidiens au maximum vingt-cinq mois, avec purge planifiée.</li><li><b>Copies techniques, sauvegardes et sécurité :</b> des résidus peuvent subsister selon les cycles des hébergeurs ou en cas d’obligation légale. Ils ne doivent pas servir à restaurer l’usage d’un compte supprimé. Le calendrier applicable peut être demandé au contact confidentialité ; la procédure de contrôle doit être finalisée avant l’ouverture de la bêta externe.</li></ul>
<h2>7. Vos choix et vos droits</h2><p>Vous pouvez refuser ou retirer le consentement aux statistiques depuis les réglages de confidentialité, sans perdre l’accès aux fonctions essentielles. Aucun consentement optionnel n’est activé par une simple mise à jour. L’application conserve la version des textes acceptés.</p><p>Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, la portabilité, ainsi que vous opposer aux traitements fondés sur l’intérêt légitime selon les conditions applicables. Utilisez l’export et la suppression depuis votre compte, ou écrivez à <a href="mailto:contact@nailmoods.com">contact@nailmoods.com</a>. Une réponse est apportée en principe sous un mois ; une prolongation motivée vous serait annoncée dans ce délai. Une vérification proportionnée de votre identité peut être nécessaire. N’envoyez jamais votre mot de passe.</p><p>Vous pouvez aussi adresser une réclamation à la <a href="https://www.cnil.fr/fr/adresser-une-plainte">CNIL</a>. Pour supprimer votre compte sans ouvrir l’application, utilisez la <a href="suppression-compte.html">page publique de suppression de compte</a>.</p>
<h2>8. Historique</h2><p>Cette précision éditoriale du 28 septembre 2026 corrige la structure juridique envisagée, les données d’âge réellement demandées, la visibilité du profil et les durées analytics. Elle ne modifie aucun consentement enregistré. Le <a href="archives/2026-09-22/confidentialite-0.4-beta.html">texte du 22 septembre 2026</a> est conservé pour traçabilité. Toute évolution des finalités ou des consentements fera l’objet d’une information et, lorsque nécessaire, d’un nouveau choix.</p>'''

terms = '''<p class="notice">NailMoods est proposé en bêta, sans paiement ni abonnement commercial actif. Les droits Free, Plus et Pro peuvent être ouverts aux comptes de test. Aucune facturation Google Play ou Apple n’est proposée dans cette phase.</p>
<h2>1. Objet et éditeur</h2><p>NailMoods permet de conserver ses couleurs et produits, imaginer des poses, dessiner, tenir un journal personnel et, selon l’offre et l’âge, utiliser les fonctions communautaires. La bêta est portée par Marie Chatelain, personne physique. Une activité sous le régime de la micro-entreprise est prévue ; son immatriculation reste à confirmer. Voir les <a href="informations.html">mentions légales</a>.</p>
<h2>2. Compte et âge</h2><ul><li>Free : à partir de 15 ans.</li><li>Plus et Pro : réservés aux personnes de 18 ans ou plus.</li><li>De 15 à 17 ans, les usages Free sont personnels et privés : collection, préférences, idées, journal, poses et gestion du compte. Aucun profil public, publication publique, recherche de personnes, connexion, messagerie ou partage social n’est accessible.</li></ul><p>Une tranche d’âge peut être demandée lorsqu’elle est nécessaire à l’accès aux fonctionnalités. L’inscription actuelle ne demande pas d’année de naissance. Il est interdit de contourner ces règles ou de créer un compte pour une personne de moins de 15 ans. Aucun parcours de consentement parental n’est proposé dans cette bêta. Conservez vos identifiants confidentiels.</p>
<h2>3. Vos contenus</h2><p>Vous conservez vos droits sur vos photos, dessins et textes. N’importez et ne partagez que des contenus dont vous détenez les droits ou les autorisations nécessaires, notamment pour l’image d’une autre personne. Vous accordez à NailMoods uniquement les droits techniques nécessaires pour héberger, sauvegarder, afficher et transmettre vos contenus selon vos choix et les fonctionnalités demandées.</p><p>Le journal et les photos personnelles sont privés. Une pose devient publique après publication explicite ; le retour en privé retire l’accès public dans le service. Une publication publique peut être vue par d’autres utilisatrices autorisées, même sans connexion ou amitié. Les profils adultes éligibles aux fonctions sociales peuvent être découvrables selon les règles de visibilité. Les messages sont destinés à leurs participantes.</p>
<h2>4. Communauté et modération</h2><p>Les connexions sont acceptées explicitement. Vous pouvez retirer une connexion, bloquer ou débloquer un profil, et signaler un profil, une publication ou un message depuis les commandes disponibles. Le support reste accessible pour une difficulté de signalement.</p><p>Sont interdits : harcèlement, menaces, haine ou discrimination, exploitation ou sexualisation de mineurs, contenus sexuels explicites, violence illicite, usurpation d’identité, spam, fraude, atteintes à la vie privée ou aux droits d’autrui et tout contenu illégal. Ne publiez pas d’informations confidentielles sur une autre personne.</p><p>Le staff examine les signalements et peut retirer un contenu, limiter ou suspendre un accès, ou fermer un compte pour abus, sécurité ou obligation légale. Une contestation peut être adressée au <a href="support.html">support</a>. Le signalement n’est pas un service d’urgence.</p>
<h2>5. Idées, dessins et disponibilité</h2><p>Les rendus sont des illustrations d’inspiration, pas une garantie de résultat réel. Les couleurs peuvent varier selon l’écran et le produit. Respectez les instructions du fabricant et les règles de sécurité de vos produits. NailMoods ne remplace pas les conseils d’un professionnel compétent.</p><p>La bêta peut comporter des anomalies ou être interrompue. Sauvegardez et exportez les éléments importants. Les droits impératifs des utilisatrices restent applicables ; aucune clause n’exclut une responsabilité qui ne peut légalement l’être. Le nom, l’identité visuelle et les éléments propres à NailMoods restent protégés.</p>
<h2>6. Données, départ et contact</h2><p>La <a href="confidentialite.html">politique de confidentialité</a> décrit les traitements, destinataires, durées et droits. Vous pouvez exporter vos données et supprimer votre compte depuis Profil → Gérer mon compte → Confidentialité et mes données, ou demander la suppression depuis la <a href="suppression-compte.html">page publique</a>. Les messages texte déjà envoyés peuvent subsister chez leurs destinataires sous « Compte supprimé » ; les copies externes ne peuvent pas être effacées à distance.</p><p>Contact : <a href="mailto:contact@nailmoods.com">contact@nailmoods.com</a>. Les précisions du 28 septembre corrigent les mentions juridiques et décrivent le fonctionnement existant, sans changer les consentements enregistrés. La <a href="archives/2026-09-22/conditions-0.3-beta.html">version du 22 septembre</a> reste consultable. Une évolution substantielle sera identifiée et portée à votre connaissance.</p>'''

deletion = '''<p class="notice">Vous pouvez demander la suppression de votre compte NailMoods et des données associées sans réinstaller l’application et sans vous connecter sur cette page.</p>
<h2>Depuis NailMoods</h2><ol><li>Ouvrez Profil → Gérer mon compte → Confidentialité et mes données.</li><li>Exportez les données que vous souhaitez conserver.</li><li>Choisissez « Supprimer mon compte », lisez les conséquences, puis saisissez la confirmation demandée.</li></ol>
<h2>Sans accès à l’application</h2><p>Écrivez depuis l’adresse email associée au compte à <a href="mailto:contact@nailmoods.com">contact@nailmoods.com</a>, avec l’objet <b>Suppression de mon compte NailMoods</b>. Indiquez que vous souhaitez supprimer le compte et ses données associées, et précisez Production ou Recette si vous le savez.</p><a class="button" href="mailto:contact@nailmoods.com?subject=Suppression%20de%20mon%20compte%20NailMoods&amp;body=Bonjour%2C%0A%0AJe%20demande%20la%20suppression%20de%20mon%20compte%20NailMoods%20et%20des%20donn%C3%A9es%20associ%C3%A9es.%0AEnvironnement%20%3A%20Production%20%2F%20Recette%20%2F%20je%20ne%20sais%20pas.%0A%0AMerci.">Préparer mon email de suppression</a><p>Ce bouton ouvre votre messagerie ; il n’envoie rien automatiquement. Si aucune messagerie ne s’ouvre, copiez l’adresse et l’objet ci-dessus dans votre service de courrier habituel. N’envoyez ni mot de passe, ni code de connexion.</p><p>Si vous n’avez plus accès à l’email du compte, expliquez-le au support. Une vérification proportionnée sera nécessaire pour éviter qu’une autre personne ne supprime votre compte. Votre demande est traitée en principe sous un mois ; toute prolongation nécessaire vous est expliquée dans ce délai.</p>
<h2>Ce qui est supprimé</h2><p>Le compte d’authentification, le profil, les collections et contenus personnels associés, les dessins et poses sauvegardés, les publications et les médias concernés par le nettoyage du compte. Le parcours de suppression nettoie les médias avant de finaliser le retrait du compte.</p>
<h2>Ce qui peut subsister</h2><p>Les messages texte déjà reçus par d’autres personnes peuvent rester dans leurs conversations sous « Compte supprimé ». Des éléments nécessaires au traitement d’un signalement, à un litige ou à une obligation légale, ainsi que des copies techniques temporaires, peuvent être conservés selon la <a href="confidentialite.html">politique de confidentialité</a>. Les copies téléchargées ou captures réalisées par d’autres personnes échappent au contrôle de NailMoods.</p><p>La suppression du compte ne nettoie pas à distance tous les appareils ou anciens navigateurs. Vous pouvez retirer leurs données locales dans les réglages de l’appareil ou du navigateur, après avoir conservé ce qui vous est utile.</p>'''

support = '''<p>Une difficulté avec NailMoods, une question sur votre compte, une demande de suppression ou un signalement ?</p><a class="button" href="mailto:contact@nailmoods.com?subject=Aide%20NailMoods">Contacter le support</a><p>Email : <a href="mailto:contact@nailmoods.com">contact@nailmoods.com</a>. Si votre messagerie ne s’ouvre pas, copiez cette adresse dans votre service de courrier.</p><h2>Pour nous aider à comprendre</h2><p>Précisez l’écran concerné, ce que vous attendiez, ce qui s’est passé et, si vous le connaissez, le numéro de version de NailMoods. Une capture est facultative : masquez les messages et informations privées qui ne sont pas nécessaires. Ne transmettez jamais votre mot de passe ou un code reçu par email.</p><h2>Dans l’application</h2><p>Utilisez « Aide &amp; Support » pour retrouver l’aide et envoyer une demande. Pour un contenu ou comportement problématique, utilisez « Signaler » depuis le profil, la publication ou le message concerné. Le blocage permet de limiter les interactions ; le support peut aider si la commande est inaccessible.</p><h2>Sans compte ni application</h2><p>Cette page et l’adresse email restent accessibles. Vous pouvez <a href="suppression-compte.html">demander la suppression de votre compte</a> ou exercer vos droits relatifs aux données par email. Consultez aussi la <a href="confidentialite.html">politique de confidentialité</a> et les <a href="conditions.html">CGU</a>.</p>'''

info = '''<p class="notice">La bêta NailMoods est portée par une personne physique. Une activité sous le régime de la micro-entreprise est prévue ; son immatriculation reste à confirmer.</p><h2>Édition et contact</h2><p>NailMoods — Marie Chatelain, personne physique, en France.<br>Contact support et données personnelles : <a href="mailto:contact@nailmoods.com">contact@nailmoods.com</a>.</p><p>Le statut administratif et les coordonnées de publication applicables restent à finaliser avant l’ouverture de la bêta externe. Le choix d’un compte développeur personnel sur Google Play ne détermine pas, à lui seul, le caractère professionnel ou non de l’activité.</p><h2>Hébergement</h2><p>Le site et les pages publiques sont hébergés par GitHub Pages, service de GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, États-Unis. <a href="https://support.github.com/">Contact GitHub</a>.</p><p>L’authentification, la base de données et le stockage des médias utilisent Supabase, avec des projets en région Paris (eu-west-3). Voir la <a href="confidentialite.html">politique de confidentialité</a> pour les traitements et transferts éventuels.</p><h2>Conditions de la bêta</h2><p>Aucun paiement ni abonnement commercial n’est actif dans cette phase. Les <a href="conditions.html">CGU</a> et la <a href="confidentialite.html">politique de confidentialité</a> sont accessibles sans compte. Ces pages ne constituent pas une annonce d’ouverture publique.</p>'''
page('confidentialite.html', 'Politique de confidentialité', privacy, 'Référence 0.4-beta · Précisions éditoriales : 28 septembre 2026')
page('conditions.html', 'Conditions d’utilisation', terms, 'Référence 0.3-beta · Précisions éditoriales : 28 septembre 2026')
page('support.html', 'Aide et support', support)
page('suppression-compte.html', 'Supprimer mon compte NailMoods', deletion)
page('informations.html', 'Mentions légales', info)
for old, new in [('conditions-0.3-beta.html','conditions.html'),('confidentialite-0.4-beta.html','confidentialite.html'),('informations-0.3-beta.html','informations.html')]:
    shutil.copy2(out / new, out / old)
# The old 0.1 texts remain accessible as history, but cannot be mistaken for current rules.
for name in ['conditions-0.1-beta.html', 'confidentialite-0.1-beta.html']:
    p = out / name
    original = p.read_text()
    if 'Texte historique — remplacé' not in original:
        marker = '<p class="notice"><b>Texte historique — remplacé.</b> Ne décrit pas les règles actuelles. Consultez les <a href="conditions.html">CGU actuelles</a> et la <a href="confidentialite.html">politique actuelle</a>.</p>'
        original = original.replace('<h1>', marker + '<h1>', 1)
        p.write_text(original)
editor = {
    'editorType': 'individual_creation_pending',
    'publicLegalName': 'NailMoods — projet porté par Marie Chatelain',
    'companyLegalForm': 'Personne physique ; micro-entreprise prévue, immatriculation à confirmer',
    'companyRegistrationNumber': 'Non attribué dans le justificatif disponible',
    'privacyContactEmail': 'contact@nailmoods.com',
    'supportContactEmail': 'contact@nailmoods.com',
    'publishedProfessionalAddress': 'À renseigner avant ouverture de la bêta externe',
    'retentionPolicy': 'Analytics : 13 mois détaillés, 25 mois agrégés. Support clos : objectif 3 mois ; signalements traités : objectif 12 mois ; contrôle opérationnel de purge à finaliser.',
    'accountDeletionProcedure': 'Dans le compte ou depuis la page publique legal/suppression-compte.html. Les messages texte déjà reçus peuvent subsister sous Compte supprimé.',
    'termsVersion': '0.3-beta', 'privacyVersion': '0.4-beta',
    'effectiveDate': '28 septembre 2026',
    'notice': 'Coordonnées professionnelles, immatriculation et procédure de conservation à finaliser avant ouverture de la bêta externe.'
}
(out / 'editor.json').write_text(json.dumps(editor, ensure_ascii=False, indent=2) + '\n')
(out / 'editor.js').write_text("// Legacy document hook. Current pages have accessible static content.\nconst target = document.getElementById('legal-editor');\nif (target) { const link = document.createElement('a'); link.href = 'informations.html'; link.textContent = 'Mentions légales actuelles de NailMoods'; target.replaceChildren(link); }\n")
for archived in archive.glob('*.html'):
    text = archived.read_text()
    if 'Archive du 22 septembre' not in text:
        notice = '<p class="notice"><b>Archive du 22 septembre 2026.</b> Certaines mentions sont obsolètes. Consultez les <a href="../../conditions.html">CGU actuelles</a> et la <a href="../../confidentialite.html">politique actuelle</a>.</p>'
        text = text.replace('<h1>', notice + '<h1>', 1)
        archived.write_text(text)
print('Static public legal pages prepared; no backend, consent, account or storage mutation.')
