export const PROFESSIONS=[['nail_artist','Nail Artist / PO','Des créations, un savoir-faire, ton univers.'],['product_creator','Créateur de produits','Tes pièces, tes collections, ton identité.'],['brand','Marque','Tes gammes et les créations qui leur donnent vie.'],['educator_creator','Formateur / Créateur de contenu','Tes techniques, tes tutoriels, ton inspiration.'],['other_professional','Autre activité','Une vitrine à ton image.']];
export const STRUCTURES=[['solo','Solo'],['institute','Institut'],['creator_team','Équipe créatrice'],['brand_team','Équipe de marque']];
export const proLabel=id=>PROFESSIONS.find(([k])=>id===k)?.[1]||STRUCTURES.find(([k])=>id===k)?.[1]||'Professionnel';
export const roleLabel=id=>({owner:'Propriétaire',admin:'Responsable',member:'Membre'})[id]||'Membre';
export const hasProducts=type=>['product_creator','brand'].includes(type);
export function safeLink(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
export function exactCatalogProduct(item,catalog){if(!item?.catalogReference)return null;return catalog.find(p=>String(p.catalogId)===item.catalogReference)||null;}
export function normalizeDraft(space={}) {return {id:space.id||null,name:space.name||'',handle:space.handle||'',professionalType:space.professionalType||'',organizationType:space.organizationType||'solo',isPublic:space.isPublic===true,fields:{bio:space.bio||'',city:space.city||'',country:'',website:'',instagram:'',shop:'',cover:'',universes:[],specialties:[],...(space.fields||{})},visibility:{...(space.visibility||{})}};}
export const errorMessage=e=>({choose_profession_structure:'Choisis ton activité et ta structure.',invalid_handle:'Choisis un identifiant de 3 à 30 caractères : lettres, chiffres, points ou tirets bas.',handle_unavailable:'Cet identifiant est déjà utilisé.',showcase_editor_required:'Tu ne peux pas modifier cette vitrine.',workspace_full:'Tous les sièges sont occupés. Aucune facturation supplémentaire n’est activée.',entitlement_inactive:'Les sièges de cette structure ne sont pas actifs.',documented_source_required:'Ajoute la source fabricant des informations techniques.',invalid_public_url:'Utilise un lien complet commençant par https://.',team_must_be_empty:'Retire ou transfère les membres avant de passer en solo.',FEATURE_REQUIRES_PRO:'Cette fonction nécessite un accès Pro.',staff_required:'Cette action est réservée à l’équipe NailMoods.'})[e?.message]||'La modification n’a pas pu être enregistrée. Tes saisies sont conservées.';
