import React,{useEffect,useState} from 'react';
import {proService} from './service';
import {salonService,contributionLabel} from './salonService';
import {TeamEditor} from './ProManager';
import {normalizeDraft,errorMessage} from './model';
import PublicProfile from '../identity/PublicProfile';
import './salon.css';
export default function SalonPanel({client,userId,tier}){
 const [state,setState]=useState(null),[selected,setSelected]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[handle,setHandle]=useState(''),[preview,setPreview]=useState(''),[tab,setTab]=useState('gallery');
 const service=salonService(client),pro=proService(client);
 async function refresh(){const next=await service.state();setState(next);setSelected(s=>next.spaces.some(w=>w.id===s)?s:next.spaces[0]?.id||'');return next;}
 useEffect(()=>{let alive=true;service.state().then(s=>{if(alive){setState(s);setSelected(s.spaces[0]?.id||'');}}).catch(()=>{if(alive)setNotice('Le salon ne peut pas être chargé. Réessaie.');});return()=>{alive=false;};},[client,userId]);
 async function run(fn,message='Modification enregistrée.'){setBusy(true);setNotice('');try{await fn();await refresh();setNotice(message);}catch(e){setNotice(errorMessage(e));}finally{setBusy(false);}}
 const space=state?.spaces.find(w=>w.id===selected),admin=space&&['owner','admin'].includes(space.role);
 const act=(action,source,data)=>run(()=>service.action(space.id,action,source,data));
 return <section className="salonPanel" aria-labelledby="salon-title"><h2 id="salon-title">Mon salon</h2><p>Ton compte, tes clientes et ta galerie restent personnels. Partage ici les réalisations choisies avec ton équipe.</p>
 {notice&&<p role="status">{notice}</p>}{!state&&!notice&&<p role="status">Chargement du salon…</p>}
 {state?.inbox.map(i=><article key={i.id} className="salonRow"><b>Invitation · {i.workspace_name}</b>{['accept','decline'].map(a=><button key={a} disabled={busy} onClick={()=>run(()=>pro.team(i.workspace_id,a,{invitationId:i.id}))}>{a==='accept'?'Accepter':'Refuser'}</button>)}</article>)}
 {state&&<><nav className="salonTabs" aria-label="Mes salons">{state.spaces.map(w=><button key={w.id} aria-pressed={selected===w.id} onClick={()=>setSelected(w.id)}>{w.name}</button>)}</nav>
 {!space&&tier==='pro'&&<form onSubmit={e=>{e.preventDefault();run(async()=>{const d=normalizeDraft();await pro.save(null,{...d,name,handle,professionalType:'nail_artist',organizationType:'institute',isPublic:false});},'Salon créé, privé. Sa capacité est attribuée par le serveur ; aucun achat Salon n’est ouvert.');}}><label>Nom du salon<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>Identifiant NailMoods<input required maxLength={30} value={handle} autoCapitalize="none" onChange={e=>setHandle(e.target.value)}/></label><button disabled={busy}>Créer mon salon</button></form>}
 {!space&&tier!=='pro'&&<p>Accepte une invitation pour rejoindre ton salon. Ton accès personnel reste conservé.</p>}
 {space&&<><div className="salonRow"><h3>{space.name}</h3>{space.isPublic&&<button onClick={()=>setPreview(space.handle)}>Voir la vitrine</button>}<small>{space.seats.active} / {space.seats.limit} places confirmées</small></div>
 {!space.operational&&<p role="status">L’accès Salon est suspendu ou expiré. Tes créations restent dans ta galerie.</p>}
 <nav className="salonTabs" aria-label="Galeries"><button aria-pressed={tab==='gallery'} onClick={()=>setTab('gallery')}>Ma galerie</button><button aria-pressed={tab==='showcase'} onClick={()=>setTab('showcase')}>Vitrine du salon</button><button aria-pressed={tab==='team'} onClick={()=>setTab('team')}>Équipe</button></nav>
 {tab==='team'&&<><TeamEditor space={space} service={pro} userId={userId} run={run} refresh={refresh} busy={busy}/>{admin&&<fieldset><legend>Autorisations de publication</legend>{space.members.filter(m=>m.role!=='owner').map(m=><label className="salonRow" key={m.id}><input type="checkbox" disabled={busy||!space.operational} checked={m.canPublish!==false} onChange={e=>act('member_permission',null,{userId:m.id,canPublish:e.target.checked})}/>{m.name} peut proposer ses créations</label>)}</fieldset>}</>}
 {tab==='gallery'&&<><p>Réutilise tes poses et inspirations publiées. Aucune photo n’est copiée.</p>{!state.sources.length&&<p>Enregistre une pose dans ton Journal puis choisis de la publier.</p>}{state.sources.map(s=><article className="salonRow" key={s.kind+s.id}><b>{s.title}</b><button disabled={busy||!space.operational||space.canPublish===false} onClick={()=>run(async()=>{const r=await service.action(space.id,'submit',s);setNotice(contributionLabel(r.status));},space.moderation?contributionLabel('pending'):contributionLabel('published'))}>Ajouter aussi à la vitrine du salon</button></article>)}</>}
 {tab==='showcase'&&<>{admin&&<label className="salonRow"><input type="checkbox" checked={space.moderation} disabled={busy||!space.operational} onChange={e=>act('settings',null,{moderation:e.target.checked})}/>Valider les propositions avant publication</label>}{!space.contributions.length&&<p>Les réalisations de l’équipe apparaîtront ici.</p>}{space.contributions.map(s=><article className="salonContribution" key={s.kind+s.id}><h4>{s.title||'Réalisation'}</h4><small>Par {s.authorName} · {contributionLabel(s.status)}</small>{!s.available&&<p>La création reste privée ou attend la vérification de son image.</p>}{s.authorId===userId?<form onSubmit={e=>{e.preventDefault();act('submit',s,{caption:new FormData(e.target).get('caption')});}}><label>Description de ma contribution<textarea key={s.caption} name="caption" maxLength={1000} defaultValue={s.caption}/></label><button disabled={busy||!space.operational||space.canPublish===false}>Enregistrer et proposer</button><button type="button" disabled={busy} onClick={()=>act('withdraw',s)}>Retirer de la vitrine</button></form>:<p>{s.caption}</p>}{admin&&<div className="salonTabs">{['approve','reject','hide'].map(a=><button key={a} disabled={busy||!space.operational||(a==='approve'&&!s.available)} onClick={()=>act(a,s)}>{{approve:'Approuver',reject:'Refuser',hide:'Masquer'}[a]}</button>)}<label>Position<input type="number" min="0" max="10000" defaultValue={s.position} onBlur={e=>{if(Number(e.target.value)!==s.position)act('order',s,{position:Number(e.target.value)});}}/></label></div>}</article>)}</>}
 {admin&&<p>Pour modifier l’identité, la couverture ou publier le salon, utilise « Mon espace professionnel » ci-dessous.</p>}
 </>}
 </>}{preview&&<PublicProfile client={client} handle={preview} onClose={()=>setPreview('')}/>}</section>;
}
