import PublicPoseBook from '../poseBook/PublicPoseBook.jsx';
import React,{useEffect,useState} from 'react';
import {ArrowUpRight,MapPin,ShieldCheck,Flower2,Package,Users,BookOpen} from 'lucide-react';
import {UniverseTiles} from '../design/ProfileModules.jsx';
import ContentImage from '../social/ContentImage.jsx';
import {ConnectionAction} from '../social/SocialHub.jsx';
import {SafetyActions} from '../support/SafetyActions.jsx';
import {track} from '../analytics/analytics.js';
import {loadCatalog} from '../catalog.js';
import {proLabel,roleLabel,hasProducts,safeLink,exactCatalogProduct} from './model.js';
import {proService} from './service.js';
import './professional-v2.css';
export function ProImage({client,path,alt='',onLoaded}){const [url,setUrl]=useState('');useEffect(()=>{let alive=true;setUrl('');if(path)proService(client).image(path).then(u=>{if(alive)setUrl(u);}).catch(()=>{});return()=>{alive=false;};},[client,path]);return url?<img className="proV2Media" src={url} alt={alt} loading="lazy" onLoad={onLoaded}/>:<span className="proV2ImageEmpty" aria-label={alt||'Image non renseignée'}><Flower2 aria-hidden="true"/></span>;}
export function ProfessionalHero({client,profile}){const p=profile.professional,f=p.fields||{};return <header className="proV2Hero"><div className="proV2Cover">{f.cover?<ProImage client={client} path={f.cover} alt="Couverture de la vitrine"/>:<div className="proV2CoverArt" aria-hidden="true"><img src={import.meta.env.BASE_URL+'nailmoods-symbol.png'} alt=""/><span>Un univers.<br/><em>Une signature.</em></span></div>}</div><div className="proV2Identity"><div className="proV2Avatar"><ContentImage client={client} kind="avatar" id={profile.handle} title={profile.displayName}/></div><span className="proV2Eyebrow">{p.organizationType==='institute'?'Institut · ':''}{proLabel(p.type)}</span><h2>{profile.displayName}</h2><p>@{profile.handle}{p.verified&&<span className="proV2Verified"><ShieldCheck size={16}/> Identité vérifiée</span>}</p>{(f.city||f.country)&&<p className="proV2Location"><MapPin size={16}/>{[f.city,f.country].filter(Boolean).join(' · ')}</p>}{f.bio&&<p className="proV2Bio">{f.bio}</p>}</div></header>;}
export function UniverseBlock({values=[]}){return values.length?<section className="proV2Block"><small className="proV2Eyebrow">CE QUI M’INSPIRE</small><h3>Notre univers</h3><UniverseTiles values={values}/></section>:null;}
export function SpecialtiesBlock({values=[]}){return values.length?<section className="proV2Block"><h3>Spécialités</h3><p className="proV2Muted">Déclarées par la professionnelle.</p><div className="proV2Chips">{values.map(v=><span key={v}>{v}</span>)}</div></section>:null;}
export function TeamBlock({team=[],onOpen}){return team.length?<section className="proV2Block"><small className="proV2Eyebrow">DES TALENTS, UNE IDENTITÉ</small><h3>Notre équipe</h3><div className="proV2Team">{team.map(m=><button key={m.handle} onClick={()=>onOpen?.(m.handle)}><span className="proV2Initial">{m.name?.[0]||'N'}</span><span><b>{m.name}</b><small>@{m.handle}</small><small>{roleLabel(m.role)}</small></span><ArrowUpRight size={18}/></button>)}</div></section>:null;}
export function ProfessionalPortfolio({client,entries=[],products=[]}){const [filter,setFilter]=useState('');const tags=[...new Set(entries.flatMap(e=>Object.values(e.preview?.publicTags||{}).flat().concat(e.preview?.technique||[])))].filter(v=>typeof v==='string');const visible=filter?entries.filter(e=>JSON.stringify(e.preview).includes(filter)):entries;return <section className="proV2Block proV2Wide"><small className="proV2Eyebrow">LE SAVOIR-FAIRE EN IMAGES</small><h3>Les créations</h3>{tags.length>0&&<div className="proV2Chips"><button aria-pressed={!filter} onClick={()=>setFilter('')}>Toutes</button>{tags.map(t=><button key={t} aria-pressed={filter===t} onClick={()=>setFilter(t)}>{t}</button>)}</div>}{!entries.length?<p className="proV2Empty">Les créations choisies pour cette vitrine apparaîtront ici.</p>:<div className="proV2Portfolio">{visible.map(e=><article key={e.kind+e.id}><ContentImage client={client} kind={e.kind} id={e.id} preview={e.preview} title={e.title}/><div><h4>{e.title}</h4>{e.productId&&products.find(p=>p.id===e.productId)&&<small>Avec {products.find(p=>p.id===e.productId).title}</small>}<SafetyActions client={client} target={{kind:e.kind,id:e.id,label:e.title}}/></div></article>)}</div>}</section>;}
export function ProductShowcase({client,items=[],portfolio=[],onCatalog}){const [open,setOpen]=useState(null),[catalog,setCatalog]=useState([]);useEffect(()=>{loadCatalog().then(setCatalog).catch(()=>{});},[]);return <section className="proV2Block proV2Wide"><small className="proV2Eyebrow">DES PIÈCES À DÉCOUVRIR</small><h3>Produits & créations</h3>{!items.length?<p className="proV2Empty">Les premiers produits de cette vitrine arrivent bientôt.</p>:<div className="proV2Products">{items.map(p=><article key={p.id}><button className="proV2ProductVisual" onClick={()=>{setOpen(open===p.id?null:p.id);track('pro_product_viewed',{category:p.details.category||'other'});}} aria-expanded={open===p.id}>{p.details.photos?.[0]?<ProImage client={client} path={p.details.photos[0]} alt={p.title}/>:p.details.hex?<span className="proV2Swatch" style={{background:p.details.hex}}/>:<Package size={44}/>}</button><div className="proV2ProductCopy"><small>{p.details.category}</small><h4>{p.title}</h4><p>{[p.details.reference,p.details.finish].filter(Boolean).join(' · ')}</p><small>{({verified:'Relation produit vérifiée',claimed:'Relation revendiquée',community:'Fiche communautaire'})[p.claimStatus]}</small><button className="proV2TextButton" onClick={()=>setOpen(open===p.id?null:p.id)}>{open===p.id?'Fermer les détails':'Découvrir le produit'} <ArrowUpRight size={15}/></button>{open===p.id&&<div className="proV2ProductDetails"><p>{p.details.description}</p>{['effects','motifs','dimensions','variants','ean','usage','technical'].map(k=>p.details[k]?<p key={k}><b>{{effects:'Effets',motifs:'Motifs',dimensions:'Dimensions',variants:'Variantes',ean:'EAN',usage:'Utilisation',technical:'Données documentées'}[k]} : </b>{Array.isArray(p.details[k])?p.details[k].join(', '):p.details[k]}</p>:null)}{safeLink(p.details.sourceUrl)&&<a href={safeLink(p.details.sourceUrl)} target="_blank" rel="noopener noreferrer">Source fabricant</a>}{safeLink(p.details.officialUrl)&&<a href={safeLink(p.details.officialUrl)} target="_blank" rel="noopener noreferrer">Fiche officielle <ArrowUpRight size={15}/></a>}{exactCatalogProduct(p,catalog)&&onCatalog&&<button onClick={()=>onCatalog(exactCatalogProduct(p,catalog))}>Ajouter à ma Collection</button>}{portfolio.some(e=>e.productId===p.id)&&<div><b>Créé avec ce produit</b>{portfolio.filter(e=>e.productId===p.id).map(e=><ContentImage key={e.id} client={client} kind={e.kind} id={e.id} preview={e.preview} title={e.title}/>)}</div>}</div>}</div></article>)}</div>}</section>;}
export function CollectionsBlock({items=[],products=[]}){return items.length?<section className="proV2Block proV2Wide"><h3>Les collections</h3><div className="proV2Collections">{items.map(c=><article key={c.id}><small className="proV2Eyebrow">COLLECTION</small><h4>{c.title}</h4><div className="proV2Palette">{(c.details.productIds||[]).map(id=>products.find(p=>p.id===id)).filter(Boolean).map(p=><span key={p.id} title={p.title} style={{background:p.details.hex||'var(--surfaceSecondary)'}}/>)}</div><p>{c.details.description}</p></article>)}</div></section>:null;}
export function PublicationsBlock({client,items=[]}){return items.length?<section className="proV2Block proV2Wide"><h3>À la une & tutoriels</h3><div className="proV2Collections">{items.map(p=><article key={p.id}>{p.details.photos?.[0]&&<ProImage client={client} path={p.details.photos[0]} alt={p.title}/>}<small>{p.details.contentKind||'Inspiration'}</small><h4>{p.title}</h4><p>{p.details.description}</p>{safeLink(p.details.officialUrl)&&<a href={safeLink(p.details.officialUrl)} target="_blank" rel="noopener noreferrer">Découvrir <ArrowUpRight size={16}/></a>}</article>)}</div></section>:null;}
export function SocialLinksBlock({fields={},type}){const links=[['shop','Voir la boutique officielle'],['website','Site officiel'],['instagram','Instagram']].filter(([k])=>safeLink(fields[k]));return links.length?<nav className="proV2Links" aria-label="Liens professionnels">{links.map(([k,label])=><a key={k} href={safeLink(fields[k])} target="_blank" rel="noopener noreferrer" onClick={()=>track('pro_shop_opened',{professional_type:type})}>{label}<ArrowUpRight size={18}/></a>)}</nav>:null;}
export default function Showcase({client,profile,onOpen,onClose,onCatalog,shelf}){const p=profile.professional,items=p.items||[],products=items.filter(i=>i.kind==='product');useEffect(()=>{track('pro_showcase_viewed',{professional_type:p.type});},[profile.handle,p.type]);return <div className="proV2"><ProfessionalHero client={client} profile={profile}/><SocialLinksBlock fields={p.fields} type={p.type}/>{shelf}<div className="proV2Grid"><UniverseBlock values={p.fields?.universes}/><SpecialtiesBlock values={p.fields?.specialties}/><div className="proV2Wide"><PublicPoseBook client={client} profile={profile}/></div>{(p.portfolio||[]).some(e=>e.kind!=='journal')&&<ProfessionalPortfolio client={client} entries={(p.portfolio||[]).filter(e=>e.kind!=='journal')} products={products}/>}<TeamBlock team={p.team} onOpen={onOpen}/>{hasProducts(p.type)&&<><CollectionsBlock items={items.filter(i=>i.kind==='collection')} products={products}/><ProductShowcase client={client} items={products} portfolio={p.portfolio} onCatalog={onCatalog}/></>}<PublicationsBlock client={client} items={items.filter(i=>i.kind==='publication')}/></div><section className="proV2Block"><h3>Entrons en contact</h3><ConnectionAction client={client} handle={profile.handle}/><p className="proV2Muted">Une fois connectées, partage une inspiration ou un projet depuis sa fiche « Envoyer à ma PO ».</p><SafetyActions client={client} target={{kind:'profile',handle:profile.handle,label:profile.displayName}} onBlocked={onClose}/></section></div>;}
