export const CATALOG_STATUS={draft:'Brouillon',submitted:'Soumis',under_review:'En vérification',changes_requested:'À compléter',approved:'Approuvé',rejected:'Refusé',archived:'Archivé'};
export const TECH_FIELDS=[['inci','Liste INCI'],['curing','Catalysation fabricant'],['compatibility','Compatibilité documentée'],['removal','Protocole de dépose'],['warnings','Précautions fabricant']];
export const PRODUCT_FIELDS=[['name','Nom'],['brand','Marque'],['collection','Gamme'],['reference','Référence'],['productKind','Famille produit'],['type','Type de produit'],['finish','Finition'],['opacity','Opacité'],['catalogColor','Couleur HEX officielle'],['ean13','EAN / GTIN'],['sku','SKU'],['url','Page officielle'],['sourceUrl','Source des informations'],['usage','Usage']];
export function productFromItem(item,space){const d=item.details||{};return {name:item.title,brand:space.name,collection:'',reference:d.reference||'',productKind:d.category||'',finish:d.finish||'',catalogColor:d.hex||'',colorValidated:false,ean13:d.ean||'',url:d.officialUrl||'',sourceUrl:d.sourceUrl||'',usage:d.usage||'',photos:d.photos||[],technical:{}};}
export function applyCatalogueOverlay(bundled,rows){const result=new Map(bundled.map(p=>[p.catalogId,p]));for(const r of rows){if(!r?.catalogId)continue;if(r.archived)result.delete(r.catalogId);else if(r.product?.name)result.set(r.catalogId,{...result.get(r.catalogId),...r.product,catalogId:r.catalogId,catalogVersion:'central-'+r.revision});}return [...result.values()];}
export function csvRows(text){const delimiter=(text.split(/\r?\n/)[0].match(/;/g)||[]).length>(text.split(/\r?\n/)[0].match(/,/g)||[]).length?';':',';const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===delimiter&&!quote){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quote)throw Error('Guillemet non fermé dans le CSV.');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}
export function tabularProducts(rows){if(rows.length<2||rows.length>251)throw Error('Prépare entre 1 et 250 produits par import.');const headers=rows[0].map(v=>String(v).replace(/^\uFEFF/,'').trim());if(new Set(headers).size!==headers.length)throw Error('Deux colonnes ont le même nom.');const allowed=new Set(['catalogId',...PRODUCT_FIELDS.map(([k])=>k),'colorValidated',...TECH_FIELDS.flatMap(([k])=>[k,k+'Source',k+'Status'])]);if(headers.some(h=>!allowed.has(h)))throw Error('Une colonne est inconnue. Utilise les noms du modèle CSV.');if(!['catalogId','name','brand'].every(h=>headers.includes(h)))throw Error('Colonnes obligatoires : catalogId, name, brand.');return rows.slice(1).map(row=>{const d={};headers.forEach((h,i)=>{const v=String(row[i]??'').trim();if(v)d[h]=v;});if(d.colorValidated)d.colorValidated=/^(true|oui|1)$/i.test(d.colorValidated);const technical={};for(const [k] of TECH_FIELDS){if(d[k])technical[k]={value:d[k],sourceUrl:d[k+'Source']||'',status:d[k+'Status']||'manufacturer'};delete d[k];delete d[k+'Source'];delete d[k+'Status'];}if(Object.keys(technical).length)d.technical=technical;return d;});}
export async function readImport(file){if(file.size>3*1024*1024)throw Error('Le fichier dépasse 3 Mo. Scinde-le en petits imports.');if(/\.csv$/i.test(file.name))return tabularProducts(csvRows(await file.text()));if(!/\.xlsx$/i.test(file.name))throw Error('Choisis un fichier CSV ou XLSX.');const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const ws=wb.worksheets[0];if(!ws||ws.rowCount>251||ws.columnCount>50)throw Error('Le premier onglet doit contenir au maximum 250 produits et 50 colonnes.');const rows=[];ws.eachRow(row=>{rows.push(row.values.slice(1).map(v=>{if(v&&typeof v==='object')throw Error('Utilise des cellules texte, sans formule, lien ni mise en forme enrichie.');return v??'';}));});return tabularProducts(rows);}
export const IMPORT_TEMPLATE='catalogId;name;brand;collection;reference;productKind;finish;catalogColor;colorValidated;ean13;sourceUrl\n';
