import React,{useRef,useState} from 'react';
import {Undo2,Redo2,X,Trash2,Layers,Check,Image,Flower2,Sticker,Palette,Type} from 'lucide-react';
import Sheet from '../Sheet.jsx';
import {cleanScrapbook,defaultScrapbook,scrapMoods,scrapAssets,scrapBackgrounds,scrapFrames} from './scrapbook.js';
import {ScrapNode,ScrapSprite,pageStyle,nodeStyle} from './ScrapPage.jsx';
import './scrapbook.css';
export default function ScrapEditor({entry,entries,renderVisual,onSave,onClose}){
 const [draft,setDraft]=useState(()=>cleanScrapbook(entry.scrapbook)||defaultScrapbook(entry)),[selected,setSelected]=useState('photo-main'),[tab,setTab]=useState('photos'),[mood,setMood]=useState('all'),[past,setPast]=useState([]),[future,setFuture]=useState([]),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const canvas=useRef(null),drag=useRef(null),current=useRef(draft);current.current=draft;
 const node=draft.nodes.find(n=>n.id===selected);
 function commit(next){next=cleanScrapbook(next);setPast(v=>[...v.slice(-39),current.current]);setFuture([]);setDraft(next);setError('');}
 function edit(change){commit({...draft,nodes:draft.nodes.map(n=>n.id===selected?{...n,...change}:n)});}
 function add(type,data){if(draft.nodes.length>=32){setError('Cette page contient déjà 32 éléments. Retire un décor avant d’en ajouter.');return;}if(type==='photo'&&draft.nodes.filter(n=>n.type==='photo').length>=4){setError('Quatre photos maximum par page.');return;}const id=crypto.randomUUID();commit({...draft,nodes:[...draft.nodes,{id,type,x:type==='photo'?65:type==='sticker'?72:50,y:type==='photo'?64:type==='text'?84:type==='tape'?20:28,w:type==='photo'?42:type==='tape'?35:type==='text'?55:22,rotate:0,...data}]});setSelected(id);}
 function start(e,n){if(e.button!==0||!e.isPrimary)return;e.preventDefault();setSelected(n.id);e.currentTarget.setPointerCapture(e.pointerId);const rect=canvas.current.getBoundingClientRect();drag.current={id:n.id,pointer:e.pointerId,x:e.clientX,y:e.clientY,node:n,rect,before:current.current};}
 function move(e){const d=drag.current;if(!d||d.pointer!==e.pointerId)return;const x=Math.max(8,Math.min(92,d.node.x+(e.clientX-d.x)/d.rect.width*100)),y=Math.max(8,Math.min(92,d.node.y+(e.clientY-d.y)/d.rect.height*100));setDraft(v=>({...v,nodes:v.nodes.map(n=>n.id===d.id?{...n,x,y}:n)}));}
 function end(e,cancel=false){const d=drag.current;if(!d||d.pointer!==e.pointerId)return;drag.current=null;if(cancel){setDraft(d.before);return;}if(Math.abs(e.clientX-d.x)+Math.abs(e.clientY-d.y)>2){setPast(v=>[...v.slice(-39),d.before]);setFuture([]);}}
 function undo(){if(!past.length)return;setFuture(v=>[current.current,...v]);setDraft(past.at(-1));setPast(v=>v.slice(0,-1));}
 function redo(){if(!future.length)return;setPast(v=>[...v,current.current]);setDraft(future[0]);setFuture(v=>v.slice(1));}
 async function save(){if(saving)return;setSaving(true);try{const result=await onSave(cleanScrapbook(current.current));if(result?.ok===false){setError(result.error||'La page n’a pas pu être enregistrée.');return;}onClose();}catch{setError('La page n’a pas pu être enregistrée. Réessaie.');}finally{setSaving(false);}}
 const filter=asset=>mood==='all'||asset.mood===mood;
 return <Sheet title="Composer ma page" onClose={onClose} className="nmScrapEditor"><div className="nmScrapToolbar"><button aria-label="Annuler la dernière modification" disabled={!past.length||saving} onClick={undo}><Undo2 size={18}/></button><button aria-label="Rétablir la modification" disabled={!future.length||saving} onClick={redo}><Redo2 size={18}/></button><button onClick={onClose} disabled={saving}><X size={17}/>Annuler</button><button className="nmScrapFinish" disabled={saving} onClick={save}><Check size={17}/>{saving?'Enregistrement…':'Terminer'}</button></div>
 <p className="nmScrapHint">Déplace les éléments au doigt. Taille et inclinaison se règlent sous la page. Tous les moods peuvent être mélangés.</p>
 {entry.visibility==='public'&&<p className="nmScrapHint">Cette pose est publique : ses décors et tes textes le seront aussi. Les photos de poses privées restent privées.</p>}
 <div ref={canvas} className={'nmScrapCanvas background-'+draft.background.split('-')[1]} style={pageStyle(draft.background)} aria-label="Page à composer">
 {draft.nodes.map(n=><div key={n.id} className={'nmScrapNode type-'+n.type+(selected===n.id?' selected':'')} style={nodeStyle(n)} role="button" tabIndex={0} aria-label={n.type==='photo'?'Photo : '+(entries.find(e=>e.id===n.ref)?.title||'Ma pose'):n.type==='text'?'Texte : '+n.text:'Décor : '+(scrapAssets.find(a=>a.id===n.asset)?.label||n.type)} aria-pressed={selected===n.id} onPointerDown={e=>start(e,n)} onPointerMove={move} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e,true)} onLostPointerCapture={e=>{if(drag.current)end(e,true);}} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();setSelected(n.id);}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();setSelected(n.id);commit({...draft,nodes:draft.nodes.map(v=>v.id===n.id?{...v,x:v.x+(e.key==='ArrowRight'?2:e.key==='ArrowLeft'?-2:0),y:v.y+(e.key==='ArrowDown'?2:e.key==='ArrowUp'?-2:0)}:v)});}}}><ScrapNode node={n} entries={entries} renderVisual={renderVisual} editing/></div>)}
 </div>
 {node&&<div className="nmScrapControls"><label>Taille<input aria-label="Taille de l’élément" type="range" min="10" max="65" value={node.w} onChange={e=>edit({w:Number(e.target.value)})}/></label><label>Inclinaison<input aria-label="Inclinaison de l’élément" type="range" min="-45" max="45" value={node.rotate} onChange={e=>edit({rotate:Number(e.target.value)})}/></label><button onClick={()=>{commit({...draft,nodes:[...draft.nodes.filter(n=>n.id!==selected),node]});}}><Layers size={17}/>Au premier plan</button><button onClick={()=>{commit({...draft,nodes:draft.nodes.filter(n=>n.id!==selected)});setSelected(null);}}><Trash2 size={17}/>Retirer</button>
 {node.type==='photo'&&<label>Cadre<select aria-label="Cadre de la photo" value={node.frame} onChange={e=>edit({frame:e.target.value})}>{scrapFrames.map((f,i)=><option key={f} value={f}>{['Dessiné classique','Papier déchiré','Liseré doré'][i]}</option>)}</select></label>}
 {node.type==='text'&&<><label>Mon texte<textarea aria-label="Mon texte manuscrit" value={node.text} maxLength={160} onChange={e=>edit({text:e.target.value})}/></label><label>Encre<select aria-label="Couleur du texte" value={node.color} onChange={e=>edit({color:e.target.value})}><option value="cassis">Cassis</option><option value="ink">Brun</option><option value="sage">Sauge</option></select></label></>}
 </div>}
 <nav className="nmScrapTabs" aria-label="Décorer la page">{[['photos','Photos',Image],['sticker','Stickers',Flower2],['tape','Scotchs',Sticker],['background','Fonds',Palette],['text','Texte',Type]].map(([key,label,Icon])=><button key={key} aria-pressed={tab===key} onClick={()=>{setTab(key);if(mood==='tech'&&key!=='sticker')setMood('all');}}><Icon size={18}/>{label}</button>)}</nav>
 {['sticker','tape','background'].includes(tab)&&<label className="nmScrapMood">Afficher<select aria-label="Moods des décors" value={mood} onChange={e=>setMood(e.target.value)}><option value="all">Tous les décors</option>{tab==='sticker'&&<option value="tech">Techniques</option>}{scrapMoods.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}
 <div className="nmScrapPalette">
 {tab==='photos'&&entries.map(e=><button key={e.id} className="nmScrapPhotoChoice" onClick={()=>add('photo',{ref:e.id,frame:'classic'})}>{renderVisual(e)}<span>{e.title||'Ma pose'}</span></button>)}
 {['sticker','tape'].includes(tab)&&scrapAssets.filter(a=>a.type===tab&&filter(a)).map(a=><button key={a.id} aria-label={'Ajouter '+a.moodLabel+' · '+a.label} onClick={()=>add(a.type,{asset:a.id})}><ScrapSprite asset={a}/><span>{a.label}</span><small>{a.moodLabel}</small></button>)}
 {tab==='background'&&scrapBackgrounds.filter(filter).map(bg=><button key={bg.id} aria-label={'Fond '+bg.label} aria-pressed={draft.background===bg.id} onClick={()=>commit({...draft,background:bg.id})}><span className={'nmScrapSwatch background-'+bg.index} style={pageStyle(bg.id)}/><span>{bg.label}</span></button>)}
 {tab==='text'&&<button onClick={()=>add('text',{text:'Mon souvenir',color:'cassis'})}><Type/><span>Ajouter un texte manuscrit</span></button>}
 </div>{error&&<p role="alert">{error}</p>}
 </Sheet>;
}
