import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {Button} from './UI';
const steps=[['home','Accueil','Ici, retrouve les idées qui correspondent à ton univers.'],['feed','Fil','Découvre les créations et inspirations publiques de la communauté.'],['create','Créer','Inspire-moi, Scan & Génère, création libre ou import photo : pars de ton envie.'],['collection','Collection','Retrouve tes vernis, produits, stickers et matériel.'],['journal','Mes poses','Conserve tes créations, photos et recettes.'],['profile','Profil','Modifie tes préférences, tes univers et l’ambiance de ton NailMoods.']];
export default function CoachTour({onNavigate,onFinish}){
 const [step,setStep]=useState(0),[rect,setRect]=useState(null);const box=useRef(null),firstFocus=useRef(document.activeElement),navigate=useRef(onNavigate);navigate.current=onNavigate;
 useEffect(()=>{navigate.current(steps[step][0]);},[step]);
 useLayoutEffect(()=>{let target;const update=()=>{target?.classList.remove('nmTourTarget');target=document.querySelector('[data-tour="'+steps[step][0]+'"]');target?.classList.add('nmTourTarget');setRect(target?.getBoundingClientRect()||null);};update();const frame=requestAnimationFrame(update);window.addEventListener('resize',update);window.addEventListener('scroll',update,{passive:true});box.current?.focus();return()=>{cancelAnimationFrame(frame);target?.classList.remove('nmTourTarget');window.removeEventListener('resize',update);window.removeEventListener('scroll',update);};},[step]);
 useEffect(()=>()=>{firstFocus.current?.focus?.();},[]);
 function finish(){onFinish();}
 return <><div className="nmTourShade" aria-hidden="true"/><section className="nmCoach" ref={box} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="nm-tour-title" style={step===5?{top:Math.max(90,(rect?.bottom||70)+12)}:{bottom:Math.max(102,innerHeight-(rect?.top||innerHeight-90)+12)}} onKeyDown={e=>{if(e.key==='Escape')finish();if(e.key==='Tab'){const buttons=[...box.current.querySelectorAll('button:not(:disabled)')];const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===box.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><p className="nmEyebrow">TA VISITE · {step+1} / {steps.length}</p><h2 id="nm-tour-title">{steps[step][1]}</h2><p>{steps[step][2]}</p><div className="nmCoachActions"><Button variant="ghost" onClick={finish}>Passer</Button>{step>0&&<Button variant="ghost" onClick={()=>setStep(s=>s-1)}>Retour</Button>}<Button onClick={()=>step===steps.length-1?finish():setStep(s=>s+1)}>{step===steps.length-1?'Terminer':'Suivant'}</Button></div></section></>;
}
