import {UniverseTiles,PreferenceTiles} from './ProfileModules';
import {MoodMiniature} from './UI';
import ProfileAvatar from './ProfileAvatar';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Palette,Camera,Library,Sparkles} from 'lucide-react';
import {choices} from '../profileOptions';
import {TAGS} from '../social/tagTaxonomy';
import MoodGlyph from '../MoodGlyph';
import ProfileNail from '../ProfileNail';
import {useSocial} from '../social/SocialContext';
import {MoodPicker,Button} from './UI';
import {profileMood} from './themes';
import {preferenceFields,completeOnboarding} from './onboarding';
const slides=[['Bienvenue dans NailMoods','Explore, crée et garde toutes tes inspirations nail art. Un espace à ton image.'],['Des idées pour chaque mood','Tes envies et tes univers inspirent tes prochaines créations.'],['Ta créativité, sans limites','Inspire-moi, Scan & Génère, création libre, import photo : choisis ton point de départ.'],['Prête à créer ton univers ?','Quelques préférences, tes univers favoris et une ambiance qui te ressemble.']];
export default function Onboarding({profile,onChange,onDone,onCancel,identityExtras,appearanceExtras}){
 const [step,setStep]=useState(()=>Math.max(0,Math.min(7,profile.onboarding_step||0))),[query,setQuery]=useState(''),[error,setError]=useState('');
 const heading=useRef(null),social=useSocial();
 useEffect(()=>{heading.current?.focus();window.scrollTo(0,0);},[step]);
 function save(p){const ok=onChange({...p,onboarding_completed:false,onboarding_step:step});setError(ok?'':'Ton profil n’a pas été enregistré. Réessaie avant de continuer.');return ok;}
 function move(next){if(onChange({...profile,onboarding_completed:false,onboarding_step:next})){setStep(next);setError('');}else setError('Enregistrement impossible. Réessaie.');}
 const toggle=value=>save({...profile,styles:profile.styles.includes(value)?profile.styles.filter(v=>v!==value):[...profile.styles,value]});
 const all=TAGS.filter(t=>['style','ambiance','theme','envie'].includes(t.category));
 const visible=all.filter(t=>!query||t.label.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr'))).sort((a,b)=>Number(profile.styles.includes(b.label))-Number(profile.styles.includes(a.label)));
 const title=step<4?slides[step][0]:['Parlons un peu de toi','Choisis tes univers','Ton NailMoods, ton ambiance','Ton profil est prêt !'][step-4];
 return <div className={"nmOnboarding nmBrandOnboarding step-"+step}><div className="nmOnboardingTop"><img src={import.meta.env.BASE_URL+'nailmoods-symbol.png'} alt="NailMoods"/><span>{step<4?'BIENVENUE':'TON UNIVERS'}</span>{step>0&&<button aria-label="Étape précédente" onClick={()=>move(step-1)}><ArrowLeft/></button>}{onCancel&&<button onClick={onCancel}>Fermer</button>}</div><main><div className="nmOnboardingProgress" aria-hidden="true">{[0,1,2,3].map(i=><i key={i} className={(step<4?0:step-4)>=i?'active':''}/>)}</div><p className="nmEyebrow">{step<4?'FAIS COMME CHEZ TOI':(step-3)+' / 4 · TON PROFIL PREND VIE'}</p><h1 tabIndex={-1} ref={heading}>{title}</h1>
 {step<4?<><p className="nmIntroCopy">{slides[step][1]}</p><div className={'nmOnboardingArt art-'+step} aria-hidden="true">{step===0?<><img src={import.meta.env.BASE_URL+'nailmoods-symbol.png'}/><span>Explore.<br/>Crée.<br/><em>Ressens.</em></span></>:step===1?<>{['Dark feminine','Cottagecore','Witchy','Goth romantique'].map(v=><div key={v}><MoodGlyph value={v}/><span>{v}</span></div>)}</>:step===2?<>{[[Sparkles,'Inspire-moi'],[Camera,'Scan & Génère'],[Palette,'Création libre'],[Library,'Ma collection']].map(([Icon,t])=><div key={t}><Icon/><span>{t}</span></div>)}</>:<><div className="nmIntroMoodPreview"><MoodMiniature mood={profileMood(profile)}/></div><span className="nmIntroSignature">Même app.<br/>Différents moods.<br/><em>Toujours toi. ♡</em></span></>}</div><div className="nmSlideDots" aria-label={'Introduction '+(step+1)+' sur 4'}>{slides.map((_,i)=><i key={i} className={i===step?'active':''}/>)}</div></>:null}
 {step===4&&<><p>Tu peux tout modifier plus tard dans ton profil. Les valeurs proposées servent de point de départ.</p><label className="nmField">Prénom ou pseudo<input maxLength={80} value={profile.name} autoComplete="given-name" onChange={e=>save({...profile,name:e.target.value})} placeholder="Comment t’appelles-tu ?"/></label><div className="nmPreferenceForm">{preferenceFields.map(([key,label])=><label className="nmField" key={key}>{label}<select aria-label={label} value={profile[key]} onChange={e=>save({...profile,[key]:e.target.value})}>{choices[key].values.map(v=><option key={Array.isArray(v)?v[0]:v}>{Array.isArray(v)?v[0]:v}</option>)}</select></label>)}</div><Button variant="ghost" onClick={()=>move(5)}>Garder ces préférences pour commencer</Button></>}
 {step===5&&<><p>Sélectionne ce qui te ressemble. Plusieurs univers peuvent cohabiter.</p><label className="nmField">Rechercher un univers<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Witchy, floral, cottagecore…"/></label><p role="status">{profile.styles.length} univers sélectionné{profile.styles.length>1?'s':''}</p><div className="nmUniverseGrid">{visible.map(t=><button key={t.id||t.label} aria-pressed={profile.styles.includes(t.label)} onClick={()=>toggle(t.label)}><MoodGlyph value={t.label}/><span>{t.label}</span>{profile.styles.includes(t.label)&&<Check size={16}/>}</button>)}</div>{!visible.length&&<p>Aucun univers trouvé. Essaie un autre mot.</p>}</>}
 {step===6&&<><p>Tu changes l’ambiance de ton NailMoods. Tes univers et toutes tes fonctionnalités restent avec toi.</p><MoodPicker value={profileMood(profile).id} onChange={id=>save({...profile,visualMood:id,theme:id})}/></>}
 {step===7&&<><section className="nmProfilePreview nmBento"><ProfileAvatar profile={profile} big/><h2>{profile.name||'Mon univers NailMoods'}</h2>{social?.identity?.username&&<p>@{social.identity.username}</p>}<p>{profile.bio||'Un espace pour toutes tes envies de nail art.'}</p><UniverseTiles values={profile.styles}/><PreferenceTiles profile={profile}/><div className="nmRecapMood"><span className="nmPalette" aria-hidden="true">{profileMood(profile).colors.map(c=><i key={c} style={{background:c}}/>)}</span><span>{profileMood(profile).name}</span></div></section><label className="nmField">Ma bio personnelle · facultatif<textarea value={profile.bio||''} maxLength={300} onChange={e=>save({...profile,bio:e.target.value})}/></label><p className="nmCaption">Ces informations restent privées par défaut. Tu peux choisir leur visibilité dans Confidentialité & données.</p>{identityExtras&&<details className="nmDisclosure"><summary>Identifiant et visibilité</summary>{identityExtras}</details>}{appearanceExtras&&<details className="nmDisclosure"><summary>Personnaliser ma photo</summary>{appearanceExtras}</details>}</>}
 {error&&<p role="alert">{error}</p>}<div className="nmOnboardingActions">{step<4&&<Button variant="ghost" onClick={()=>move(4)}>Passer l’introduction</Button>}{step===5&&<Button variant="ghost" onClick={()=>move(6)}>Explorer plus tard</Button>}<Button onClick={()=>{if(step===7){if(onChange(completeOnboarding(profile)))onDone();else setError('Ton profil n’a pas pu être enregistré. Réessaie.');}else move(step+1);}}>{step===7?'Entrer dans NailMoods':step===0?'Commencer':'Suivant'}<ArrowRight size={18}/></Button></div></main></div>;
}
