import React from 'react';
import {Check,Heart,Sparkles} from 'lucide-react';
import MoodGlyph from '../MoodGlyph';
import {visualMoods,themeStyle} from './themes';
import './profile-experience.css';
import './brand-splash.css';
export function Button({variant='primary',busy=false,children,...props}){return <button {...props} disabled={props.disabled||busy} aria-busy={busy||undefined} className={'nmButton nmButton-'+variant+' '+(props.className||'')}>{busy?<span className="nmLoader" aria-hidden="true"/>:null}{children}</button>;}
export function BentoCard({as:Tag='section',tone='',className='',children,...props}){return <Tag {...props} className={'nmBento '+tone+' '+className}>{children}</Tag>;}
export function MoodMiniature({mood}){return <div className="nmMiniPreview" aria-hidden="true"><span className="nmMiniBrand"><img src={import.meta.env.BASE_URL+'nailmoods-symbol.png'} alt=""/>NailMoods<Heart/></span><span className="nmMiniHeading">De belles idées.<em>À ton image.</em></span><div className="nmMiniBento"><span><MoodGlyph value="Cottagecore"/><i>Mes univers</i></span><span><Sparkles/><i>Mon mood</i></span></div><span className="nmMiniCTA">Créer une idée <span>+</span></span><span className="nmMiniNav"><i/><i/><i/><i/><i/></span></div>;}
export function MoodPicker({value,onChange}){return <div className="nmMoodGrid" role="group" aria-label="Ambiance de NailMoods">{visualMoods.map(m=><button key={m.id} className="nmMoodOption" aria-pressed={m.id===value} onClick={()=>onChange(m.id)} style={themeStyle(m)}><MoodMiniature mood={m}/><strong>{m.name}</strong><small>{m.description}</small><span className="nmPalette" aria-hidden="true">{m.colors.map(c=><i key={c} style={{background:c}}/>)}</span><span className="nmMoodState">{m.id===value?<><Check size={16}/>Choisie</>:'Choisir'}</span></button>)}</div>;}
export function Splash({error,children}){return <main className="nmSplash nmBrandSplash"><div className="nmSplashPetal" aria-hidden="true"/><div className="nmSplashDoodle" aria-hidden="true"><Heart/><Sparkles/></div><div className="nmSplashContent"><span className="nmSplashEyebrow">TON INSTANT CRÉATIF</span><div className="nmSplashLogo"><img src={import.meta.env.BASE_URL+'nailmoods-symbol.png'} alt=""/></div><h1>NailMoods</h1><p className="nmSplashMotto">Plus qu’une inspiration,<br/><em>un état d’esprit.</em></p><div className="nmSplashLoading"><p role={error?'alert':'status'}>{error||'Ouverture de ton espace…'}</p>{!error&&<span className="nmSplashProgress" aria-hidden="true"/>}{children}</div></div><p className="nmSplashSignature">Même app. Différents moods.<br/>Toujours toi. ♡</p></main>;}
export function Skeleton({label='Chargement…'}){return <div className="nmSkeleton" role="status"><span>{label}</span><div aria-hidden="true"><i/><i/><i/></div></div>;}
