import ProfileAvatar from './design/ProfileAvatar';
import {MoodPicker} from './design/UI';
import {profileMood} from './design/themes';
import { ProfileIdentity } from './identity/IdentityPanel';
import MoodGlyph from './MoodGlyph';
import ProfileNail from './ProfileNail';
import React, { useState } from 'react';
import { ChevronRight, X, Check, Palette, UserRound, Camera, Sparkles, Search, ArrowRight, Pencil } from 'lucide-react';
import { avatars, choices } from './profileOptions';
import { TAGS, querySuggestions } from './social/tagTaxonomy';
import Sheet from './Sheet';
import { productColor } from './colorAnalysis';
import { PersonalizationSummary } from './PersonalizationView';
import './profile.css';

const universeGroups = [
  ['Styles', 'style'], ['Envies', 'envie'], ['Ambiances', 'ambiance'], ['Techniques', 'technique'], ['Effets', 'finish'], ['Thèmes', 'theme'],
].map(([label, category]) => [label, TAGS.filter(tag => tag.category === category).map(tag => tag.label)]);

export default function ProfileView({ journal,library,onJournal,onOpen,onRestartOnboarding,route, onHelp, accountAccess, identityExtras, extras, appearanceExtras, onCreate, onEquipment, onFavorites, profile, items, onChange, onCollection, personalModel, personalSettings, onPersonalization }) {
  const section = route?.split('/')[1] || '';
  const titles = {preferences:'Mes préférences',ambiance:'Mon ambiance',account:'Réglages',offer:'Mon offre',privacy:'Confidentialité & données',social:'Connexions et comptes bloqués',pro:'Espace Pro',staff:'Journal staff'};
  const openSection = key => { window.location.hash = 'profil' + (key ? '/' + key : ''); window.scrollTo({top:0}); };
  const [picker, setPicker] = useState(null);
  const [panel, setPanel] = useState(section==='ambiance'?'theme':null);
  const [universes, setUniverses] = useState(false);
  const [query, setQuery] = useState('');
  const av = avatars.find(avatar => avatar[0] === profile.avatar);
  const choose = (key, value) => { if (onChange({ ...profile, [key]: value })) setPicker(null); };
  const toggleStyle = style => onChange({ ...profile, styles: profile.styles.includes(style) ? profile.styles.filter(value => value !== style) : [...profile.styles, style] });
  const avatar = big => <ProfileAvatar profile={profile} big={big}/>;
  const tile = (key, label) => <button key={key} className="settingTile" onClick={() => setPicker(key)}><small>{label}</small><b>{profile[key]}</b><ChevronRight /></button>;
  return <div className="profilePage">
    {!section ? <>    <section className="profileHero"><button className="profileAvatarButton" aria-label="Modifier mon avatar et le thème" aria-haspopup="dialog" onClick={() => setPanel('appearance')}>{avatar(true)}<span className="avatarEditHint" aria-hidden="true"><Pencil size={12} /></span></button><div><small>MON UNIVERS</small><h1>{profile.name || 'Mon profil'}</h1><ProfileIdentity /><p>{profile.bio||"Ton profil guide tes inspirations."}</p></div></section>
<div className="nmProfileBento"><section className="nmBento"><div className="nmSectionHead"><h2>Mes univers</h2><button onClick={()=>setUniverses(true)}>Modifier</button></div><div className="favoriteStyles">{profile.styles.length?profile.styles.map(v=><span key={v} className="nmMoodChip"><MoodGlyph value={v}/>{v}</span>):<p>Choisis les univers qui te ressemblent.</p>}</div></section><section className="nmBento"><div className="nmSectionHead"><h2>Mes préférences</h2><button onClick={()=>openSection('preferences')}>Modifier</button></div><dl className="nmPreferenceSummary">{[['shape','Forme'],['length','Longueur'],['level','Niveau'],['duration','Temps'],['technique','Type de pose']].map(([k,t])=><div key={k}><dt>{t}</dt><dd>{profile[k]}</dd></div>)}</dl></section><section className="nmBento"><div className="nmSectionHead"><h2>Mon ambiance</h2><button onClick={()=>setPanel('theme')}>Changer</button></div><p>{profileMood(profile).name} · {profileMood(profile).description}</p><div className="nmMoodSummary" aria-hidden="true">{profileMood(profile).colors.map(c=><i key={c} style={{background:c}}/>)}</div></section><section className="nmBento"><div className="nmSectionHead"><h2>Mes poses</h2><button onClick={()=>{window.location.hash='journal';}}>Tout voir</button></div><div className="nmProfileRecent">{journal?.entries?.slice(0,3).map(e=><button key={e.id} onClick={()=>onJournal(e.id)}>{e.photo&&<img src={e.photo} alt=""/>}<span>{e.title||'Ma pose'}<small>{e.date}</small></span></button>)}{!journal?.entries?.length&&<p>Ta prochaine pose deviendra un joli souvenir.</p>}</div></section><section className="nmBento"><div className="nmSectionHead"><h2>Mes inspirations</h2><button onClick={onFavorites}>Tout voir</button></div><div className="nmProfileRecent">{library?.favorites?.slice(0,3).map(e=><button key={e.key} onClick={()=>onOpen(e)}>{e.title}</button>)}{!library?.favorites?.length&&<p>Garde ici les idées que tu aimes.</p>}</div></section></div>
<div className="profileDestinations">{Object.entries(titles).filter(([key])=>key!=='account'&&!['offer','social','pro','staff'].includes(key)||extras?.[key]).map(([key,label])=><button className="nmShortcut" key={key} onClick={()=>openSection(key)}><span>{label}</span><ChevronRight/></button>)}<button className="nmShortcut profileSecondary" onClick={()=>openSection('account')}><span>Réglages · informations personnelles</span><ChevronRight/></button><button className="nmShortcut" onClick={()=>window.dispatchEvent(new Event("nm-tour-replay"))}><span>Rejouer la visite guidée</span><ChevronRight/></button><button className="nmShortcut" onClick={onRestartOnboarding}><span>Revoir mon accueil personnel</span><ChevronRight/></button><button className="nmShortcut" onClick={onHelp}><span>Aide & support</span><ChevronRight/></button></div></> : <><button className="nmQuiet" onClick={()=>openSection('')}>← Mon profil</button><h1>{titles[section] || 'Mon profil'}</h1></>}
    {section==='preferences' && <>
    <section className="card"><h2>À propos de moi</h2><p>Quelques informations pour des idées qui te ressemblent. Tu peux aussi créer une idée sans compléter ton profil.</p>
      <div className="profileGrid">{tile('shape', 'FORME')}{tile('length', 'LONGUEUR')}{tile('level', 'NIVEAU')}{tile('duration', 'TEMPS')}<div className="wide">{tile('technique', 'TYPE DE POSE')}</div></div>
    </section>
    <section className="card"><div className="titleRow"><div><h2>Mes univers</h2><p>Ce que tu aimes aujourd’hui.</p></div><button className="explore" onClick={() => setUniverses(true)}>Explorer</button></div>
      {!profile.styles.length && <p>Choisis les univers qui te ressemblent, ou explore librement.</p>}<div className="favoriteStyles">{profile.styles.map(style => <button key={style} aria-label={'Retirer ' + style} onClick={() => toggleStyle(style)}><MoodGlyph value={style} />{style}<X /></button>)}</div><button className="outline" onClick={() => setUniverses(true)}>+ Ajouter des univers</button>
    </section>
    <section className="card"><h2>Mes techniques</h2><div className="techList">{[['stickers', 'Stickers & décos'], ['french', 'French & lignes'], ['freehand', 'Dessin à main levée'], ['effects', 'Effets / poudres / chrome']].map(([key, label]) => <button key={key} onClick={() => setPicker(key)}><span>{label}</span><b>{profile[key]}</b><ChevronRight /></button>)}</div></section>
    <section className="profileShortcuts" aria-label="Mon NailMoods"><button onClick={onCollection}><Palette /><span>Ma collection<small>Mes couleurs et produits</small></span><ChevronRight /></button><button onClick={onEquipment}><Sparkles /><span>Mon matériel<small>Mes outils et stickers</small></span><ChevronRight /></button><button onClick={onFavorites}><Palette /><span>Mes inspirations<small>Mes idées sauvegardées</small></span><ChevronRight /></button><button onClick={onCreate}><Sparkles /><span>Créer une idée avec mes préférences<small>À adapter selon mon envie</small></span><ArrowRight /></button></section>
    <PersonalizationSummary model={personalModel} settings={personalSettings} onOpen={onPersonalization} />
    </>}
    {section==='account' && <><section className="card"><h2>Informations personnelles</h2><label>Prénom<input value={profile.name} onChange={e=>onChange({...profile,name:e.target.value})}/></label></section><section className="card"><label>Ma bio personnelle<textarea maxLength={300} value={profile.bio||''} onChange={e=>onChange({...profile,bio:e.target.value})}/></label><p className="nmCaption">Privée par défaut. Choisis les informations visibles dans Confidentialité & données.</p></section>{identityExtras}{accountAccess}</>}
    {section==='privacy'&&<section className="card"><h2>Visible sur mon profil</h2><p>Ces informations sont privées par défaut. Elles ne seront montrées qu’aux personnes autorisées à consulter ton profil public.</p>{[['bio','Ma bio personnelle'],['universes','Mes univers'],['preferences','Mes préférences de pose']].map(([key,label])=><label className="nmVisibilityToggle" key={key}><input type="checkbox" checked={profile.publicProfile?.[key]===true} onChange={e=>onChange({...profile,publicProfile:{...profile.publicProfile,[key]:e.target.checked}})}/><span>{label}</span></label>)}</section>}
    {['offer','privacy','social','pro','staff'].includes(section) && extras?.[section]}
    {picker && <Sheet title={choices[picker].title} eyebrow="MON NAILMOODS" onClose={() => setPicker(null)} className="profileSheet">
      {choices[picker].visual ? <div className="visualOptions">{choices[picker].values.map(([value, description, shape]) => <button key={value} className={profile[picker] === value ? 'selected' : ''} aria-pressed={profile[picker] === value} onClick={() => choose(picker, value)}><ProfileNail variant={shape} /><b>{value}</b><span>{description}</span>{profile[picker] === value && <em><Check /></em>}</button>)}</div> : <div className="optionList">{choices[picker].values.map(value => <button key={value} className={profile[picker] === value ? 'selected' : ''} aria-pressed={profile[picker] === value} onClick={() => choose(picker, value)}><span>{value}</span>{profile[picker] === value && <Check />}</button>)}</div>}
    </Sheet>}
    {panel === 'appearance' && <Sheet title="Apparence de mon NailMoods" onClose={() => setPanel(null)} className="profileSheet"><div className="appearance">
      <button onClick={() => setPanel('theme')}><Palette /><span><b>Thème de l’application</b><small>{profileMood(profile).name}</small></span><ChevronRight /></button>
      <button onClick={() => setPanel('avatar')}><UserRound /><span><b>Photo / Avatar</b><small>{profile.avatarMode === 'avatar' ? av?.[1] : 'Initiales'}</small></span><ChevronRight /></button>
    </div></Sheet>}
    {section==='ambiance'&&panel!=='theme'&&<section className="card"><MoodPicker value={profileMood(profile).id} onChange={id=>onChange({...profile,visualMood:id,theme:id})}/></section>}
    {panel === 'theme' && <Sheet title="Choisis ton ambiance" onClose={() => setPanel(null)} className="profileSheet"><p>Même NailMoods, une autre ambiance. Tes univers préférés restent les mêmes.</p><MoodPicker value={profileMood(profile).id} onChange={id=>onChange({...profile,visualMood:id,theme:id})}/><button className="primarySticky inSheet" onClick={()=>setPanel(null)}>Garder cette ambiance</button></Sheet>}
    {panel === 'avatar' && <Sheet title="Photo ou avatar" onClose={() => setPanel(null)} className="profileSheet">{appearanceExtras}<div className="avatarModes"><button className={profile.avatarMode === 'initials' ? 'selected' : ''} aria-pressed={profile.avatarMode === 'initials'} onClick={() => onChange({ ...profile, avatarMode: 'initials' })}>{avatar(false)}<b>Initiales</b></button><button disabled><div className="avatar"><Camera /></div><b>Ma photo</b><small>Bientôt disponible</small></button></div><h3 className="subhead">Avatars NailMoods</h3><div className="avatarGrid">{avatars.map(avatar => <button key={avatar[0]} className={profile.avatarMode === 'avatar' && profile.avatar === avatar[0] ? 'selected' : ''} aria-pressed={profile.avatarMode === 'avatar' && profile.avatar === avatar[0]} onClick={() => onChange({ ...profile, avatarMode: 'avatar', avatar: avatar[0] })}><div className={'avatar avatarArt av-' + avatar[0]}>{avatar[2]}</div><span>{avatar[1]}</span></button>)}</div><button className="primarySticky inSheet" onClick={() => setPanel(null)}>Garder mon avatar</button></Sheet>}
    {universes && <Sheet title="Explorer les univers" onClose={() => setUniverses(false)} className="profileSheet universePicker"><div className="search"><Search /><input aria-label="Rechercher un univers" value={query} onChange={event => setQuery(event.target.value)} placeholder="Rechercher un univers, une technique…" /></div>{universeGroups.map(([group, values]) => { const suggestions = new Set(querySuggestions(query, 100).map(tag => tag.label)); const filtered = values.filter(style => !query || style.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')) || suggestions.has(style)); return filtered.length ? <div className="universeGroup" key={group}><h3>{group}</h3><div className="chips">{filtered.map(style => <button key={style} className={profile.styles.includes(style) ? 'on' : ''} aria-pressed={profile.styles.includes(style)} onClick={() => toggleStyle(style)}><MoodGlyph value={style} />{style}</button>)}</div></div> : null; })}{query && !universeGroups.some(([, values]) => values.some(style => style.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')) || querySuggestions(query, 100).some(tag => tag.label === style))) && <p className="universeEmpty">Aucun tag correspondant.</p>}</Sheet>}
  </div>;
}
